{
  "hash": "e6a06085205fc019fdc0f12a80477162",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Intervalos de Confianza y Test de hipótesis\"\ndate: \"2026-08-19\"\nlang: es\nexecute:\n  freeze: auto\n  cache: true\nnumber-sections: true\nformat:\n  html:\n    code-copy: true\n    highlight-style: github\n#lightbox: true\n---\n\n<style>\n/* Texto escrito entre comillas invertidas */\n:not(pre) > code {\n  color: #00695c !important;\n  background-color: #eef7f6 !important;\n  padding: 0.1em 0.3em;\n  border-radius: 4px;\n}\n\n/* Resultados producidos por R */\n.cell-output pre {\n  color: #17233a !important;\n  background-color: #e8f5f3 !important;\n  border-left: 4px solid #009688 !important;\n  padding: 0.8em 1em !important;\n}\n\n/* Evita que el tema cambie el color del texto de las salidas */\n.cell-output pre code {\n  color: #17233a !important;\n  background-color: transparent !important;\n}\n\n/* Comentarios (#) dentro de los chunks de código */\ncode span.co {\n  color: #5c7a2c !important;\n}\n\n/* Tamaño de fuente de los chunks de código */\ndiv.sourceCode pre code {\n  font-size: 1.15em;\n}\n</style>\n\n# Objetivo de la práctica {.unnumbered}\n\nEl objetivo de esta guía práctica es repasar intervalos de confianza, y además aplicar las herramientas teóricas y prácticas aprendidas hasta el momento para realizar pruebas de hipótesis, tanto para diferencias de medias como direccionales utilizando la prueba **_t_**.\n\nEn detalle, en el práctico de hoy veremos:\n\n1) Cálculo e interpretación de intervalos de confianza\n\n2) Formular hipótesis, realizar una prueba t en R e interpretar sus principales resultados.\n\n# Repaso intervalos de confianza\n\nRecordemos que un intervalo de confianza es **la mejor estimación del rango de un estadístico en la población (parámetro poblacional) con una muestra aleatoria**\n\nEl nivel de confianza describe qué tan frecuentemente este procedimiento produciría intervalos que contienen la verdadera media poblacional si repitiéramos muchas veces el muestreo.\n\n![](https://correlacional.netlify.app/slides/img/intervalos.png)\n\n\n\nA modo de repasar el contenido de intervalos a confianza, resolveremos el ejercicio autónomo de la última sesión práctica. Trabajaremos con el conjunto de datos `Galton`, incluido en el paquete `HistData`, que contiene las estaturas de 928 hijos e hijas adultos recopiladas por Francis Galton en 1886. \n\nEste es, de hecho, el conjunto de datos histórico que dio origen al estudio de la curva normal aplicada a variables biológicas.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!requireNamespace(\"pacman\", quietly = TRUE)) install.packages(\"pacman\") # Si no está instalado, instala el paquete\npacman::p_load(HistData)\ndata(\"Galton\")\n\nnames(Galton) # revisar las variables disponibles: \"parent\" y \"child\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"parent\" \"child\" \n```\n\n\n:::\n\n```{.r .cell-code}\naltura <- Galton$child # creamos el vector con la variable de interés\n```\n:::\n\n\n::: callout-important\nLa función `p_load` del paquete `pacman` simplifica el proceso de carga de paquetes, ya que se pueden cargar varios paquetes a la vez y, en caso de que alguno de esos paquetes no esté previamente instalado, p_load lo reconoce e instala\n:::\n\nLa unidad de medida de la variable se encuentra en pulgadas.\n\n::: callout-tip\n**Los \\# en el código**\n\nEn este código y siguientes aparecen varios #, que son una función de comentarios en R. Todo lo escrito después de # es un comentario para explicar el código o texto. R no lo ejecuta.\n\nPueden servir como herramientas para tomar apuntes mientras se trabaja en el código\n:::\n\n\n1.  Calcule y describa la distribución\n\n-   Obtenga la media y desviación estándar de la estatura.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedia <- mean(Galton$child)\ndesv_estandar <- sd(Galton$child)\n\nmedia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 68.08847\n```\n\n\n:::\n\n```{.r .cell-code}\ndesv_estandar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.517941\n```\n\n\n:::\n:::\n\n\n-   Visualice la distribución en un histograma\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(Galton$child,main=\"Histograma del Vector\",xlab=\"Valor\",ylab=\"Frecuencia\",col=\"cyan4\",border=\"black\")\n```\n\n::: {.cell-output-display}\n![](02-practico_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n2.  Estandarice los datos (puntajes Z)\n\n-   Transforme la variable a puntajes Z\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_scores <- (Galton$child - media) / desv_estandar # aplicamos la fórmula del puntaje Z a la variable child dentro de la base de datos Galton\n```\n:::\n\n\n-   Muestre los primeros 6 valores (`head()`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(z_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2.537180 -2.537180 -2.537180 -2.537180 -2.537180 -2.338605\n```\n\n\n:::\n:::\n\n\n-   Muestre también los últimos 6 valores (`tail()`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(z_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.228618 2.228618 2.228618 2.228618 2.228618 2.228618\n```\n\n\n:::\n:::\n\n\n-   ¿Cuál es el máximo puntaje Z y el mínimo puntaje Z? ¿A qué estatura corresponden?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax <- max(z_scores)\nmax\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.228618\n```\n\n\n:::\n:::\n\n\nEl máximo puntaje Z corresponde a 2.23. Esto significa que el hijo o hija más alto se encuentra 2.23 desviaciones estándar sobre el promedio\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin <- min(z_scores)\nmin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2.53718\n```\n\n\n:::\n:::\n\n\nEl mínimo puntaje corresponde a -2.53, lo que se entiende como que el hijo o hija más bajo se encuentra -2.53 desviaciones estándar bajo el promedio\n\n**Obteniendo valores observados a partir de puntajes Z**\n\nEn el ejericio anterior, calculamos los puntajes Z para valores específicos de la variable estatura, en específico el mínimo y máximo. Esto nos permitió conocer cuántas desviaciones estándar se encontraba cada valor respecto de la media.\n\nTambiés es posible hacer el ejercicio inverso, es decir, **calcular el valor observado a partir de un puntaje Z**. Para esto, utilizaremos la fórmula del puntaje Z y despejaremos el valor observado.\n\nRecordemos que la fórmula del puntaje Z es:\n$$ \nZ = \\frac{X - \\mu}{\\sigma}\n$$\n\nPor lo tanto,si queremos obtener el valor observado, debemos despejar X de la fórmula:\n\n$$\nX = Z \\cdot \\sigma + \\mu\n$$\n\nPara verificar, veamos que pasa con el valor observado del puntaje Z máximo, que es 2.23:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(max * desv_estandar) + media\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 73.7\n```\n\n\n:::\n:::\n\n\nPor lo tanto conociendo Z también podemos volver a valores observados de la distribución original ... que en realidad ya conocemos, porque tenemos la variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax(Galton$child) # valor máximo de la variable original\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 73.7\n```\n\n\n:::\n:::\n\n\nPero, lo interesante es que podemos hacer esto mismo para un valor teórico de Z, que por ejemplo podría ser el límite superior de un intervalo de confianza al 99% (2.58). Entonces, si queremos saber cuál es el valor observado que corresponde a un puntaje Z de 2.58, podemos hacer lo siguiente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(2.58 * desv_estandar) + media\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 74.58476\n```\n\n\n:::\n:::\n\nPor lo tanto, el valor observado que corresponde a un puntaje Z de 2.58 es de 74.58 pulgadas, lo que significa que un 0,5% de los hijos e hijas miden más que este valor (ya que el 99% de la distribución se encuentra entre \\pm 2.58 desviaciones estándar de la media, y el restante 1% se divide en 0.5% por cada cola de la distribución). \n\n1.  Calcule el error estándar de la variable\n\n::: callout-important\nRecordemos que la fórmula del error estándar es:\n$$\nSE = \\frac{s}{\\sqrt{n}}\n$$\n\nDonde:\n\n$s$ es la desviación estándar de la muestra.\n$n$ es el número de casos de la muestra.\n:::\n\nPara nuestro caso, reemplazamos los valores en la fórmula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_vector <- length(Galton$child)\n\nse <- desv_estandar / sqrt(n_vector)\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08265547\n```\n\n\n:::\n:::\n\n\nEsto quiere decir que el error estándar estimado de la distribución de medias muestrales es 0,083: nos indica cuánto tienden a variar las medias entre posibles muestras de igual tamaño.\n\n::: callout-important\nEl error estándar es una estimación de la **desviación estandar de los promedios de varias muestras** a partir de **una sola muestra**\n:::\n\n4.  Calcule el intervalo de confianza para la media\n\n-   Estime el IC para un 95% de confianza\n\n::: callout-important\nSu fórmula es la siguiente:\n\n$$\nIC = \\bar{x} \\pm z \\cdot \\frac{s}{\\sqrt{n}}\n$$\n\nDonde:\n\n- $\\bar{x}$ es la media de la muestra.\n- $z$ es el valor crítico.\n- $s$ es la desviación estándar de la muestra.\n- $n$ es el tamaño de la muestra.\n- $\\frac{s}{\\sqrt{n}}$ corresponde al error estándar.\n:::\n\nRecordemos que el valor crítico para un 95% de confianza es de 1.96 ([link al práctico anterior](https://correlacional.metodos-facso.org/assignment/01-practico.html))\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlim_inf <- media - 1.96 * se # Limite inferior del Intervalo\nlim_inf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67.92647\n```\n\n\n:::\n\n```{.r .cell-code}\nlim_sup <- media + 1.96 * se # Límite superior del Intervalo\nlim_sup\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 68.25047\n```\n\n\n:::\n:::\n\n\nGeneramos un gráfico para visualizar de mejor manera el intervalo de confianza que construimos\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Media muestral e intervalo de confianza del 95 %.](02-practico_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n::: {style=\"background-color: #b71c1c; color: #ffffff; border: 1px solid #8e0000; border-radius: 6px; padding: 0.8rem 1rem;\"}\nPodemos observar que contamos con una media muestral de 68.1 como estimación puntual. Ahora, se puede decir con un 95% de confianza que la media poblacional se encuentra entre 67.93 y 68.25.\n:::\n\n::: callout-important\nEn simple: si estimamos 100 intervalos de confianza, **95 de ellos contendrán la media poblacional**.\n:::\n\n-   Estime el IC para un 99% de confianza. ¿Qué sucede con el ancho del intervalo?\n\nEl puntaje para el intervalo de confianza a un 95% es 1.96. Para un intervalo de confianza al 99% es 2.58, el cual refiere a la **área acumulada bajo la curva normal**. Entonces, calculemos el intervalo de confianza\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlim_inf_99 <- media - 2.58 * se # Limite inferior del Intervalo\nlim_inf_99\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67.87522\n```\n\n\n:::\n\n```{.r .cell-code}\nlim_sup_99 <- media + 2.58 * se # Límite superior del Intervalo\nlim_sup_99\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 68.30172\n```\n\n\n:::\n:::\n\n\n::: {style=\"background-color: #b71c1c; color: #ffffff; border: 1px solid #8e0000; border-radius: 6px; padding: 0.8rem 1rem;\"}\nPodemos observar que al calcular el IC para un 99% de confianza, el ancho del intervalo se amplía, es decir, el rango donde se puede hallar el parámetro poblacional es mayor, encontrándose entre 67.88 y 68.30\n:::\n\nRecordemos que también podemos utilizar la función `t.test` para calcular el intervalo de confianza de manera mucho más rápida. Solamente debemos especificar el vector y el nivel de confianza.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Galton$child, conf.level = 0.99)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67.87512 68.30182\nattr(,\"conf.level\")\n[1] 0.99\n```\n\n\n:::\n:::\n\n\nAsí, llegamos a los mismos resultados.\n\n5.  Explore el efecto del tamaño muestral\n\n-   Generemos 2 submuestras aleatorias con la función `sample()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nmuestra_50 <- sample(altura, 50)\nmuestra_500 <- sample(altura, 500)\n```\n:::\n\n\n::: callout-note\nla función `set.seed` fija una semilla para que las secuencias de números \"aleatorios\" que produce R sean reproducibles. Es decir, asegura que otra persona que corra el mismo script obtenga los mismos resultados\n:::\n\n-   Calcule el error estándar y el intervalo de confianza al 95% de cada muestra ¿Qué pasa con el error estándar y el intervalo de confianza a medida que aumenta el tamaño de la muestra?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedia_50 <- mean(muestra_50)\ndesv_estandar_50 <- sd(muestra_50)\nn_media_50 <- length(muestra_50)\n\nse_50 <- desv_estandar_50 / sqrt(n_media_50)\nse_50\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3390383\n```\n\n\n:::\n:::\n\n\nCalculamos el intervalo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(muestra_50)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67.25868 68.62132\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\nLa media como estimación puntual es de 67.9, mientras que con un 95% de confianza podemos asegurar que el parámetro poblacional se encuentra entre **67.26 y 68.62**.\n\nAhora realicemos el mismo procedimiento con la muestra generada con 500 casos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedia_500 <- mean(muestra_500)\ndesv_estandar_500 <- sd(muestra_500)\nn_media_500 <- length(muestra_500)\n\nse_500 <- desv_estandar_500 / sqrt(n_media_500)\nse_500\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1109578\n```\n\n\n:::\n:::\n\n\nCalculamos el intervalo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(muestra_500)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67.832 68.268\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\nAl comparar el error estándar de la muestra de 50 con la muestra de 500, podemos ver que, **a medida que la muestra es más grande**, **el error estándar se vuelve más pequeño**.\n\nDe la misma manera, el intervalo de la muestra de 50 casos es de 67.28 y 68.60, mientras que el de la muestra de 500 es más reducido, conteniendo valores entre el 67.83 y 68.27. Así, podemos afirmar que **una muestra con mayor cantidad de casos** tenderá a entregar intervalos más pequeños, es decir, **estimaciones más precisas**\n\n-   Calcule el intervalo de confianza al 99% de cada muestra ¿Qué pasa con el intervalo de confianza a medida que aumenta el tamaño de la muestra?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(muestra_50, conf.level = 0.99)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67.03139 68.84861\nattr(,\"conf.level\")\n[1] 0.99\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(muestra_500, conf.level = 0.99)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67.76309 68.33691\nattr(,\"conf.level\")\n[1] 0.99\n```\n\n\n:::\n:::\n\n\n::: {style=\"background-color: #b71c1c; color: #ffffff; border: 1px solid #8e0000; border-radius: 6px; padding: 0.8rem 1rem;\"}\nA medida que la muestra se vuelve más grande, el error estándar se vuelve más pequeño, es decir, es más preciso en la estimación.\n\nA medida que el intervalo de confianza aumenta en su nivel de confiabilidad, el rango se vuelve más amplio y, en consecuencia, la estimación es menos precisa, **a menos que aumente su tamaño muestral**\n:::\n\n\n# Test de hipótesis\n\nHasta ahora utilizamos el error estándar para expresar la incertidumbre de una estimación mediante intervalos de confianza. Ahora usaremos esa misma idea de variabilidad muestral para responder una nueva pregunta: ¿las diferencias entre grupos que logramos observar en una muestra, pueden ser representativas de a nivel de la población?\n\nPara este punto, recurriremos a todas las herramientas que hemos aprendido hasta ahora:\n\n| Concepto | Definición |\n|----------|------------|\n| Curva normal | Distribución teórica que nos entrega un estándar para comparar distribuciones empíricas |\n| Teorema central del límite | Al calcular un estadístico de distintas muestras de una misma población, estos valores se distribuirán de manera normal |\n| Error estándar | Desviación estándar de los promedios de distintas muestras de una misma población |\n| Puntajes Z | Medida estandarizada la cual se expresa en términos de desviación estándar |\n| Intervalos de confianza | Rango de probabilidad de un parámetro poblacional |\n\n\nPara esta sección del práctico, trabajaremos con un subconjunto de datos previamente procesados de la Encuesta de Caracterización Socioeconómica (CASEN) del año 2022, elaborada por el [Ministerio de Desarrollo Social y Familia](https://observatorio.ministeriodesarrollosocial.gob.cl/). \n\nPara este ejercicio, obtendremos directamente esta base desde internet. No obstante, también tienes la opción de acceder a la misma información a través del siguiente enlace: [{{< fa table >}} `CASEN 2022`](https://github.com/cursos-metodos-facso/datos-ejemplos/raw/main/proc_casen.RData). Desde allí, podrás descargar el archivo que contiene el subconjunto procesado de la base de datos CASEN 2022.\n\n## Los cinco pasos para la inferencia estadística\n\nEn inferencia, las pruebas de hipótesis nos permiten evaluar qué tan compatibles son los resultados observados en nuestra muestra con una hipótesis planteada sobre la población. Aquí recomendamos una lista de cinco pasos lógicos para enfrentarnos a la inferencia estadística: \n\n<style>\n  table {\n    margin-left: auto; /* Ajustamos el margen izquierdo a automático */\n    margin-right: auto; /* Ajustamos el margen derecho a automático */\n    border-collapse: collapse;\n    width: 60%;\n    border: 2px solid black;\n  }\n  \n  th, td {\n    border: 1px solid #D3D3D3;\n    padding: 8px;\n    text-align: center;\n  }\n</style>\n\n<table>\n  <tr>\n    <th class=\"cell-left\">Paso</th>\n    <th class=\"cell-left\"> Detalle</th>\n  </tr>\n  <tr>\n    <td class=\"cell-left\">1</td>\n    <td class=\"cell-left\">Formula $H_0$ y $H_A$ y estipula la dirección de la prueba</td>\n  </tr>\n  <tr>\n    <td class=\"cell-left\">2</td>\n    <td class=\"cell-left\">Calcula el error estándar (SE) y el valor estimado de la prueba (ej: Z o t)</td>\n  </tr>\n  <tr>\n    <td class=\"cell-left\">3</td>\n    <td class=\"cell-left\">Especifica la probabilidad de error $\\alpha$ y el valor crítico de la prueba</td>\n  </tr>\n  <tr>\n    <td class=\"cell-left\">4</td>\n    <td class=\"cell-left\">Contrasta el valor estimado con el valor crítico</td>\n  </tr>\n  <tr>\n    <td class=\"cell-left\">5</td>\n    <td class=\"cell-left\">Interpreta los resultados</td>\n  </tr>\n</table>\n\n::: callout-important\nLa hipótesis nula ($H_{0}$) es la contraria a la hipótesis original, y es la buscamos **falsar** \n:::\n\nAdemás de estos 5 pasos también existe la posibilidad de calcular un intervalo de confianza, que acompañe la precisión de nuestra estimación.\n\n## Preparación datos\n\nComencemos por preparar nuestros datos. Iniciamos cargando las librerías necesarias.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(dplyr, # Manipulación datos\n               gginference, # Visualización \n               rempsyc, # Reporte\n               kableExtra, # Tablas\n               broom, # Varios\n               flextable # nice table\n               )\n\noptions(scipen = 999) # para desactivar notación científica\nrm(list = ls()) # para limpiar el entorno de trabajo\n```\n:::\n\n\n::: callout-important\n`dplyr` será uno de los paquetes más frecuentrados en nuestro flujo de trabajo, ya que nos entrega las herramientas esenciales para el procesamiento de datos sociales. Algunas de ellas nos permiten realizar el filtrado, selección, orden y creación de variables.\n:::\n\nCargamos los datos directamente desde internet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(url(\"https://github.com/cursos-metodos-facso/datos-ejemplos/raw/main/proc_casen.RData\")) #Cargar base de datos\n```\n:::\n\n\nA continuación, exploramos la base de datos **proc_casen**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(proc_casen) # Nombre de columnas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"id_vivienda\"      \"folio\"            \"id_persona\"       \"hogar\"           \n [5] \"nucleo\"           \"varunit\"          \"varstrat\"         \"expr\"            \n [9] \"edad\"             \"sexo\"             \"educ\"             \"activ\"           \n[13] \"y1\"               \"ytrabajocor\"      \"pobreza_multi_5d\" \"o15\"             \n[17] \"qaut\"             \"fdt\"              \"ocupado\"          \"desocupado\"      \n[21] \"inact\"            \"hijo\"             \"n_educ\"           \"universitaria\"   \n[25] \"tipo_ocup\"        \"ss_salud\"         \"ayuda_moverse\"    \"ayuda_thogar\"    \n[29] \"disc_fisica\"     \n```\n\n\n:::\n\n```{.r .cell-code}\ndim(proc_casen) # Dimensiones\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 202111     29\n```\n\n\n:::\n:::\n\n\nContamos con 29 variables (columnas) y 202.111 observaciones (filas).\n\n## Recordemos...\n\nEn estadística, la formulación de hipótesis que implica dos variables (o la comparación de grupos) busca determinar si las diferencias que se encuentran en la muestra son extrapolables a la población.\n\nAhora vamos a aprender a contrastar hipótesis sobre diferencias entre grupos. Si nuestra hipótesis plantea **solamente** que los **grupos son diferentes**, sin especificar cuál tendrá un promedio mayor, utilizamos una **prueba de dos colas** o **no direccional**.\n\n::: callout-note\n#### Diferencias de medias (o prueba de dos colas)\n\nContrastamos la *hipótesis nula* de *no* diferencias entre grupos: $$  H_{0}: \\mu_{1} - \\mu_{2} = 0 $$ En relación a una *hipótesis alternativa* sobre *diferencias* entre grupos: $$  H_{A}: \\mu_{1} - \\mu_{2} \\neq 0 $$\n:::\n\nAdemás, podemos **plantear hipótesis** respecto a que el valor de cierto parámetro para un grupo **puede ser mayor o menor** al de otro grupo. A esto se le conoce como **hipótesis de una cola** y lo veremos más adelante.\n\n\nVeamos ahora cómo aplicar todos estos conocimientos con ejercicios. Primero, para asegurar la reproducibilidad de los resultados, utilizamos `set.seed`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) # Fijar la semilla para reproducibilidad\n```\n:::\n\n\n## Ejercicio 1\n\nEstamos en un escenario donde la pregunta de investigación es: *¿Existen diferencias salariales entre hombres y mujeres en Chile?*\n\n::: callout-important\nPara diferencia de medias utilizaremos _**prueba t**_, la cual es una especie de extensión de la prueba Z para diferencia de medias, y que se asimila a Z con muestras mayores a 30. Por lo tanto, por el momento vamos a asumir que Z=t, y sus diferencias se verán en el próximo práctico\n:::\n\nPara contrastar esta hipótesis, vamos utilizar la base de datos `proc_casen`, seleccionaremos las variables `sexo` e `ytrabajocor` (ingresos) y haremos un subset de datos de 1.500 casos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncasen_subset <- proc_casen %>% \n  select(sexo, ytrabajocor) %>% # seleccionamos\n  sample_n(1500) # extraemos una muestra de 1500 casos\n\ncasen_subset <- na.omit(casen_subset) # eliminamos casos perdidos (listwise)\n```\n:::\n\n\n:::callout-tip\nEl símbolo `%>%` se llama pipe, y es una de las funciones más útiles de R. Su utilidad radica en que permite **encadenar operaciones**, es decir, lee el código como una secuencia de pasos en lugar de funciones aisladas, donde el resultado de un comando pasa a ser el primer argumento del siguiente comando, lo que permite ahorrar líneas de código\n:::\n\n\nGeneramos tabla para visualizar la distribución de los datos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncasen_subset %>% \n  dplyr::group_by(sexo) %>% # se agrupan por la variable categórica \n  dplyr::summarise(Obs. = n(), # columna para el N de cada categoría\n                   Promedio = mean(ytrabajocor, na.rm=TRUE),\n                   SD = sd(ytrabajocor, na.rm=TRUE)) %>% # se agregan las operaciones a presentar en la tabla\n  kableExtra::kable(format = \"markdown\") # se genera la tabla\n```\n\n::: {.cell-output-display}\n\n\n| sexo| Obs.| Promedio|       SD|\n|----:|----:|--------:|--------:|\n|    1|  379| 690724.8| 613238.9|\n|    2|  309| 585360.4| 567737.7|\n\n\n:::\n:::\n\n\nAhora vamos con los [5 pasos de la inferencia](https://correlacional.netlify.app/slides/05-inferencia4.html#33)\n\n**1. Formulación de hipótesis**\n\nEl primer aspecto a establecer es el tipo de hipótesis a formular: ¿Direccional o no direccional? En este caso, la pregunta **no** indica una **direccionalidad**, por lo tanto corresponde a una **hipótesis no direccional**. Si hubiera sido una pregunta que hiciera referencia a una mayoría de un grupo por sobre otro (\"¿Es el salario de los hombres mayor que el de las mujeres?\") correspondería a una hipótesis direccional.\n\nLa hipótesis general es que el salario de los hombres es **distinto** que el de las mujeres. Pasando a lenguaje de hipótesis, esto se plantea como:\n\n**Hipótesis alternativa**:\n\n$$H_{a}: \\bar{X}_{hombres} -  \\bar{X}_{mujeres} \\neq 0$$\n\n**Hipótesis nula**:\n\n$$H_{0}: \\bar{X}_{hombres} -  \\bar{X}_{mujeres}= 0$$\n\n**2. Obtención del error estándar y estadístico de prueba**\n\n::: callout-important\n\nLa fórmula para error estándar en diferencia de medias es:\n\n$$SE=\\sqrt{\\frac{\\sigma_{diff}}{n_a}+\\frac{\\sigma_{diff}}{n_b}}$$\n\n::: \n\nAhora aplicamos la fórmula con nuestros datos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedia_hombres <- mean(casen_subset$ytrabajocor[casen_subset$sexo == 1]) # media para hombres\nmedia_mujeres <- mean(casen_subset$ytrabajocor[casen_subset$sexo == 2]) # media para mujeres\n\nvar_hombres <- var(casen_subset$ytrabajocor[casen_subset$sexo == 1]) # varianza para hombres\nvar_mujeres <- var(casen_subset$ytrabajocor[casen_subset$sexo == 2]) # varianza para mujeres\n\nn_hombres <- length(casen_subset$ytrabajocor[casen_subset$sexo == 1]) # n para hombres\nn_mujeres <- length(casen_subset$ytrabajocor[casen_subset$sexo == 2]) # n para mujeres\n\n# aplicamos la fórmula de error estándar para diferencia de medias\nse_diff <- sqrt((var_hombres / n_hombres) + (var_mujeres / n_mujeres))\nse_diff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 45115.12\n```\n\n\n:::\n:::\n\n\n**3. Establecer probabilidad de error**\n\nRecordemos que, por convención, nuestra probabilidad de error es $a$ = 0.05\n\n**4. Intervalo de confianza**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiff_medias <- media_hombres - media_mujeres # diferencia de medias observada\n\nlim_inf <- diff_medias - 1.96 * se_diff # límite inferior del intervalo\nlim_sup <- diff_medias + 1.96 * se_diff # límite superior del intervalo\n\nlim_inf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16938.82\n```\n\n\n:::\n\n```{.r .cell-code}\nlim_sup\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 193790.1\n```\n\n\n:::\n:::\n\n\nEntonces nuestro intervalo de confianza quedaría de tal manera: $CI$[16939.82; 193790.1]\n\n\nAhora...\n\n**Pasos 2, 3 y 4 de una vez con R**\n\n-   Obtener error estándar y estadístico de prueba empírico correspondiente (ej: Z o t)\n\n-   Establecer la probabilidad de error $\\alpha$ (usualmente 0.05) y obtener valor crítico (teórico) de la prueba correspondiente\n\n-   Cálculo de intervalo de confianza / contraste valores empírico/crítico\n\nLuego de establecer las hipótesis nos vamos directamente al software, ya que R nos permite obtener de una vez toda la información de los pasos 2, 3 y 4.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_ej1 <- t.test(casen_subset$ytrabajocor ~ casen_subset$sexo, # define las variables que serán sometidas al test de hipótesis\n                   alternative = \"two.sided\", # define la hipótesis alternativa\n                   conf.level = 0.95) # establece el nivel de confianza\n\ntest_ej1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  casen_subset$ytrabajocor by casen_subset$sexo\nt = 2.3355, df = 674.99, p-value = 0.01981\nalternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0\n95 percent confidence interval:\n  16781.61 193947.32\nsample estimates:\nmean in group 1 mean in group 2 \n       690724.8        585360.4 \n```\n\n\n:::\n:::\n\n\nTambién podemos visualizarlo en una tabla más amable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstats.table <- tidy(test_ej1, conf_int = T) # se convierten los datos del test en un dataframe\nnice_table(stats.table, broom = \"t.test\") # convierte el dataframe en tabla\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-98345518{table-layout:auto;}.cl-982fba9e{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-982fbab2{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-982fbabc{font-family:'Times New Roman';font-size:7.2pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3.6pt;}.cl-98316a60{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-98316a74{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-98317b54{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-98317b72{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-98317b7c{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-98345518'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-98317b54\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">Method</span></p></th><th class=\"cl-98317b54\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">Alternative</span></p></th><th class=\"cl-98317b54\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">Mean 1</span></p></th><th class=\"cl-98317b54\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">Mean 2</span></p></th><th class=\"cl-98317b54\"><p class=\"cl-98316a60\"><span class=\"cl-982fbab2\">M</span><span class=\"cl-982fbabc\">1</span><span class=\"cl-982fba9e\"> - </span><span class=\"cl-982fbab2\">M</span><span class=\"cl-982fbabc\">2</span></p></th><th class=\"cl-98317b54\"><p class=\"cl-98316a60\"><span class=\"cl-982fbab2\">t</span></p></th><th class=\"cl-98317b54\"><p class=\"cl-98316a60\"><span class=\"cl-982fbab2\">df</span></p></th><th class=\"cl-98317b54\"><p class=\"cl-98316a60\"><span class=\"cl-982fbab2\">p</span></p></th><th class=\"cl-98317b54\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">95% CI</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-98317b72\"><p class=\"cl-98316a74\"><span class=\"cl-982fba9e\">Welch Two Sample t-test</span></p></td><td class=\"cl-98317b7c\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">two.sided</span></p></td><td class=\"cl-98317b7c\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">690,724.82</span></p></td><td class=\"cl-98317b7c\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">585,360.36</span></p></td><td class=\"cl-98317b7c\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">105,364.47</span></p></td><td class=\"cl-98317b7c\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">2.34</span></p></td><td class=\"cl-98317b7c\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">674.99</span></p></td><td class=\"cl-98317b7c\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">.020*</span></p></td><td class=\"cl-98317b7c\"><p class=\"cl-98316a60\"><span class=\"cl-982fba9e\">[16781.61, 193947.32]</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n::: callout-important\nLos intervalos de confianza calculados de manera manual difieren levemente de los estimados con `t.test`. Esto se debe a que `t.test` utiliza el valor crítico de la distribución *t*, el cual es 1.9635, mientras que en el cálculo manual utilizamos 1.96. En la próxima clase ahondaremos en este tema\n:::\n\nVisualicemos la distribución de esta prueba y su zona de rechazo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngginference::ggttest(test_ej1)\n```\n\n::: {.cell-output-display}\n![](02-practico_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\n\n**5. Interpretación**\n\nAntes de la interpretación, aclaremos algunos conceptos:\n\n- El valor $p$ es la **probabilidad** de observar un resultado (una diferencia de medias, un estadístico $t$) igual o más extremo que el obtenido en la muestra, **asumiendo que $H_0$ es verdadera**\n\n- Si $p < \\alpha$ → rechazamos $H_0$ (el resultado es \"estadísticamente significativo\": es poco probable observar algo así si $H_0$ fuera cierta)\n\n- Si $p \\geq \\alpha$ → no rechazamos $H_0$ (los datos son compatibles con la ausencia de efecto)\n\nAhora, pasemos a la interpretación:\n\nLa prueba t que evalúa la diferencia de medias entre el salario y el sexo sugiere que el efecto es positivo y estadísticamente signficativo (diferencia = 105.364,47, t = 2.34, p < .05). El valor **$p$** indica que **la probabilidad de observar una diferencia de esta magnitud, o mayor, bajo la suposición de $H_{0}$ es menor al 5%**. Por tanto, con un 95% de confianza, rechazamos la $H_{0}$ ya que existe **evidencia a favor** de nuestra $H_{A}$ respecto a que hay diferencias de salario entre hombres y mujeres.\n\n\n\n\n::: callout-important\nMientras más grande (en valor absoluto) sea $t$, más lejos está el resultado observado de lo que $H_0$ predice, y por lo tanto más pequeño es el valor $p$ asociado\n:::\n\n## Ejercicio autónomo\n\nTomando como ejemplo el trabajo de la ganadora del Premio Nobel de Economía 2023 Claudia Goldin, en este siguiente ejercicio evaluaremos la siguiente pregunta: _¿Es el salario de las mujeres con hijos distinto al salario de las mujeres sin hijos?_ Por ende, usaremos **prueba $t$** para diferencia de medias.\n\nSiga las siguientes instrucciones:\n\n- Utilice la base de datos `proc_casen`, seleccionando las variables `ocupado`, `sexo`, `ytrabajocor` e `hijo`\n\n- Filtre por `ocupado == 1` y `sexo == 2` para quedarnos sólo con mujeres ocupadas\n\n- Genere una muestra aleatoria de 1.500 casos con la función `sample_n()` y elimine los casos pérdidos con `na.omit()`\n\n- Genere una tabla de descriptivos presentando la cantidad de casos, la media y la desviación estándar.\n\n- Aplique los 5 pasos para la inferencia mediante el uso de software\n\n- Interprete los resultados\n\n# Repaso\n\nHoy vimos:\n\n- Repaso de los intervalos de confianza, observando la importancia del error estándar y la estimación de rangos para encontrar el parámetro poblacional\n\n- Contraste de hipótesis mediante pruebas de diferencias de medias\n\n- Aplicar los 5 pasos para la inferencia mediante software\n\nPara cerrar...\n\n![](https://correlacional.netlify.app/slides/img/rechazar_meme.png)\n\n::: callout-important\nNuestro objetivo no es rechazar $H_{0}$ a toda costa, sino evaluar si los datos entregan evidencia suficiente para rechazarla. Un resultado en que no rechazamos $H_{0}$ también es un resultado estadístico válido\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}