{
  "hash": "d50517df4e1123f60ca0a321ce268486",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Reporte Evaluación 1\"\ndate: 09-21-2026\ncategories: [info, mail-UCursos]\nlang: es\nwebsite:\n  comments:\n    giscus:\n      repo: cursos-metodos-facso/correlacional\neditor_options: \n  chunk_output_type: console\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Ver código\"\n---\n\n\n\nEste reporte realiza un análisis de la Evaluación 1 sobre la Unidad 1: Inferencia estadística\n\n# Pauta y recorrecciones\n\nLa pauta de evaluación se puede revisar [aquí](/news/documents/prueba1-2026-PAUTAS.pdf)\n\n## Solicitudes de recorrección\n\n- Enviar correo a apoyo docente [Gabriel Cortés, gabriel.cortes@uchile.cl](mailto: gabriel.cortes@uchile.cl), quien estará coordinando estas solicitudes\n- En el correo:\n  - mencionar pregunta a corregir\n  - argumento y puntaje esperado\n  - foto de la pregunta\n\nSolicitudes hasta el Jueves 1 de Octubre 23:59, las solicitudes se responderán en un plazo máximo el miércoles 7 de Octubre.\n\n# Librerías, datos y ajustes \n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, sjmisc, sjPlot, kableExtra, sjlabelled, readxl, janitor, here)\n```\n:::\n\n\n## Generación de la base de datos\n\nSe unen (por RUT) los puntajes por pregunta y la nota (columna \"Nota + bonus\") con la asistencia descargada desde U-Cursos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrut_lista <- read_excel(here(\"news/data/notas.xls\")) %>%\n  clean_names() %>%\n  pull(rut)\n\nasistencia <- read_excel(here(\"news/data/asistencia.xls\"), .name_repair = \"minimal\")\nasistencia <- asistencia[, 1:4] %>%\n  set_names(c(\"n\", \"persona\", \"rut\", \"asistencia\")) %>%\n  mutate(asistencia = parse_number(asistencia)) %>%  # \"67%\" -> 67\n  select(rut, asistencia)\n\npuntajes <- read_excel(here(\"news/data/Puntajes prueba 1.xlsx\"), .name_repair = \"minimal\")\nnames(puntajes) <- c(\"n\", \"persona\", \"rut\", \"corrector\", \"forma\", \"p1a\", \"p1b\", \"p1c\",\n                     \"p2a\", \"p2b\", \"p2c\", \"p2d\", \"bonus\", \"puntaje\", \"nota_puntajes\", \"nota_bonus\")\npuntajes <- puntajes %>%\n  mutate(across(c(p1a:puntaje), ~ as.numeric(str_replace(as.character(.x), \",\", \".\"))),  # p1c trae comas decimales\n         forma = if_else(forma %in% c(\"A\", \"B\"), forma, NA_character_)) %>%\n  # se adaptan las preguntas 2 de la forma B a la forma A: 2aB = 2bA, 2bB = 2cA, 2cB = 2dA, 2dB = 2aA\n  mutate(p2a_b = p2a, p2b_b = p2b, p2c_b = p2c, p2d_b = p2d,\n         p2a = if_else(forma == \"B\", p2d_b, p2a),\n         p2b = if_else(forma == \"B\", p2a_b, p2b),\n         p2c = if_else(forma == \"B\", p2b_b, p2c),\n         p2d = if_else(forma == \"B\", p2c_b, p2d)) %>%\n  select(-ends_with(\"_b\")) %>%\n  # quienes no rindieron tienen todo vacío (puntaje 0 / nota 1 solo por defecto)\n  mutate(across(c(p1a:puntaje), ~ if_else(is.na(p1a), NA_real_, .x))) %>%\n  select(rut, persona, corrector, forma, p1a:p2d, bonus, puntaje, nota = nota_bonus) %>%  # nota = nota + bonus\n  mutate(nota = floor(nota * 10 + 0.5 + 1e-9) / 10)  # redondeo a 1 decimal (mitad hacia arriba), como U-Cursos\n\nprueba1 <- puntajes %>%\n  left_join(asistencia, by = \"rut\")\n\nstopifnot(nrow(prueba1) == length(rut_lista), !anyDuplicated(prueba1$rut))\n```\n:::\n\n\nUn caso (corrector JC) trae en `forma` el valor \"2.0\" (error de digitación); queda como forma perdida.\n\n## Etiquetados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprueba1 <- prueba1 %>%\n  set_label(c(persona = \"Estudiante\", corrector = \"Corrector/a\", forma = \"Forma de la prueba\",\n              p1a = \"1a: Hipótesis\", p1b = \"1b: Valor t\", p1c = \"1c: Intervalo\",\n              p2a = \"2a: 2 muestras\", p2b = \"2b: Intervalos\", p2c = \"2c: Alfa y p\", p2d = \"2d: Hijos\",\n              bonus = \"Bonus\", puntaje = \"Puntaje total (con bonus)\",\n              nota = \"Nota final\", asistencia = \"Asistencia (%)\")[names(.)])\n```\n:::\n\n\nSin nota (no rindieron la prueba): 21. Sin registro de asistencia: 2.\n\n# Descriptivos\n\n## Tabla descriptiva\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprueba1 %>% select(p1a:p2d, bonus, puntaje, nota, asistencia) %>% descr(show = c(\"label\",\"range\", \"mean\", \"sd\", \"n\")) %>% kable(.,\"markdown\", digits=2)\n```\n\n::: {.cell-output-display}\n\n\n|   |var        |label                     |   n|  mean|    sd|range         |\n|:--|:----------|:-------------------------|---:|-----:|-----:|:-------------|\n|4  |p1a        |1a: Hipótesis             |  87|  1.16|  0.90|3 (0-3)       |\n|5  |p1b        |1b: Valor t               |  87|  2.43|  1.38|4 (0-4)       |\n|6  |p1c        |1c: Intervalo             |  87|  0.68|  0.70|2 (0-2)       |\n|7  |p2a        |2a: 2 muestras            |  87|  0.21|  0.41|1 (0-1)       |\n|8  |p2b        |2b: Intervalos            |  87|  0.54|  0.50|1 (0-1)       |\n|9  |p2c        |2c: Alfa y p              |  87|  0.32|  0.47|1 (0-1)       |\n|10 |p2d        |2d: Hijos                 |  87|  0.34|  0.48|1 (0-1)       |\n|2  |bonus      |Bonus                     |  87|  0.31|  0.23|0.5 (0-0.5)   |\n|11 |puntaje    |Puntaje total (con bonus) |  87|  5.99|  2.82|11.5 (0-11.5) |\n|3  |nota       |Nota final                |  87|  4.16|  1.46|6 (1-7)       |\n|1  |asistencia |Asistencia (%)            | 106| 74.63| 20.65|75 (25-100)   |\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Ajuste entre formas\n\n- **Pregunta 2:** las preguntas 2 de la forma B se adaptaron a la forma A, según esta equivalencia: 2a B = 2b A, 2b B = 2c A, 2c B = 2d A y 2d B = 2a A. Las etiquetas de la tabla corresponden a la forma A.\n- **Pregunta 1:** en la forma A se refiere a una hipótesis **no direccional**; en la forma B, a una hipótesis **direccional**.\n:::\n\n## Gráficos descriptivos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_frq(data = prueba1$nota, type = \"hist\", show.mean = T)\n```\n\n::: {.cell-output-display}\n![](2026-09-21_reporte-notas1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprueba1 %>%\n  filter(!is.na(nota)) %>%\n  mutate(notas_cat = cut(nota, breaks = c(-Inf, 3.95, 4.95, 5.95, Inf),\n                         labels = c(\"Menor a 4.0\", \"4.0-4.9\", \"5.0-5.9\", \"6.0-7.0\"))) %>%\n  count(notas_cat) %>%\n  mutate(pct = n / sum(n)) %>%\n  ggplot(aes(x = n, y = fct_rev(notas_cat))) +\n  geom_col(fill = \"steelblue\") +\n  geom_text(aes(label = paste0(n, \" (\", round(pct * 100, 1), \"%)\")), hjust = -0.1, size = 6) +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.35))) +\n  labs(title = \"Rangos de notas en Evaluación 1\", x = \"Estudiantes\", y = NULL) +\n  theme_minimal(base_size = 16) +\n  theme(plot.title = element_text(face = \"bold\", hjust = 0.5),\n        axis.text.y = element_text(size = 18),\n        axis.text.x = element_text(size = 14),\n        axis.title = element_text(size = 16))\n```\n\n::: {.cell-output-display}\n![](2026-09-21_reporte-notas1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n# Asociación entre asistencia y nota\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- cor(prueba1$asistencia, prueba1$nota, use = \"complete.obs\")\n\nggplot(prueba1, aes(x = asistencia, y = nota)) + \n  geom_jitter(width = 0.2, color = \"red\", size = 4) + \n  labs(title = paste0(\"Relación entre asistencia y notas en Evaluación 1 (r=\", round(r, 2), \")\"),\n       x = \"Asistencia (%)\", y = \"Nota\") + \n  theme(axis.title = element_text(size = 12),\n        axis.text = element_text(size = 12),\n        aspect.ratio = 1/1.5,\n        plot.title = element_text(size = 12, face = \"bold\", hjust = 0.5)) +\n  scale_x_continuous(breaks = seq(0, 100, by = 10), limits = c(0, 100)) +\n  scale_y_continuous(breaks = 1:7, limits = c(1, 7)) +\n  geom_vline(xintercept = 50, linetype = \"dashed\") +\n  geom_hline(yintercept = 4, linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](2026-09-21_reporte-notas1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n## Cuadrantes según nota (4.0) y asistencia (50%)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncuadrantes <- prueba1 %>%\n  filter(!is.na(nota), !is.na(asistencia)) %>%\n  mutate(cuadrante = case_when(\n    asistencia >= 50 & nota >= 4 ~ \"Asistencia alta y nota ≥ 4.0\",\n    asistencia >= 50 & nota <  4 ~ \"Asistencia alta y nota < 4.0\",\n    asistencia <  50 & nota >= 4 ~ \"Asistencia baja y nota ≥ 4.0\",\n    asistencia <  50 & nota <  4 ~ \"Asistencia baja y nota < 4.0\")) %>%\n  group_by(cuadrante) %>%\n  summarise(n = n(), nota_media = mean(nota)) %>%\n  mutate(pct = n / sum(n) * 100)\n\ncuadrantes %>%\n  transmute(Cuadrante = cuadrante, N = n, `% estudiantes` = pct, `Nota promedio` = nota_media) %>%\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|Cuadrante                    |  N| % estudiantes| Nota promedio|\n|:----------------------------|--:|-------------:|-------------:|\n|Asistencia alta y nota < 4.0 | 35|          40.7|           2.9|\n|Asistencia alta y nota ≥ 4.0 | 45|          52.3|           5.3|\n|Asistencia baja y nota < 4.0 |  5|           5.8|           2.2|\n|Asistencia baja y nota ≥ 4.0 |  1|           1.2|           4.0|\n\n\n:::\n\n```{.r .cell-code}\nq <- function(x) filter(cuadrantes, cuadrante == x)\n```\n:::\n\n\nConsiderando a los 86 estudiantes con nota y asistencia, y usando como puntos de corte la nota 4.0 y el 50% de asistencia:\n\n- 52.3% (n = 45) tiene asistencia igual o superior a 50% y nota igual o superior a 4.0; su nota promedio es 5.33.\n- 40.7% (n = 35) tiene asistencia igual o superior a 50% y nota inferior a 4.0; su nota promedio es 2.93.\n- 1.2% (n = 1) tiene asistencia inferior a 50% y nota igual o superior a 4.0; su nota promedio es 4.\n- 5.8% (n = 5) tiene asistencia inferior a 50% y nota inferior a 4.0; su nota promedio es 2.16.\n\n# Preguntas y asociaciones\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_corr(select(prueba1, p1a:p2d, puntaje, nota, asistencia),\n         triangle = \"lower\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">&nbsp;</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">1a: Hipótesis</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">1b: Valor t</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">1c: Intervalo</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">2a: 2 muestras</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">2b: Intervalos</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">2c: Alfa y p</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">2d: Hijos</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">Puntaje total (con bonus)</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">Nota final</th>\n<th style=\"font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;\">Asistencia (%)</th>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">1a: Hipótesis</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">1b: Valor t</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.251<span style=\"vertical-align:super;font-size:0.8em;\">*</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">1c: Intervalo</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.314<span style=\"vertical-align:super;font-size:0.8em;\">**</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.561<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">2a: 2 muestras</td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.104<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.244<span style=\"vertical-align:super;font-size:0.8em;\">*</span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.166<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">2b: Intervalos</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.335<span style=\"vertical-align:super;font-size:0.8em;\">**</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.218<span style=\"vertical-align:super;font-size:0.8em;\">*</span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.182<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.276<span style=\"vertical-align:super;font-size:0.8em;\">*</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">2c: Alfa y p</td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">-0.146<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">-0.250<span style=\"vertical-align:super;font-size:0.8em;\">*</span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">-0.138<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.154<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.184<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">2d: Hijos</td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.095<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.141<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.065<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.140<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.353<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.187<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">Puntaje total (con bonus)</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.597<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.769<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.673<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.446<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.567<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.067<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.402<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">Nota final</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.596<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.758<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.673<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.440<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.558<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.079<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.390<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.997<span style=\"vertical-align:super;font-size:0.8em;\">***</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"font-style:italic;\">Asistencia (%)</td>\n<td style=\"padding:0.2cm; text-align:center;\">0.329<span style=\"vertical-align:super;font-size:0.8em;\">**</span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">-0.024<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.125<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.029<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.262<span style=\"vertical-align:super;font-size:0.8em;\">*</span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.059<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">-0.014<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center; color:#999999;\">0.209<span style=\"vertical-align:super;font-size:0.8em;\"></span></td>\n<td style=\"padding:0.2cm; text-align:center;\">0.224<span style=\"vertical-align:super;font-size:0.8em;\">*</span></td>\n<td style=\"padding:0.2cm; text-align:center;\">&nbsp;</td>\n</tr>\n<tr>\n<td colspan=\"11\" style=\"border-bottom:double black; border-top:1px solid black; font-style:italic; font-size:0.9em; text-align:right;\">Computed correlation used pearson-method with listwise-deletion.</td>\n</tr>\n \n</table>\n`````\n:::\n:::\n\n\n**Consistencia interna**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(psych)\n\npreguntas <- prueba1 %>% select(p1a:p2d)\npsych::alpha(preguntas)$total$raw_alpha\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSome items ( p2c ) were negatively correlated with the first principal component and \nprobably should be reversed.  \nTo do this, run the function again with the 'check.keys=TRUE' option\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5402977\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "2026-09-21_reporte-notas1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}