{
  "hash": "80da58316c21f735ff453b0d7b26a698",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\nformat:\n  revealjs:\n    incremental: true\n    scrollable: true\n    logo: img/logo-correlacional-transp.png\n    theme: [css/custom_2025.scss]\n    title-slide-attributes:\n      visibility: false\n    transition: none\n    transition-speed: slow\n    auto-play-media: true\n    title-slide-logo: false\n    slide-number: true\neditor: source\n---\n\n\n\n\n::: {.cell}\n\n:::\n\n\n# {.hide-logo data-background-color=\"#0C3547\"}\n\n<br>\n\n::::: columns\n::: {.column width=\"30%\"}\n\n<br>\n\n![](img/logo-correlacional-transp.png){width=\"100%\" fig-align=\"right\"}\n:::\n\n:::{.column width=\"2%\"}\n\n:::\n\n::: {.column style=\"width: 65%; font-size: 25px; text-align: right; margin: 0 auto;\"}\n\n<br>\n\n### [Estadística Correlacional]{style=\"font-size: 2em; color: white;\"}\n\n::: {style=\"border-top: 1px solid white; margin: 0.3em 0;\"}\n:::\n\n[Inferencia, asociación, y reporte]{style=\"font-size: 1.5em; color: #dfc117;\"}\n\n[Juan Carlos Castillo]{style=\"font-size: 1em; color: white;\"}\\\n[Sociología FACSO - UChile]{style=\"font-size: 1em; color: white;\"}\\\n[2do Sem 2026]{style=\"font-size: 1em; color: white;\"}\n\n[correlacional.metodos-facso.org](https://correlacional.metodos-facso.org)\n\n<br>\n[**Inferencia 4**:]{style=\"color: white; font-size: 1.3em;\"}\n\n[Test de hipótesis]{style=\"color: #dfc117;\"}\n\n:::\n:::::\n\n# [¿Qué hemos visto hasta ahora?]{style=\"color: #dfc117;\"} {data-background-color=\"#0C3547\"}\n\n##\n\n![](img/temas-inferencias.png){width=\"100%\" fig-align=\"center\"}\n\n## ¿Qué puedo decir de la población a partir de mi muestra? {style=\"font-size: 0.8em;\"}\n\nPROBABILIDADES ... de un rango de valores\n\n:::: {.columns}\n::: {.column width=\"70%\"}\n\n### ¿Cómo llego al rango de valores probables de un parámetro poblacional obtenido a partir de **una muestra**?\n\n:::\n\n::: {.column width=\"30%\"}\n\n![](img/inference1.png){width=\"80%\" fig-align=\"center\"}\n\n:::\n::::\n\n## Probabilidades {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"45%\"}\n\n- Podemos calcular probabilidades basados en una distribución teórica de ocurrencia de eventos.\n\n- Ej: En teoría, la probabilidad de que salga sello al tirar una moneda es 50%\n\n- Mientras más repetimos el evento, más se van a acercar los resultados (distribución empírica) a la probabilidad del evento (distribución teórica)\n\n:::\n\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-inferencia4_files/figure-revealjs/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n:::\n::::\n\n## Curva normal {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n- Hay una serie de eventos que en términos teóricos y empíricos tienen una distribución particular en torno al valor central -> **normal**\n\n- La [curva normal]{style=\"color: #c0392b;\"} es una distribución teórica que nos permite tener un estándar con el cual comparar distribuciones empíricas\n\n:::\n\n::: {.column width=\"50%\"}\n\n<br>\n\n![](img/norm2.png){width=\"100%\" fig-align=\"center\"}\n\n:::\n::::\n\n## Teorema central del límite y error estándar {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"55%\"}\n\n- si pudiera calcular un estadístico en muchas muestras distintas (ej: promedio) este se distribuiría de manera normal\n\n- el **error estándar** es la formula que nos permite obtener el valor de la desviación estándar de los promedios con una sola muestra\n\n:::\n\n::: {.column width=\"45%\"}\n\n<br>\n\n$$\\sigma_{\\bar{X}}=\\frac{s}{\\sqrt{N}}$$\n\n:::\n::::\n\n## Puntajes Z {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n- el puntaje Z es una medida de distancias del promedio en una distribución normal, que tiene promedio 0 y desviación estándar 1\n\n- Z expresa cualquier puntaje en desviaciones estándar desde el promedio (de la curva normal)\n\n- Z permite además obtener el valor del percentil de cada puntaje\n\n:::\n\n::: {.column width=\"50%\"}\n\n$$z=\\frac{x-\\mu}{\\sigma}$$\n\n![](https://correlacional.netlify.app/slides/03-inferencia2_files/figure-html/unnamed-chunk-16-1.png){width=\"90%\" fig-align=\"center\"}\n\n:::\n::::\n\n## Intervalos de confianza [para el promedio] {style=\"font-size: 0.75em;\"}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n- rango de probabilidad del valor de un parámetro en la población\n\n- Para construirlo, 4 pasos:\n\n  1- establecer **nivel de confianza** (convencionalmente 95%)\n\n  2- definir **puntaje Z** correspondiente a este intervalo (para 95% es 1.96)\n\n:::\n\n::: {.column .fragment width=\"50%\"}\n\n3- multiplicar Z por el **error estándar**\n\n4- restar al promedio (límite inferior) y sumar (límite superior)\n\n$$\\bar{X}\\pm Z*\\frac{\\sigma}{\\sqrt{N}}$$\n\n:::\n::::\n\n## {data-background-color=\"#0C3547\"}\n\n![](img/herramientas.png){width=\"90%\" fig-align=\"center\"}\n\n# [¿Qué es una hipótesis?]{style=\"color: white;\"} {data-background-color=\"#0C3547\"}\n\n::: {.fragment}\n### [¿Cuándo una hipótesis es [verdadera]{style=\"color: #dfc117;\"}?]{style=\"color: white;\"}\n:::\n\n## [Una [hipótesis]{style=\"color: #dfc117;\"} es una aseveración o una predicción que se desprende de una teoría sobre una situación que ocurre en la población en estudio]{style=\"color: white;\"} {data-background-color=\"#9B2626\"}\n\n# [¿Cuándo se puede verificar una hipótesis?]{style=\"color: white;\"} {data-background-color=\"#0C3547\"}\n\n::: {.fragment}\n### [-> [NUNCA]{style=\"color: #dfc117;\"}]{style=\"color: white;\"}\n:::\n\n::: {.fragment}\n### [... pero, se puede **[falsar]{style=\"color: #e8871a;\"}**]{style=\"color: white;\"}\n:::\n\n## Popper y la falsabilidad {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"40%\"}\n\n![](img/popper.jpg){width=\"80%\" fig-align=\"center\"}\n\n:::\n\n::: {.column width=\"60%\"}\n\n_\"el criterio de demarcación que hemos de adoptar no es el de la verificabilidad, sino el de la [falsabilidad]{style=\"color: #c0392b;\"} de los sistemas. Dicho de otro modo: no exigiré que un sistema científico pueda ser seleccionado, de una vez para siempre, en un sentido positivo; pero sí que sea susceptible de selección en un sentido negativo por medio de contrastes o pruebas empíricas: ha de ser posible refutar por la experiencia un sistema científico empírico\" (Popper, 1982, p. 40)_\n\n:::\n::::\n\n## Contraste de hipótesis y falsación {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"35%\"}\n\n![](img/hipotesis.png){width=\"100%\" fig-align=\"center\"}\n\n:::\n\n::: {.column width=\"65%\"}\n\n- El **verificar** una hipótesis no hace que una teoría sea verdadera\n\n- Se puede intentar refutar una teoría (**falsarla**) mediante un contraejemplo o hipótesis contraria\n\n- Si no es posible refutar la hipótesis contraria, entonces la teoría queda aceptada **provisionalmente**\n\n:::\n::::\n\n## Ejemplo\n\n:::: {.columns}\n::: {.column width=\"60%\"}\n\nTeoría: todos los cuervos son negros\n\nHipótesis de verificación: hay cuervos negros\n\nHipótesis de falsación: hay cuervos blancos\n\n:::\n\n::: {.column width=\"40%\"}\n\n<br>\n\n![](img/white-crow.png){width=\"90%\" fig-align=\"center\"}\n\n:::\n::::\n\n## [Lógica de contraste de hipótesis]{style=\"color: white;\"} {data-background-color=\"#0C3547\"}\n\n::: {style=\"color: white;\"}\n### [Intentar falsar lo que es contrario a nuestra hipótesis original]{style=\"color: #dfc117;\"}\n\n::: {.fragment}\n### En estadística, esta \"hipótesis contraria\" se denomina la [HIPÓTESIS NULA]{style=\"color: #dfc117;\"}\n:::\n:::\n\n## [buscamos RECHAZAR LA HIPÓTESIS NULA]{style=\"color: white;\"} {data-background-color=\"#9B2626\"}\n\n::: {style=\"color: white; font-size: 0.8em;\"}\nsi logramos rechazar la hipótesis nula (o sea, que lo contrario de nuestra teoría no es verdad), entonces encontramos evidencia a favor de nuestra teoría\n\nBuscamos **no encontrar** cuervos blancos ![](img/white-crow.png){width=\"10%\"}\n:::\n\n## Hipótesis nula\n\n- Hipótesis se denota con la letra $H$\n\n- La hipótesis nula se denota $H_0$ (hache cero)\n\n- **Cero** porque en general se refiere a que lo que señala la teoría no existe o **es cero en la población**\n\n-> más detalle de tipos de hipótesis prox. clase, ahora vamos a un **ejemplo**\n\n## [¿Existen diferencias salariales entre hombres y mujeres en Chile?]{style=\"color: white;\"} {data-background-color=\"#0C3547\"}\n\n::: {style=\"color: white; font-size: 0.7em;\"}\n| Hipótesis general | Hipótesis estadística |\n|-------------------------------|-------------------------------|\n| Existen diferencias salariales entre hombres y mujeres | Hipótesis **alternativa**: Las diferencias son distintas de cero |\n| No existen diferencias salariales entre hombres y mujeres | Hipótesis **nula**: Las diferencias no son distintas de cero |\n:::\n\n## Cuestionario CASEN\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n![](img/sueldo_casen.png){width=\"85%\" fig-align=\"center\"}\n\n:::\n\n::: {.column width=\"50%\"}\n\n![](img/sexo_casen.png){width=\"100%\" fig-align=\"center\"}\n\n:::\n::::\n\n## Datos CASEN 2022 {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"35%\"}\n\n![](img/casen_download.png){width=\"100%\" fig-align=\"center\"}\n\n:::\n\n::: {.column width=\"65%\"}\n\nVamos a generar una submuestra de 350 casos de CASEN para ilustrar de mejor manera el sentido del test de hipótesis\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sjmisc, haven, dplyr, stargazer, interpretCI, kableExtra)\nload(\"casen2022_inf2.Rdata\")\noptions(scipen = 999) # para evitar notación en los ceros\nset.seed(20) # para fijar el resultado aleatorio\ncasen_350 <- casen2022_inf %>% select(salario, sexo) %>% sample_n(350)\ncasen_350 <- na.omit(casen_350)\n```\n:::\n\n\n:::\n::::\n\n## Datos {style=\"font-size: 0.7em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstargazer(as.data.frame(casen_350), type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n======================================================\nStatistic  N     Mean      St. Dev.    Min      Max   \n------------------------------------------------------\nsalario   343 634,402.300 459,180.200 30,000 2,900,000\nsexo      343    1.402       0.491      1        2    \n------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n## {style=\"font-size: 0.7em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncasen_350 %>% # se especifica la base de datos\n  dplyr::group_by(sexo = sjlabelled::as_label(sexo)) %>% # se agrupan por la variable categórica y se usan sus etiquetas con as_label\n  dplyr::summarise(Obs. = n(), Promedio = mean(salario, na.rm = TRUE), SD = sd(salario, na.rm = TRUE)) %>% # se agregan las operaciones a presentar en la tabla\n  kable(format = \"markdown\") # se genera la tabla\n```\n\n::: {.cell-output-display}\n\n\n|sexo      | Obs.| Promedio|       SD|\n|:---------|----:|--------:|--------:|\n|1. Hombre |  205| 654585.4| 468692.5|\n|2. Mujer  |  138| 604420.3| 444666.0|\n\n\n:::\n:::\n\n\nDiferencia salarial = 654.585-604.420=**50.165**\n\n## [[Procedimiento: 5 pasos de la inferencia]{style=\"color: #dfc117;\"} (ajustados de Ritchey)]{style=\"color: white;\"} {data-background-color=\"#0C3547\" style=\"font-size: 0.8em;\"}\n\n::: {style=\"color: white;\"}\n1. Formular hipótesis ( $H_0$ y $H_A$)\n\n2. Obtener error estándar y estadístico de prueba empírico correspondiente (ej: Z o t)\n\n3. Establecer la probabilidad de error $\\alpha$ (usualmente 0.05) y obtener valor crítico (teórico) de la prueba correspondiente\n\n4. Cálculo de intervalo de confianza / contraste valores empírico/crítico\n\n5. Interpretación\n:::\n\n## 1. Formular hipótesis\n\nContrastamos la *hipótesis nula* (no hay diferencias de promedios entre grupos):\n\n$$H_{0}: \\bar{X}_{hombres} -  \\bar{X}_{mujeres}= 0$$\n\nEn referencia a la siguiente hipótesis alternativa:\n\n$$H_{a}: \\bar{X}_{hombres} -  \\bar{X}_{mujeres} \\neq 0$$\n\n## {style=\"font-size: 0.8em;\"}\n\n::: {.content-box-green}\n### (2. Error estándar y estadístico de prueba)\n\n- [(Una nota preliminar)]{style=\"color: #ffe08a;\"} En general, existen 2 formas de realizar el contraste de hipótesis:\n\n  - intervalo de confianza, asociado al error estándar\n\n  - contraste con valor crítico, asociado al estadístico de prueba\n\n- Ambos entregan información consistente y complementaria\n\n- En esta clase vamos a estimar solo el intervalo, la próxima veremos el contraste con valor crítico, que el caso de diferencia de medias corresponde a la prueba $t$ de student.\n:::\n\n## 2. Error estándar (y estadístico de prueba) {style=\"font-size: 0.75em;\"}\n\n- Cada estadístico tiene su propia fórmula de error estándar\n\n- En el caso de la **diferencia de medias** (en este caso, de hombres y mujeres), el error estándar es:\n\n$$SE=\\sqrt{\\frac{\\sigma_{diff}}{n_a}+\\frac{\\sigma_{diff}}{n_b}}$$\n\nDonde\n\n$$\\sigma_{diff}=\\frac{\\sigma^2_{a}(n_a-1)+\\sigma^2_{b}(n_b-1)}{n_a+n_b-2}$$\n\n- como se puede apreciar, es una extensión del error estándar del promedio pero para dos grupos distintos\n\n## {style=\"font-size: 0.9em;\"}\n\nCálculo de la desviación estándar de las diferencias de promedios:\n\n$$\n\\begin{align*}\n\\sigma_{diff}&=\\frac{468692^2(205-1)+444666^2(138-1)}{205+138-2} \\\\ \\\\\n&=\\frac{44813126936256+27088715663172}{341}\\\\ \\\\\n&=210855843400\n\\end{align*}\n$$\n\n## {style=\"font-size: 0.9em;\"}\n\nY entonces el error estándar de la diferencia de medias:\n\n$$\n\\begin{align*}\nSE&=\\sqrt{\\frac{\\sigma_{diff}}{n_a}+\\frac{\\sigma_{diff}}{n_b}} \\\\ \\\\\n&=\\sqrt{\\frac{210855843400}{205}+\\frac{210855843400}{138}}\\\\ \\\\\n&=50561\n\\end{align*}\n$$\n\n## 3. Establecer probabilidad de error {style=\"font-size: 0.85em;\"}\n\n- asumimos que existe una probabilidad de error al rechazar $H_0$, para lo cual fijamos un límite convencional -> usualmente un 5%\n\n- ¿error **de qué**? -> de rechazar $H_0$ cuando esta existe en la población.\n\n- Esto se conoce como la **probabilidad de error Tipo I o $\\alpha$ (alfa)**\n\n## Hipótesis nula ( $H_0$) y tipos de error {style=\"font-size: 0.8em;\"}\n\n![](img/errortypes.png){width=\"100%\" fig-align=\"center\"}\n\n## En nuestro ejemplo: {style=\"font-size: 0.8em;\"}\n\n$$H_{0}: \\bar{X}_{sueldo\\ mujeres} -  \\bar{X}_{sueldo\\ hombres}= 0$$\n\n- Si **hay** diferencias de sueldo en la población y rechazamos $H_0$: decisión correcta\n\n- Si **no hay** diferencias de sueldo en la población y rechazamos $H_0$: Error tipo I\n\n::: {.fragment}\n::: {.content-box-red style=\"text-align: center;\"}\n### El Error Tipo I equivale a encontrar cosas en nuestra muestra que no existen en la población\n:::\n:::\n\n## Hipótesis nula y tipos de error\n\n![](img/errors.jpg){width=\"70%\" fig-align=\"center\"}\n\n## Hipótesis nula y tipos de error\n\n<br>\n\n:::: {.columns}\n::: {.column width=\"48%\"}\n\n::: {.content-box-red}\n### Error Tipo I\n\nEncontrar algo que no existe en la población\n:::\n\n:::\n\n::: {.column width=\"48%\"}\n\n::: {.content-box-green}\n### Error Tipo II\n\nNo encontrar algo que si existe en la población\n:::\n\n:::\n::::\n\n## Hipótesis nula y $\\alpha$ {style=\"font-size: 0.85em;\"}\n\n- Entonces, el $\\alpha$ es la probabilidad de error que fijamos para rechazar la hipótesis nula\n\n- en lenguaje de prueba de hipótesis, es la probabilidad de rechazar la hipótesis nula cuando esta es verdadera\n\n- o la probabilidad de encontrar diferencias entre grupos de la población cuando estas no existen\n\n- o en simple, la probabilidad de que nos estemos equivocando\n\n## Nivel de confianza y probabilidad de error $\\alpha$ {style=\"font-size: 0.8em;\"}\n\n- el nivel de confianza de una estimación se determina de manera **convencional**, usualmente se acepta 95% o 99% de confianza\n\n- un nivel de confianza se expresa en una probabilidad de error $\\alpha$ ([alfa]{style=\"color: #c0392b;\"}), que es 1 - nivel de confianza\n\n  - para un nivel de confianza de 95%, $\\alpha=1-0.95=0.05$\n\n  - para un nivel de confianza de 99%, $\\alpha=1-0.99=0.01$\n\n##\n\n![](img/normal&alfa2.png){width=\"90%\" fig-align=\"center\"}\n\n##\n\n![](img/normal&alfa.png){width=\"90%\" fig-align=\"center\"}\n\n## {style=\"font-size: 0.8em;\"}\n\n::: {.content-box-green}\n### 4. Intervalo de confianza [y contraste con valor crítico]\n\n- de la clase anterior con prueba Z sabemos que el valor crítico para un 95% de confianza es 1.96\n\n- para diferencia de medias se utiliza prueba $t$, donde el valor crítico es variable según en tamaño muestral\n\n- sin embargo, para muestras grandes, t=Z, y por lo tanto por ahora mantendremos los valores referenciales Z (de 1.96) hasta que profundicemos en t la próxima clase\n:::\n\n## 4. Intervalo de confianza\n\n$$\n\\begin{align*}\n\\bar{x}_1-\\bar{x}_2 &\\pm t_{\\alpha/2}*SE_{\\bar{x_1}-\\bar{x_2}} \\\\\\\\\n50165 &\\pm 1.96*50561 \\\\\\\\\n50165 &\\pm 99099.56 \\\\\\\\\nCI[-49287.48&;149617.63]\n\\end{align*}\n$$\n\n## Test de hipótesis de diferencias en R {style=\"font-size: 0.75em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(salario ~ sexo, data = casen_350, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  salario by sexo\nt = 0.99215, df = 341, p-value = 0.3218\nalternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0\n95 percent confidence interval:\n -49287.48 149617.63\nsample estimates:\nmean in group 1 mean in group 2 \n       654585.4        604420.3 \n```\n\n\n:::\n:::\n\n\n## tabla t test con `rempsyc` {style=\"font-size: 0.75em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(rempsyc, broom)\nmodel <- t.test(salario ~ sexo, data = casen_350, var.equal = TRUE)\nstats.table <- tidy(model, conf.int = TRUE)\nnice_table(stats.table, broom = \"t.test\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-97bde480{table-layout:auto;}.cl-97b8d27e{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-97b8d288{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-97b8d292{font-family:'Times New Roman';font-size:7.2pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3.6pt;}.cl-97baf680{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-97baf68a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-97bb0a12{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97bb0a13{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-97bb0a1c{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-97bde480'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-97bb0a12\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">Method</span></p></th><th class=\"cl-97bb0a12\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">Alternative</span></p></th><th class=\"cl-97bb0a12\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">Mean 1</span></p></th><th class=\"cl-97bb0a12\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">Mean 2</span></p></th><th class=\"cl-97bb0a12\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d288\">M</span><span class=\"cl-97b8d292\">1</span><span class=\"cl-97b8d27e\"> - </span><span class=\"cl-97b8d288\">M</span><span class=\"cl-97b8d292\">2</span></p></th><th class=\"cl-97bb0a12\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d288\">t</span></p></th><th class=\"cl-97bb0a12\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d288\">df</span></p></th><th class=\"cl-97bb0a12\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d288\">p</span></p></th><th class=\"cl-97bb0a12\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">95% CI</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-97bb0a13\"><p class=\"cl-97baf68a\"><span class=\"cl-97b8d27e\">Two Sample t-test</span></p></td><td class=\"cl-97bb0a1c\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">two.sided</span></p></td><td class=\"cl-97bb0a1c\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">654,585.37</span></p></td><td class=\"cl-97bb0a1c\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">604,420.29</span></p></td><td class=\"cl-97bb0a1c\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">50,165.08</span></p></td><td class=\"cl-97bb0a1c\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">0.99</span></p></td><td class=\"cl-97bb0a1c\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">341</span></p></td><td class=\"cl-97bb0a1c\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">.322</span></p></td><td class=\"cl-97bb0a1c\"><p class=\"cl-97baf680\"><span class=\"cl-97b8d27e\">[-49287.48, 149617.63]</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n::: {.notes}\nhttps://rempsyc.remi-theriault.com/articles/t-test\n:::\n\n## 5. Interpretación {style=\"font-size: 0.85em;\"}\n\nNuestro intervalo de confianza **contiene el cero**, por lo que no se rechaza la hipótesis nula\n\n::: {.fragment}\n::: {.content-box-red}\nCon un 95% de confianza (5% de probabilidad de error) no se encuentra evidencia de diferencias salariales entre hombres y mujeres.\n\nAlternativamente: No existe evidencia que las diferencias salariales entre hombres y mujeres son distintas de cero, con un 5% de probabilidad de error\n:::\n:::\n\n# [Resumen]{style=\"color: #dfc117;\"} {data-background-color=\"#0C3547\"}\n\n::: {style=\"color: white; font-size: 0.85em;\"}\n- hipótesis: aseveraciones sobre algo que ocurre en la población, usualmente asociaciones entre conceptos / variables\n\n- las hipótesis se contrastan con un criterio de falsabilidad\n\n- el contraste de hipótesis en estadística opera mediante el rechazo de la hipótesis nula (o de no diferencias), con una probabilidad de error $\\alpha$\n\n- 5 pasos para contraste de hipótesis\n:::\n\n## Próxima clase (miércoles): manos al código {style=\"font-size: 0.85em;\"}\n\n::: {style=\"border-top: 1px solid #0C3547; margin: 0.3em 0;\"}\n:::\n\n### y próximo lunes\n\n- Prueba $t$\n\n- hipótesis direccionales (mayor o menor qué) o de una cola (one tail)\n\n- inferencia para proporciones\n\n## Recomendaciones\n\n[![](img/logicaccss.png){width=\"30%\" fig-align=\"center\"}](https://cienciassocialesfcpys.wordpress.com/wp-content/uploads/2016/03/5la-logica-de-las-ciencias-sociales-popper-adorno-dahrendorf-habermas.pdf)\n\n# {.hide-logo data-background-color=\"#0C3547\"}\n\n<br>\n\n::::: columns\n::: {.column width=\"30%\"}\n\n<br>\n\n![](img/logo-correlacional-transp.png){width=\"100%\" fig-align=\"right\"}\n:::\n\n:::{.column width=\"2%\"}\n\n:::\n\n::: {.column style=\"width: 65%; font-size: 25px; text-align: right; margin: 0 auto;\"}\n\n<br>\n\n### [Estadística Correlacional]{style=\"font-size: 2em; color: white;\"}\n\n::: {style=\"border-top: 1px solid white; margin: 0.3em 0;\"}\n:::\n\n[Inferencia, asociación, y reporte]{style=\"font-size: 1.5em; color: #dfc117;\"}\n\n[Juan Carlos Castillo]{style=\"font-size: 1em; color: white;\"}\\\n[Sociología FACSO - UChile]{style=\"font-size: 1em; color: white;\"}\\\n[2do Sem 2026]{style=\"font-size: 1em; color: white;\"}\n\n[correlacional.metodos-facso.org](https://correlacional.metodos-facso.org)\n\n:::\n:::::\n",
    "supporting": [
      "05-inferencia4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}