---
title: Asignación de Ayudantes
lang: es
---

Con el objetivo de apoyar y monitorear el avance en el aprendizaje de los contenidos prácticos y teóricos del curso, hemos realizado una asignación de ayudantes a cada estudiante del grupo. Esta asignación se basó parcialmente en las prioridades expresadas por ustedes a través de un formulario, designando aleatoriamente a quienes no expresaron preferencias.

A cada ayudante se le asignaron entre 8 y 9 estudiantes, con quienes estará en contacto y se reunirá a lo largo del semestre. Adicionalmente, cada grupo contará con la supervisión de un profesor colaborador. Para facilitar el contacto entre ayudantes y estudiantes, se crearán grupos en U-Cursos. 

La siguiente tabla muestra la distribución establecida.

**Grupos supervisados por Katherine Aravena**

| Amaranta Gonzalez | Tomás González | Joaquín Núñez | Cristóbal Ramírez | Amanda Rojo |
|---|---|---|---|---|
| Amanda Collao | Amanda García | Constanza Pérez | Camila Vázquez | Florencia Trimboli |
| Valentina Loyola | Fernanda Vázquez | Francisco Múñoz | Colomba Lagos | Renata Prieto |
| Fran Takaota | Valentín Báez | Martín Coronado | Martina Zúñiga | Vicente Álvarez |
| Magdalena Abbott | Camilo Prieto | Valentina López | Sofía Inostroza | Ignacio Alvear |
| Celeste Mardones | Lukas Diaz | Diego Peralta | Danahe Aguirre | Martina Carrizo |
| Martín Quinteros | Orlando Morales | Leonor Sáez | Alex Silva | Josefina Pumarino |
| Constanza Araya | Martín Lascano | María Cerda | Benjamín Muñoz | Rebeca Escobar |
| Mia Véliz | Gabriel González | Martina Vega | Sergio Montecinos | Jadee Saud |
| | Isidora Valenzuela | | | |

<br>

**Grupos supervisados por Gabriel Cortés**

| Amaya Barbet | Manuela Chateau | Nicolás Outerbridge | Vicente Rojas |
|---|---|---|---|
| Danahe Arriagada | Vicente Tassara | Anita Novoa | Vicente Badilla |
| Fernanda Cornejo | Montserrat Méndez | Víctor Atabales | Tomás Diedricks |
| Nicole Durán | Emilio Alcaide | Tomás Chávez | Amanda Guijon |
| Pablo Flores | Kintruy Ancanten | Rafael Chacón | Thiare Álvarez |
| Antonia Romero | Joaquín Catalan | Alvaro Peña | Rose Miño |
| Francisco Rondán | Tamara Roa | Jun Sarmiento | Juan Albornoz |
| Catalina Jazme | Fernando Varela | Mateo Tavali | Julieta Olavarría |
| Fabián Jara | Aretha Silva | Daniel Salvo | Bernardita Ormeño |
| Rodrigo Campos | | | |

<br>

**Grupos supervisados por Tomás Urzúa**

| Felipe Vega | Renato de Luca | Cassidy Mansilla | Bastián Martin |
|---|---|---|---|
| Martina Aguirre | Alán Álvarez | Nayomi López | Olivia González |
| Florencia Urquejo | Alec Arancibia | Ingrid Pita | Ignacia Etchegoyen |
| Antonia Rojas | Klaudimar Zambrano | Alonso Palma | Angélica Bozo |
| Renata Cornejo | José Cáceres | Ignacia Rodríguez | Liam Paredes |
| Matilde Ortega | Renato Rojas | Cristóbal Bobadilla | Ayelén Muñoz |
| Camilá Alarcón | Pablo San Martín | Santiago Romero | Cristián Fuentealba |
| Lilian Francke | Antonia Gómez | Maximiliano Cruz | José Flores |
| Manuel Torres | Carlos Lobos | Sofia Tremsal | Dennise Fuica |
| | Vicente Machuca | | |
