{
  "hash": "f961c5b9fd372de320bc3f0d3ff360da",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Distribución Normal e Intervalos de Confianza\"\ndate: \"2025-08-20\"\nlang: es\nexecute:\n  freeze: auto\n  cache: true\nnumber-sections: true\nformat: html\nlightbox: true\n---\n\n# Objetivo de la práctica {.unnumbered}\n\nEl objetivo de esta guía práctica es introducirnos en la inferencia estadística, revisando los conceptos y aplicaciones de la curva normal y las probabilidades bajo esta con puntajes Z, además del cálculo de intervalos de confianza.\n\nEn detalle, aprenderemos y recordaremos:\n\n1.  Los conceptos de promedio y desviación estándar\n2.  Estimación de puntaje Z\\\n3.  Cómo calcular e interpretar intervalos de confianza\n\n# Promedio y desviación estándar\n\nEl *promedio* y la *desviación estándar* son conceptos fundamentales para continuar hacia la estadística inferencial. Repasemos estos conceptos mediante un ejercicio con datos simulados.\n\nPrimero, generaremos un vector de 100 valores aleatorios con $\\mu = 5$ y $\\sigma = 2$. Con la función `summary` podemos un resumen de algunos estadísticos del vector que creamos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) # Fijar la semilla para reproducibilidad\nvector <- rnorm(100, mean = 5, sd = 2)\nsummary(vector) # Ver el vector generado\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.3817  4.0123  5.1235  5.1808  6.3836  9.3747 \n```\n\n\n:::\n:::\n\n\n::: callout-tip\nSi no sabes lo que hace una función en específico, puedes correr el comando `?`. Por ejemplo, `?summary` entrega la descripción, el uso y los argumento de la función de R base `summary`\n:::\n\n¿Cómo se vería la distribución de este vector aleatorio? Una buena práctica en el análisis de datos es realizar un primera inspección visual de los datos. Los tres gráficos que siguen nos dan una buena idea de la distribución del vector creado.\n\n::: {layout=\"\\[\\[100\\], \\[50,50\\]\\]\" .lightbox group= \"galeria\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(vector,main=\"Histograma del Vector\",xlab=\"Valor\",ylab=\"Frecuencia\",col=\"cyan4\",border=\"black\")\n```\n\n::: {.cell-output-display}\n![](01-practico_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(vector,main=\"Diagrama de Caja del Vector aleatorio\",ylab=\"Valor\",col=\"cyan3\")\n```\n\n::: {.cell-output-display}\n![](01-practico_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(vector, main=\"Gráfico Q-Q Normal del Vector\",\n       xlab=\"Cuantiles Teóricos\", ylab=\"Cuantiles Muestrales\",\n       col=\"cyan4\", pch=19)\nqqline(vector, col=\"black\", lwd=2)\n```\n\n::: {.cell-output-display}\n![](01-practico_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n:::\n\nAhora, calculamos la media y la desviación estándar del vector:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedia <- mean(vector)\ndesv_estandar <- sd(vector)\n\ncat(\"Media:\", media, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedia: 5.180812 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Desviación Estándar:\", desv_estandar, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDesviación Estándar: 1.825632 \n```\n\n\n:::\n:::\n\n\nEn el caso de nuestro vector, creado con datos aleatorios, la media $\\bar{x} = 5,18$ nos muestra que el promedio de los datos se encuentra en torno a 5,2.\n\nLa desviación estándar corresponde, entonces, a un promedio de lo que cada valor se aleja del promedio del vector. En el caso de nuestro vector, $s = 1,82$ nos muestra que en promedio los datos se alejan 1,82 puntos del promedio.\n\n# Puntajes Z\n\nAl estandarizar las variables (como en la Curva Normal Estándar) lo que hacemos es expresar el valor de una distribución en términos de desviaciones estándar basados en la distribución normal. Esto nos permite comparar distribuciones distintas.\n\nAl valor estandarizado lo llamamos **puntaje Z**, y corresponde a la cantidad de desviaciones estándar que nos alejamos del promedio (para cada variable con la que trabajemos).\n\n## Cálculo de probabilidades con puntaje Z\n\nRecordemos que la formula para calcular el puntaje z es:\n\n$$\nz = \\frac{x - \\bar{x}}{s}\n$$\n\ndonde $x$ es el valor observado, $\\bar{x}$ la media y $s$ la desviación estándar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_scores <- (vector - media) / desv_estandar\n\n# Comparar valores originales y estandarizados\nhead(data.frame(Valor=vector, Z=z_scores), 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Valor           Z\n1  3.879049 -0.71304802\n2  4.539645 -0.35120270\n3  8.117417  1.60854170\n4  5.141017 -0.02179795\n5  5.258575  0.04259548\n6  8.430130  1.77983218\n7  5.921832  0.40589817\n8  2.469878 -1.48492941\n9  3.626294 -0.85149566\n10 4.108676 -0.58726835\n```\n\n\n:::\n:::\n\n\nAhora bien, R trae incorporadas funciones que permiten hacer estos calculos más rapidos. En este caso, usamos la función `scale` para centrar el vector en torno a su media.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estandarizar el vector\nz_scores_scale <- scale(vector)\n\n# Comparar valores originales y estandarizados según ambos métodos. \nhead(data.frame(Valor=vector, Z_manual=z_scores, z_scale=z_scores_scale), 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Valor    Z_manual     z_scale\n1  3.879049 -0.71304802 -0.71304802\n2  4.539645 -0.35120270 -0.35120270\n3  8.117417  1.60854170  1.60854170\n4  5.141017 -0.02179795 -0.02179795\n5  5.258575  0.04259548  0.04259548\n6  8.430130  1.77983218  1.77983218\n7  5.921832  0.40589817  0.40589817\n8  2.469878 -1.48492941 -1.48492941\n9  3.626294 -0.85149566 -0.85149566\n10 4.108676 -0.58726835 -0.58726835\n```\n\n\n:::\n:::\n\n\n::: callout-tip\nNoten que ambos procedimientos llegan al mismo resultados\n:::\n\nLos valores estandarizados o puntajes Z además nos permiten conocer probabilidades.\n\nCon R es posible generar un conjunto de datos simulados con una distribución normal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_values <- seq(-4,4,length=1000)\ny_values <- dnorm(x_values)\nplot(x_values,y_values,type=\"l\",xlab=\"Valor Z\",ylab=\"Probabilidad\",main=\"Distribución Normal\")\n```\n\n::: {.cell-output-display}\n![](01-practico_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nPodemos preguntar qué parte de la curva cae por debajo de un valor particular. Por ejemplo, preguntaremos sobre el valor 0 antes de ejecutar el código. Piense ¿cuál debería ser la respuesta?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Probabilidades acumuladas\npnorm(0)       # P(Z <= 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5\n```\n\n\n:::\n:::\n\n\nAhora probemos los valores Z de +1,96 y -1,96.\n\nSabemos que estos valores aproximados marcan el 2,5% superior e inferior de la distribución normal estándar. Esto corresponde a un alfa típico $\\alpha = 0,05$ para una prueba de hipótesis de dos colas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1.96)    # P(Z <= 1.96)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9750021\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(-1.96)   # P(Z <= -1.96)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0249979\n```\n\n\n:::\n:::\n\n\nLa respuesta nos dice lo que ya sabemos: el 97,5% de la distribución normal ocurre por debajo del valor z de 1,96.\n\ny si lo visualizamos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(x_values, y_values, type=\"l\", lty=1, xlab=\"Z value\", ylab=\"Probability\", main=\"Normal Distribution\") +\nabline(v = 1.96)\n```\n\n::: {.cell-output-display}\n![](01-practico_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\ninteger(0)\n```\n\n\n:::\n:::\n\n\n# Error Estándar\n\nEl error estándar es la desviación estándar de la distribución muestral de la media, y mide cuánto varía dicho estadístico entre distintas muestras de una misma población. Se define formalmente como:\n\n$$\nSE = \\frac{s}{\\sqrt{n}}\n$$\n\ndonde $s$ es la desviación estándar de la muestra y $n$ es el tamaño de la muestra.\n\nCalculemos el Error Estándar de nuestro vector:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_vector <- length(vector) # calculamos el tamaño muestral\n\nee_vector <- desv_estandar/sqrt(n_vector)\n\nee_vector\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1825632\n```\n\n\n:::\n:::\n\n\n# Intervalos de confianza\n\nUn intervalo de confianza es un rango dentro del cual es probable que se encuentre un parámetro poblacional con un nivel de confianza específico. Además, proporciona información sobre la precisión de nuestras estimaciones.\n\n## Cálculo de intervalos de confianza para medias\n\nEn el caso de nuestro vector aleatorio, presentamos tres maneras de calcular el intervalo de confianza para la media\n\nPrimero, a través del calculo manual, recordando que:\n\n$$\nIC = \\bar{x} \\pm z \\cdot \\frac{s}{\\sqrt{n}}\n$$\n\ndonde $\\bar{x}$ es la media muestral, $z$ es el valor crítico según el nivel de confianza (por ejemplo, 1,96 para un 95%), $s$ la desviación estándar y $n$ el tamaño de la muestra.\n\n::: callout-important\nRecordemos: $\\frac{s}{\\sqrt{n}}$ es igual al Error Estándar.\n:::\n\nDe tal modo, para saber el intervalo de confianza al 95% de confianza.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nic_vector_inf <- media - 1.96 * ee_vector # Limite inferior del Intervalo\nic_vector_sup <- media + 1.96 * ee_vector # Límite superior del Intervalo\n\ncat(\"Media:\", media, \"- IC 95%: [\", ic_vector_inf, \",\", ic_vector_sup, \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedia: 5.180812 - IC 95%: [ 4.822988 , 5.538636 ]\n```\n\n\n:::\n:::\n\n\nUna alternativa la función `t.test` que, por defecto, estima el intervalo de confianza del 95%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcular un intervalo de confianza para la media\nintervalo_confianza <- t.test(vector)$conf.int  # Intervalo de confianza del 95% para la media\nintervalo_confianza\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.818567 5.543057\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\nOtra opción es con la función `ci.mean` del paquete `Publish`. Con esta función también podemos especificar si queremos estimar los CI al 95% (alpha = 0.05) o al 99% (alpha = 0.05)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!requireNamespace(\"Publish\", quietly = TRUE)) install.packages(\"Publish\") # Si no está instalado, instala el paquete\nlibrary(Publish) # lo cargamos\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'Publish' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: prodlim\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'prodlim' was built under R version 4.5.3\n```\n\n\n:::\n\n```{.r .cell-code}\nPublish::ci.mean(vector, alpha = 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mean CI-95%     \n 5.18 [4.82;5.54]\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n`install.packages()` instala paquetes de R en tu sistema. Solo se debe correr una vez. Una vez instalado solo debe llamar el paquete con la función `library()`.\n\nAlternativamente, la función `p_load` del paquete `pacman` permite instalar y cargar múltiples paquetes con solo una línea de código\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!requireNamespace(\"pacman\", quietly = TRUE)) install.packages(\"pacman\") # instala pacman, si es necesario\n\npacman::p_load(Publish, dplyr) # ambos paquetes se instalarán (de ser necesario) y se cargarán en la sesión. \n```\n:::\n\n:::\n\nContamos con una media 5.18 como estimación puntual. Pero también podemos decir que con un 95% de confianza el parámetro poblacional se encontrará entre 4.82 y 5.54.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPublish::ci.mean(vector, alpha = 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mean CI-99%     \n 5.18 [4.70;5.66]\n```\n\n\n:::\n:::\n\n\nContamos con una media 5.18 como estimación puntual. Pero también podemos decir que con un 99% de confianza el parámetro poblacional se encontrará entre 4.70 y 5.66.\n\n# Resumen {.unnumbered}\n\nHoy pudimos aprender y recordar:\n\n1.  Los conceptos de promedio y dispersión\n2.  Estimación de puntajes Z\n3.  Cálculo del Error Estándar\n4.  Cálculo de intervalos de confianza\n\n\n# Ejercicio práctico de trabajo autónomo {.unnumbered}\n\nEn este ejercicio aplicará los contenidos revisados: cálculo de media y desviación estándar, puntajes Z, error estándar e intervalos de confianza, pero esta vez con datos reales en lugar de datos simulados.\n\nTrabajaremos con el conjunto de datos `Galton`, incluido en el paquete `HistData`, que contiene las estaturas de 928 hijos e hijas adultos recopiladas por Francis Galton en 1886. Este es, de hecho, el conjunto de datos histórico que dio origen al estudio de la curva normal aplicada a variables biológicas.\n\n::: callout-note\n[Francis Galton](https://es.wikipedia.org/wiki/Francis_Galton), primo de Charles Darwin, no sólo hizo aportes importantes al uso de la distribución normal, también fue pionero en el uso de correlaciones, inventó la línea de regresión, fundo la psicometría, ideó un método para clasificar huellas dáctilares y fue iniciador de de la ciencia metereológica.\n\nEn su lado menos alegre, inventó el concepto de eugenesia... y abogó activamente por ella.\n:::\n\n\n## Instrucciones {.unnumbered}\n\n0.  Cargue la base de datos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!requireNamespace(\"HistData\", quietly = TRUE)) install.packages(\"HistData\") # Si no está instalado, instala el paquete\nlibrary(HistData)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'HistData' was built under R version 4.5.3\n```\n\n\n:::\n\n```{.r .cell-code}\ndata(\"Galton\")\n\nnames(Galton) # revisar las variables disponibles: \"parent\" y \"child\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"parent\" \"child\" \n```\n\n\n:::\n\n```{.r .cell-code}\naltura <- Galton$child # creamos el vector con la variable de interés\n```\n:::\n\n\n::: callout-tip\nLa unidad de medida de la variable se encuentra en pulgadas.\n:::\n\n1.  Calcule y describa la distribución\n\n-   Obtenga la media y desviación estándar de la estatura.\n-   Visualice la distribución en un histograma\n\n2.  Estandarice los datos (puntajes Z)\n\n-   Transforme la variable a puntajes Z\n-   Muestre los primeros 10 valores (`head()`).\n-   Muestre también los últimos 10 valores (`tail()`).\n-   ¿Cuál es el máximo puntaje Z y el mínimo puntaje Z? ¿A qué estatura corresponden?\n-   Verifique la media y desviación estándar\n\n3.  Calcule el error estándar de la variable\n\n4.  Calcule el intervalo de confianza para la media\n\n-   Estime el IC para un 95% de confianza\n-   Estime el IC para un 99% de confianza. ¿Qué sucede con el ancho del intervalo?\n\n5.  Explore el efecto del tamaño muestral\n\n-   Generemos 3 submuestras aleatorias con la función `sample()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nmuestra_100 <- sample(altura, 100)\nmuestra_200 <- sample(altura, 200)\nmuestra_400 <- sample(altura, 400)\n```\n:::\n\n\n-   Calcule el error muestral y el intervalo de confianza al 95% de cada muestra ¿Qué pasa con el error estándar y el intervalo de confianza a medida que aumenta el tamaño de la muestra?\n\n# Referencias {.unnumbered}\n\n[Análisis de datos en Lenguaje R](/files/textos/ximenez2022.pdf)",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}