---
title : "The Impact of Open and Reproducible Scholarship on Students’ Scientific Literacy, Engagement, and Attitudes towards Science: A Review and Synthesis of the Evidence"
date : "2022-04-01"
author : "Pownall, Madeleine; Azevedo, Flavio; Konig, Laura M.; Slack, Hannah Rachael; Evans, Thomas Rhys; Flack, Zoe; Grinschgl, Sandra; Elsherif, Mahmoud; Gilligan-Lee, Katie; Oliveira, Catia Margarida; Gjoneska, Biljana; Kanadadze, Tamara; Button, Kate; Ashcroft-Jones, Sarah; Terry, Jenny; Albayrak-Aydemir, Nihan; Dechterenko, Filip; Alzahawi, Shilaan; Baker, Bradley James; Pittelkow, Merle-Marie; Riedl, Lydia; Schmidt, Kathleen; Pennington, Charlotte Rebecca; Shaw, John J.; Luke, Timo; Makel, Matthew C.; Hartmann, Helena; Zaneva, Mirela; Walker, Daniel; Verheyen, Steven; Cox, Daniel; Mattschey, Jennifer; Gallagher-Mitchell, Thomas; Branney, Peter; Weisberg, Yanna; Izydorczak, Kamil; Al-Hoorie, Ali H.; Creaven, Ann-Marie; Stewart, Suzanne; Krautter, Kai; Matvienko-Sikar, Karen; Westwood, Samuel; Arriaga, Patricia; Liu, Meng; Baum, Myriam A.; Wingen, Tobias; Ross, Robert M.; O'Mahony, Aoife; Bochynska, Agata; Jamieson, Michelle K.; Tromp, Myrthe Vel; Yeung, Siu Kit; Vasilev, Martin Rachev; Gourdon-Kanhukamwe, Amelie; Micheli, Leticia; Konkol, Markus; Moreau, David; Bartlett, James E.; Brekelmans, Gwen; Gkinopoulos, Theofilos; Tyler, Samantha; Roer, Jan Philipp; Ilchovska, Zlatomira; Madan, Christopher; Robertson, Olly; Iley, Bethan; Guay, Samuel; Sladekova, Martina; Sadhwani, Shanu & FORRT"
categories : ["Presentation"]
publication : "  MetaArXiv [https://doi.org/10.31222/osf.io/9e526](https://doi.org/10.31222/osf.io/9e526)"
publication_short : "  MetaArXiv [https://doi.org/10.31222/osf.io/9e526](https://doi.org/10.31222/osf.io/9e526)"
abstract : "In recent years, the scientific community has called for improvements in the credibility, robustness, and reproducibility of research, characterized by higher standards of scientific evidence, increased interest in open practices, and promotion of transparency. While progress has been positive, there is a lack of consideration about how this approach can be embedded into undergraduate and postgraduate research training. Currently, the impact of integrating an open and reproducible approach into the curriculum on student outcomes is not well articulated in the literature. Therefore, in this paper, we provide the first comprehensive review of how integrating open and reproducible scholarship into teaching and learning may impact students, using a large-scale, collaborative, team-science approach. Our review highlighted how embedding open and reproducible scholarship may impact: (1) students’ scientific literacies (i.e., students’ understanding of open research, consumption of science, and the development of transferable skills); (2) student engagement (i.e., motivation and engagement with learning, collaboration, and engagement in open research), and (3) students’ attitudes towards science (i.e., trust in science and confidence in research findings). Our review also identified a need for more robust and rigorous methods within evaluations of teaching practice. We discuss implications for teaching and learning scholarship in this area."
abstract_short : ""
about:
  template: marquee
  links:
    - icon: NA
      href: NA
---


::: {.callout-note title="How to cite this work"}

Pownall, Madeleine; Azevedo, Flavio; Konig, Laura M.; Slack, Hannah Rachael; Evans, Thomas Rhys; Flack, Zoe; Grinschgl, Sandra; Elsherif, Mahmoud; Gilligan-Lee, Katie; Oliveira, Catia Margarida; Gjoneska, Biljana; Kanadadze, Tamara; Button, Kate; Ashcroft-Jones, Sarah; Terry, Jenny; Albayrak-Aydemir, Nihan; Dechterenko, Filip; Alzahawi, Shilaan; Baker, Bradley James; Pittelkow, Merle-Marie; Riedl, Lydia; Schmidt, Kathleen; Pennington, Charlotte Rebecca; Shaw, John J.; Luke, Timo; Makel, Matthew C.; Hartmann, Helena; Zaneva, Mirela; Walker, Daniel; Verheyen, Steven; Cox, Daniel; Mattschey, Jennifer; Gallagher-Mitchell, Thomas; Branney, Peter; Weisberg, Yanna; Izydorczak, Kamil; Al-Hoorie, Ali H.; Creaven, Ann-Marie; Stewart, Suzanne; Krautter, Kai; Matvienko-Sikar, Karen; Westwood, Samuel; Arriaga, Patricia; Liu, Meng; Baum, Myriam A.; Wingen, Tobias; Ross, Robert M.; O'Mahony, Aoife; Bochynska, Agata; Jamieson, Michelle K.; Tromp, Myrthe Vel; Yeung, Siu Kit; Vasilev, Martin Rachev; Gourdon-Kanhukamwe, Amelie; Micheli, Leticia; Konkol, Markus; Moreau, David; Bartlett, James E.; Brekelmans, Gwen; Gkinopoulos, Theofilos; Tyler, Samantha; Roer, Jan Philipp; Ilchovska, Zlatomira; Madan, Christopher; Robertson, Olly; Iley, Bethan; Guay, Samuel; Sladekova, Martina; Sadhwani, Shanu & FORRT (2022). *The Impact of Open and Reproducible Scholarship on Students’ Scientific Literacy, Engagement, and Attitudes towards Science: A Review and Synthesis of the Evidence*.   MetaArXiv [https://doi.org/10.31222/osf.io/9e526](https://doi.org/10.31222/osf.io/9e526)

:::

