{
  "hash": "cab4f83840774a2c19598e9adcabf7a3",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\n# quartolanguage: es\nformat:\n  revealjs:\n    incremental: true\n    scrollable: true\n    logo: img/logo-correlacional-transp.png\n    theme: [css/custom_2025.scss]\n    title-slide-attributes:\n      visibility: false\n    transition: none\n    transition-speed: slow\n    auto-play-media: true\n    title-slide-logo: false\n    slide-number: true\neditor: source\nfreeze: auto\n---\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n# {.hide-logo data-background-color=\"#0C3547\"}\n\n<br>\n\n::::: columns\n::: {.column width=\"30%\"}\n\n<br>\n\n![](img/logo-correlacional-transp.png){width=\"100%\" fig-align=\"right\"}\n:::\n\n:::{.column width=\"2%\"}\n\n:::\n\n::: {.column style=\"width: 65%; font-size: 25px; text-align: right; margin: 0 auto;\"}\n\n<br>\n\n### [Estadística Correlacional]{style=\"font-size: 2em; color: white;\"}\n\n::: {style=\"border-top: 1px solid white; margin: 0.3em 0;\"}\n:::\n\n[Inferencia, asociación, y reporte]{style=\"font-size: 1.5em; color: #dfc117;\"}\n\n[Juan Carlos Castillo]{style=\"font-size: 1em; color: white;\"}\\\n[Sociología FACSO - UChile]{style=\"font-size: 1em; color: white;\"}\\\n[2do Sem 2026]{style=\"font-size: 1em; color: white;\"}\n\n[correlacional.metodos-facso.org](https://correlacional.metodos-facso.org)\n\n<br>\n[**Inferencia 5**:]{style=\"color: white; font-size: 1.3em;\"}\n\n[Hipótesis direccionales y de proporciones]{style=\"color: #dfc117;\"}\n\n:::\n:::::\n\n# \n\n[Recordando 5 pasos de la inferencia]{style=\"color: #ef0303; font-size: 1.3em;\"} \n\n1. Formular hipótesis ( $H_0$ y $H_A$)\n\n2. Obtener error estándar y estadístico de prueba empírico correspondiente (ej: Z o t)\n\n3. Establecer la probabilidad de error $\\alpha$ (usualmente 0.05) y obtener valor crítico (teórico) de la prueba correspondiente\n\n4. Cálculo de intervalo de confianza / contraste valores empírico/crítico\n\n5. Interpretación\n\n## Esta clase {data-background-color=\"#9B2626\"}\n\n::: {style=\"color: white;\"}\n1. hipótesis direccionales de diferencia de medias\n\n2. hipótesis para proporciones (por ejemplo, mayor o menor qué)\n:::\n\n# [1. Hipótesis direccionales]{style=\"color: white;\"} {data-background-color=\"#0C3547\"}\n\n## [Comparación entre grupos]{style=\"font-size: 0.9em;\"} \n\n:::{.columns}\n\n:::{.column width=\"45%\" style=\"font-size: 0.9em;\"}\n\n  - gran parte de las hipótesis de investigación se relacionan con **diferencias entre grupos**, ej:\n\n  - hombres obtienen mayor salario que las mujeres\n\n  - los chilenos son más prejuiciosos que los migrantes\n\n  - ahora se apoyan los cambios más graduales que antes (comparación en el tiempo)\n:::\n\n:::{.column width=\"50%\"}\n\n![](img/Normal_TwoGroups.png)\n\n:::\n\n:::\n\n\n## {data-background-color=\"#0C3547\"}\n\n::: {style=\"color: white; font-size: 1.3em; text-align: right;\"}\n_\"la sociología comparada no es una rama especial de la sociología, sino que es la sociología misma en tanto deja de ser puramente descriptiva y aspira a dar razón de los hechos\"_\n:::\n\n::: {style=\"color: white; text-align: right;\"}\nDurkheim (1895), *Les règles de la méthode sociologique*, op. cit., p. 137\n:::\n\n## {data-background-color=\"#0c4712\" style=\"color: white; text-align: center;\"}\n\n### [_¿Es posible traducir una pregunta de investigación en una hipótesis de diferencia de medias?_]{style=\"color: #dfc117; font-size: 1.3em;\"}\n\n## Comparación de **medias** ( $\\bar{X}$) {style=\"font-size: 0.85em;\"}\n\n- la comparación de medias es una manera de contrastar empíricamente teorías e hipótesis de investigación\n\n- al traducir a este lenguaje, se puede aplicar **inferencia estadística** para contrastar la hipótesis planteada\n\n## La prueba t {style=\"font-size: 0.9em;\"}\n\n- tenemos un valor de diferencia de medias: $\\bar{X}_1 - \\bar{X}_2$\n  \n- vamos a **TRANSFORMAR** este valor a un estándar comparable que nos permita evaluar **QUE TAN GRANDE** es esta diferencia\n\n- ¿Qué es GRANDE? -> qué tan distinto es de 0 en términos de **desviaciones estándar**\n\n- para esto, la diferencia de medias se divide por su ERROR ESTANDAR - >  **PRUEBA t**\n\n- Este valor t de nuesta diferencia de medias (t empírico) se compara con el **t crítico**\n\n## Visualización interactiva: prueba $t$ {style=\"font-size: 0.8em;\"}\n\n```{=html}\n<div class=\"ttest-widget\" style=\"font-size: 0.5em; color: #222; line-height: 1.4;\">\n  <div style=\"display:flex; gap:2em; flex-wrap:wrap; align-items:center; margin-bottom:0.4em;\">\n    <label>grados de libertad (df): <input type=\"range\" id=\"tt-df\" min=\"1\" max=\"300\" value=\"20\" style=\"vertical-align:middle;\"> <span id=\"tt-df-val\">20</span></label>\n    <label>&alpha; (significancia): <input type=\"range\" id=\"tt-alpha\" min=\"0.001\" max=\"0.5\" step=\"0.001\" value=\"0.05\" style=\"vertical-align:middle;\"> <span id=\"tt-alpha-val\">0.05</span></label>\n    <label>t empírico: <input type=\"range\" id=\"tt-tval\" min=\"-6\" max=\"6\" step=\"0.01\" value=\"1.62\" style=\"vertical-align:middle;\"> <span id=\"tt-tval-val\">1.62</span></label>\n  </div>\n  <div style=\"margin-bottom:0.4em;\">\n    <label style=\"margin-right:1.5em;\"><input type=\"radio\" name=\"tt-tail\" value=\"two\" checked> H1: &mu; &ne; &mu;0 (dos colas)</label>\n    <label style=\"margin-right:1.5em;\"><input type=\"radio\" name=\"tt-tail\" value=\"less\"> H1: &mu; &lt; &mu;0</label>\n    <label><input type=\"radio\" name=\"tt-tail\" value=\"greater\"> H1: &mu; &gt; &mu;0</label>\n  </div>\n  <div id=\"tt-plot\" style=\"width:100%; height:420px;\"></div>\n</div>\n\n<script src=\"https://cdn.plot.ly/plotly-2.32.0.min.js\"></script>\n<script>\n(function() {\n  function gammaln(xx) {\n    var cof = [76.18009172947146,-86.50532032941677,24.01409824083091,\n               -1.231739572450155,0.1208650973866179e-2,-0.5395239384953e-5];\n    var x = xx, y = xx;\n    var tmp = x + 5.5;\n    tmp -= (x + 0.5) * Math.log(tmp);\n    var ser = 1.000000000190015;\n    for (var j = 0; j <= 5; j++) { y += 1; ser += cof[j] / y; }\n    return -tmp + Math.log(2.5066282746310005 * ser / x);\n  }\n\n  function betacf(x, a, b) {\n    var MAXIT = 200, EPS = 3e-7, FPMIN = 1e-30;\n    var qab = a + b, qap = a + 1, qam = a - 1;\n    var c = 1, d = 1 - qab * x / qap;\n    if (Math.abs(d) < FPMIN) d = FPMIN;\n    d = 1 / d;\n    var h = d;\n    for (var m = 1; m <= MAXIT; m++) {\n      var m2 = 2 * m;\n      var aa = m * (b - m) * x / ((qam + m2) * (a + m2));\n      d = 1 + aa * d; if (Math.abs(d) < FPMIN) d = FPMIN;\n      c = 1 + aa / c; if (Math.abs(c) < FPMIN) c = FPMIN;\n      d = 1 / d; h *= d * c;\n      aa = -(a + m) * (qab + m) * x / ((a + m2) * (qap + m2));\n      d = 1 + aa * d; if (Math.abs(d) < FPMIN) d = FPMIN;\n      c = 1 + aa / c; if (Math.abs(c) < FPMIN) c = FPMIN;\n      d = 1 / d;\n      var del = d * c; h *= del;\n      if (Math.abs(del - 1) < EPS) break;\n    }\n    return h;\n  }\n\n  function betai(x, a, b) {\n    if (x <= 0) return 0;\n    if (x >= 1) return 1;\n    var bt = Math.exp(gammaln(a + b) - gammaln(a) - gammaln(b) +\n                       a * Math.log(x) + b * Math.log(1 - x));\n    if (x < (a + 1) / (a + b + 2)) return bt * betacf(x, a, b) / a;\n    else return 1 - bt * betacf(1 - x, b, a) / b;\n  }\n\n  function tcdf(t, df) {\n    var x = df / (df + t * t);\n    var p = betai(x, df / 2, 0.5);\n    return t > 0 ? 1 - 0.5 * p : 0.5 * p;\n  }\n\n  function upperTail(t, df) { return 1 - tcdf(t, df); }\n\n  function findCritT(targetUpper, df) {\n    var lo = 0, hi = 100;\n    for (var i = 0; i < 100; i++) {\n      var mid = (lo + hi) / 2;\n      if (upperTail(mid, df) > targetUpper) lo = mid; else hi = mid;\n    }\n    return (lo + hi) / 2;\n  }\n\n  function tpdf(t, df) {\n    var logC = gammaln((df + 1) / 2) - gammaln(df / 2) - 0.5 * Math.log(df * Math.PI);\n    return Math.exp(logC) * Math.pow(1 + (t * t) / df, -(df + 1) / 2);\n  }\n\n  var elDf = document.getElementById('tt-df');\n  var elAlpha = document.getElementById('tt-alpha');\n  var elTval = document.getElementById('tt-tval');\n  var elDfVal = document.getElementById('tt-df-val');\n  var elAlphaVal = document.getElementById('tt-alpha-val');\n  var elTvalVal = document.getElementById('tt-tval-val');\n  var plotDiv = document.getElementById('tt-plot');\n\n  function getTail() {\n    var radios = document.getElementsByName('tt-tail');\n    for (var i = 0; i < radios.length; i++) if (radios[i].checked) return radios[i].value;\n    return 'two';\n  }\n\n  function render() {\n    var df = parseInt(elDf.value, 10);\n    var alpha = parseFloat(elAlpha.value);\n    var tval = parseFloat(elTval.value);\n    var tail = getTail();\n    elDfVal.textContent = df;\n    elAlphaVal.textContent = alpha.toFixed(3);\n    elTvalVal.textContent = tval.toFixed(2);\n\n    var xs = [], ys = [];\n    for (var x = -6; x <= 6; x += 0.03) { xs.push(x); ys.push(tpdf(x, df)); }\n\n    var critPos, critNeg, rejectRegions = [], pVal, reject, comparisonText;\n\n    if (tail === 'two') {\n      critPos = findCritT(alpha / 2, df);\n      critNeg = -critPos;\n      rejectRegions.push([-6, critNeg]);\n      rejectRegions.push([critPos, 6]);\n      pVal = 2 * upperTail(Math.abs(tval), df);\n      reject = Math.abs(tval) >= critPos;\n      comparisonText = '|t| = ' + Math.abs(tval).toFixed(3) + (reject ? ' ≥ ' : ' < ') + critPos.toFixed(3);\n    } else if (tail === 'greater') {\n      critPos = findCritT(alpha, df);\n      critNeg = null;\n      rejectRegions.push([critPos, 6]);\n      pVal = upperTail(tval, df);\n      reject = tval >= critPos;\n      comparisonText = 't = ' + tval.toFixed(3) + (reject ? ' ≥ ' : ' < ') + critPos.toFixed(3);\n    } else {\n      critNeg = -findCritT(alpha, df);\n      critPos = null;\n      rejectRegions.push([-6, critNeg]);\n      pVal = tcdf(tval, df);\n      reject = tval <= critNeg;\n      comparisonText = 't = ' + tval.toFixed(3) + (reject ? ' ≤ ' : ' > ') + critNeg.toFixed(3);\n    }\n\n    var traces = [{\n      x: xs, y: ys, type: 'scatter', mode: 'lines',\n      line: { color: '#2c7fb8', width: 2 }, name: 'distribución t', hoverinfo: 'skip'\n    }];\n\n    rejectRegions.forEach(function(region) {\n      var rx = [], ry = [];\n      for (var x = region[0]; x <= region[1]; x += 0.03) { rx.push(x); ry.push(tpdf(x, df)); }\n      traces.push({\n        x: rx, y: ry, type: 'scatter', mode: 'lines',\n        fill: 'tozeroy', fillcolor: 'rgba(34,139,34,0.35)',\n        line: { color: 'rgba(34,139,34,0.6)', width: 1 },\n        name: 'zona de rechazo', hoverinfo: 'skip', showlegend: false\n      });\n    });\n\n    var shapes = [];\n    var maxY = Math.max.apply(null, ys) * 1.15;\n    [critPos, critNeg].forEach(function(cv) {\n      if (cv === null) return;\n      shapes.push({\n        type: 'line', x0: cv, x1: cv, y0: 0, y1: maxY,\n        line: { color: '#d62728', width: 2, dash: 'dash' }\n      });\n    });\n    shapes.push({\n      type: 'line', x0: tval, x1: tval, y0: 0, y1: maxY,\n      line: { color: '#111', width: 2, dash: 'dash' }\n    });\n\n    var annotations = [{\n      x: 0, y: maxY, xref: 'x', yref: 'y', showarrow: false, yanchor: 'bottom',\n      text: 'df = ' + df + ',  α = ' + alpha.toFixed(3),\n      font: { size: 13 }\n    }, {\n      x: (critNeg !== null ? critNeg : critPos), y: maxY * 0.9, xref: 'x', yref: 'y',\n      showarrow: false, font: { size: 11, color: '#d62728' },\n      text: 't crítico = ' + (critPos !== null ? critPos.toFixed(3) : critNeg.toFixed(3))\n    }, {\n      x: tval, y: maxY * 0.55, xref: 'x', yref: 'y', showarrow: false,\n      font: { size: 11, color: '#111' }, xanchor: tval >= 0 ? 'left' : 'right',\n      text: 't = ' + tval.toFixed(3)\n    }, {\n      x: -4.8, y: maxY * 0.75, xref: 'x', yref: 'y', showarrow: false,\n      font: { size: 20, color: reject ? '#1a7a1a' : '#c0392b' },\n      text: '<b>' + (reject ? 'Se rechaza H0' : 'No se rechaza H0') + '</b>'\n    }, {\n      x: 4.8, y: maxY * 0.75, xref: 'x', yref: 'y', showarrow: false,\n      font: { size: 18, color: reject ? '#1a7a1a' : '#c0392b' },\n      text: '<b>' + comparisonText + '<br>p = ' + pVal.toFixed(4) + '</b>'\n    }];\n\n    var layout = {\n      margin: { l: 40, r: 20, t: 25, b: 30 },\n      xaxis: { range: [-6, 6], title: 't' },\n      yaxis: { range: [0, maxY], title: 'densidad' },\n      shapes: shapes,\n      annotations: annotations,\n      showlegend: false\n    };\n\n    Plotly.react(plotDiv, traces, layout, { responsive: true, displayModeBar: false });\n  }\n\n  elDf.addEventListener('input', render);\n  elAlpha.addEventListener('input', render);\n  elTval.addEventListener('input', render);\n  var radios = document.getElementsByName('tt-tail');\n  for (var i = 0; i < radios.length; i++) radios[i].addEventListener('change', render);\n\n  render();\n})();\n</script>\n```\n\n\n## [El **valor crítico** es el punto (o los puntos) en la distribución de un estadístico de prueba que separa la región de aceptación de la región de rechazo en una prueba de hipótesis]{style=\"color: white;\"} {data-background-color=\"#9B2626\"}\n\n## Los **grados de libertad** son la cantidad de información independiente disponible para estimar parámetros o calcular un estadístico {data-background-color=\"#0C3547\" style=\"font-size: 0.8em;\"}\n\n\n- Cada restricción (como conocer un promedio, fijar una suma, etc.) reduce en 1 los grados de libertad.\n\n- Por ejemplo, si hay tres números que tienen promedio 10, se pueden elegir libremente 2 de ellos, y el tercero ya está determinado. Por lo tanto, hay 3-1 grados de libertad\n\n## $t$ y probabilidad de error $p$ {style=\"font-size: 0.9em;\"}\n\n- el cálculo de $t$ (estimado) nos da un valor que puede ser transformado a un valor de área bajo la curva (tal como en Z)\n\n- _¿cuál es la probabilidad de error (valor p) de un $t$ específico?_\n\n- hay que recordar que tanto Z como t tienen promedio 0 y son simétricas, y por lo tanto el 0 divide el área de la curva en 0.5\n\n- 0.5 es la mayor probabilidad de error (=azar total), y a medida que se aleja del 0.5 disminuye la probabilidad de error\n\n## \n\n\n::: {.cell}\n\n```{.r .cell-code}\n(qt(t, df, lower.tail = FALSE)) * 2\n```\n:::\n\n\nDonde:\n\n- qt: función que entrega la probabilidad para un valor $t$\n\n- df: grados de libertad (degrees of freedom)\n\n- lower.tail=FALSE: considera las probabilidades acumuladas hacia la cola superior de la curva\n\n- *2: al ser una prueba de diferencias, considera zona de rechazo en ambas direcciones de la curva, por lo que las probabilidades se multiplican por 2\n\n## En nuestro ejemplo {style=\"font-size: 0.8em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(pt(0.99215, 341, lower.tail = FALSE)) * 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3218278\n```\n\n\n:::\n:::\n\n\n- La probabilidad de error del $t$ estimado es de 0.322.\n\n- Esto quiere decir es que en la estimación de esta diferencia de medias, nos estamos equivocando aproximadamente un tercio de las veces (lejos del nivel convencional de rechazo de $H_0$ de 0.05)\n\n## _p_ y mayores niveles de confianza {style=\"font-size: 0.8em;\"}\n\n- La obtención del valor $p$ podría también entregar información para rechazar $H_0$ con un mayor nivel de confianza al establecido\n\n- Si bien el p<0.05 es aceptado, en el caso que el p sea menor a 0.01 o 0.001, se reporta por convención el valor p menor\n\n- Usualmente en los trabajos de investigación esto se representa con asteriscos: $^{\\ast}p<0.05$, $^{\\ast\\ast}p<0.01$, y $^{\\ast\\ast\\ast}p<0.001$\n\n## [A mayor valor $t$, menor probabilidad de error $p$]{style=\"color: white;\"} {data-background-color=\"#0C3547\"}\n\n## Test de hipótesis: insumos complementarios {style=\"font-size: 0.8em;\"}\n\nEntonces, se logra rechazar la hipótesis nula cuando:\n\n- el intervalo de confianza no contiene el 0\n\n- $t_{calculado} > t_{crítico}$\n\n- $p_{calculado} < p_{crítico}$\n\n  - o en términos generales convencionales, p<0.05\n\n## Test de hipótesis de diferencias en R {style=\"font-size: 0.8em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(salario ~ sexo, data = casen_350, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  salario by sexo\nt = 0.99215, df = 341, p-value = 0.3218\nalternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0\n95 percent confidence interval:\n -49287.48 149617.63\nsample estimates:\nmean in group 1 mean in group 2 \n       654585.4        604420.3 \n```\n\n\n:::\n:::\n\n\n\n## Reporte formato APA {style=\"font-size: 0.75em;\"}\n\n<br>\n\n_\"Se realizó una prueba t para muestras independientes para comparar los salarios entre hombres y mujeres. Los resultados indicaron una diferencia no significativa en los salarios entre hombres (M = 654585, SD = 468692) y mujeres (M = 604420, SD = 444666); t(341)=0.9921, p=0.321. El intervalo de confianza del 95% para la diferencia de medias fue [−49288.49;149618.5]._\n\n[diferencia no significativa=no se logra rechazar $H_0$]\n\n## En R con librería `report` {style=\"font-size: 0.75em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- t.test(salario ~ sexo, data = casen_350, var.equal = TRUE)\nreport::report(model)\n```\n:::\n\n\n_La prueba t de dos muestras que evalúa la diferencia de salario según sexo (media en el grupo 1 = 654585, media en el grupo 2 = 604420) sugiere que el efecto es positivo, estadísticamente no significativo y muy pequeño (diferencia = 50165, IC del 95% [-49,287.48, 150,000], t(341) = 0.99, p = 0.322)._\n\n[traducido y con mínima edición]{style=\"font-size: 0.7em;\"}\n\n## Tipos de preguntas e hipótesis (ej: con promedio(s)) {style=\"font-size: 0.65em;\"}\n\n| **Pregunta**| **Hipótesis**   | **Prueba** |\n|---------------------|------------------------------------------------------|------------|\n| A. ¿Existe el promedio en la población? | $H_{a}: \\bar{X}_1 \\neq 0$ <br> $H_{0}: \\bar{X}_1 = 0$ | Dos colas (no direccional) |\n| B. ¿Existen diferencias de promedios en la población? | $H_{a}: \\bar{X}_1 -  \\bar{X}_2 \\neq 0$ <br> $H_{0}: \\bar{X}_1 -  \\bar{X}_2= 0$ | Dos colas (no direccional) |\n| C. ¿Es un promedio (1) superior (o inferior) al otro (2)? | $H_{a}: \\bar{X}_1 -  \\bar{X}_2 \\gt 0$ <br> $H_{0}: \\bar{X}_1 -  \\bar{X}_2 \\leq 0$ | Una cola (direccional) |\n\n## {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n![](img/direccional-derecha.png){width=\"100%\" fig-align=\"center\"}\n\n:::\n\n::: {.column width=\"50%\"}\n\nSi bien en teoría las hipótesis direccionales se pueden plantear en ambas direcciones, en general (y por simpleza) se expresan en términos de \"mayor que\", quedando la zona de rechazo de $H_0$ a la derecha\n\n:::\n::::\n\n## Pasos en test de hipótesis {style=\"font-size: 0.75em;\"}\n\n1. Formulación: El salario de los hombres (grupo 1) es mayor al de las mujeres (grupo 2)\n\n::: {.fragment}\n$$\n\\begin{align*}\nH_{a}: \\bar{X}_1 \\gt  \\bar{X}_2 \\\\\nH_{0}: \\bar{X}_1 \\leq  \\bar{X}_2\n\\end{align*}\n$$\n:::\n\n2. Obtener error estándar y estadístico de prueba (lo mismo que para el caso anterior)\n\n::: {.fragment}\n$$t=\\frac{(\\bar{x}_1-\\bar{x}_2)}{\\sqrt{\\frac{s_1²}{\\sqrt{n_1}}+\\frac{s_2²}{\\sqrt{n_2}} }}=\\frac{50165}{50561}=0.9921$$\n:::\n\n## 3. Probabilidad de error y valor crítico {style=\"font-size: 0.8em;\"}\n\n- seguimos con probabilidad de error ( $\\alpha$ 0.05), pero a diferencia de las no-direccionales no se divide entre 2 (colas), sino que es solo para una\n\n::: {.fragment}\n![](img/One_tailed_and_two_tailed_t-test.png){width=\"80%\" fig-align=\"center\"}\n:::\n\n## 3. Probabilidad de error y valor crítico {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n- para un nivel de error $\\alpha=0.05$ (de una cola)\n\n- grados de libertad N-2= 343-2 = 341\n\n:::\n\n::: {.column .fragment width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(p = .05,\n   df = 341,\n   lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.649334\n```\n\n\n:::\n:::\n\n\n[lower.tail=FALSE se refiere que el cálculo refiere a la cola superior]{style=\"font-size: 0.8em;\"}\n\n:::\n::::\n\n## 4. Contraste {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n- Recordemos nuestra hipótesis nula:\n\n::: {.fragment}\n$$H_{0}: \\bar{X}_{hombres} \\leq  \\bar{X}_{mujeres}$$\n:::\n\n- Considerando los valores de contraste:\n\n::: {.fragment}\n$$t_{estimado}=0.992 < t_{crítico}=1.6$$\n:::\n\n:::\n\n::: {.column .fragment width=\"50%\"}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-inferencia5_files/figure-revealjs/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n:::\n::::\n\n## 5. Interpretación {style=\"font-size: 0.8em;\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-f289a0ca{table-layout:auto;}.cl-f285732e{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f2857338{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f2857339{font-family:'Times New Roman';font-size:7.2pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;vertical-align:sub;}.cl-f2874d16{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-f2874d2a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-f2875e3c{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f2875e46{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f2875e47{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-f289a0ca'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-f2875e3c\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">Method</span></p></th><th class=\"cl-f2875e3c\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">Alternative</span></p></th><th class=\"cl-f2875e3c\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">Mean 1</span></p></th><th class=\"cl-f2875e3c\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">Mean 2</span></p></th><th class=\"cl-f2875e3c\"><p class=\"cl-f2874d16\"><span class=\"cl-f2857338\">M</span><span class=\"cl-f2857339\">1</span><span class=\"cl-f285732e\"> - </span><span class=\"cl-f2857338\">M</span><span class=\"cl-f2857339\">2</span></p></th><th class=\"cl-f2875e3c\"><p class=\"cl-f2874d16\"><span class=\"cl-f2857338\">t</span></p></th><th class=\"cl-f2875e3c\"><p class=\"cl-f2874d16\"><span class=\"cl-f2857338\">df</span></p></th><th class=\"cl-f2875e3c\"><p class=\"cl-f2874d16\"><span class=\"cl-f2857338\">p</span></p></th><th class=\"cl-f2875e3c\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">95% CI</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-f2875e46\"><p class=\"cl-f2874d2a\"><span class=\"cl-f285732e\">Two Sample t-test</span></p></td><td class=\"cl-f2875e47\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">greater</span></p></td><td class=\"cl-f2875e47\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">654,585.37</span></p></td><td class=\"cl-f2875e47\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">604,420.29</span></p></td><td class=\"cl-f2875e47\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">50,165.08</span></p></td><td class=\"cl-f2875e47\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">0.99</span></p></td><td class=\"cl-f2875e47\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">341</span></p></td><td class=\"cl-f2875e47\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">.161</span></p></td><td class=\"cl-f2875e47\"><p class=\"cl-f2874d16\"><span class=\"cl-f285732e\">[-33228.46, Inf]</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n_\"Se realizó una prueba t para muestras independientes para examinar si el salario promedio de los hombres (M = 654585, SD = 468692) es mayor que el de las mujeres (M = 604420, SD = 444666), siendo la diferencia entre ambos de 50.165. Los resultados no fueron estadísticamente significativos, t(341)=0.9921, p=0.161. Por lo tanto, con un 95% de confianza no se puede rechazar la hipótesis nula, lo que no permite sustentar la hipótesis inicial (alternativa) que el salario de los hombres es mayor que el de las mujeres.\"_\n\n<!--\nNota: en el práctico cambiar el N de la muestra y establecer distintos niveles de confianza\n-->\n\n## [¿Qué habría pasado con un tamaño muestral más grande, y/o con un nivel de probabilidad de error distinto?]{style=\"color: white;\"} {data-background-color=\"#0C3547\"}\n\n## sub-muestra CASEN 1500 casos {style=\"font-size: 0.8em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncasen_1500 %>% # se especifica la base de datos\n  dplyr::group_by(sexo = sjlabelled::as_label(sexo)) %>% # se agrupan por la variable categórica y se usan sus etiquetas con as_label\n  dplyr::summarise(Obs. = n(), Promedio = mean(salario, na.rm = TRUE), SD = sd(salario, na.rm = TRUE)) %>% # se agregan las operaciones a presentar en la tabla\n  kable(format = \"markdown\") # se genera la tabla\n```\n\n::: {.cell-output-display}\n\n\n|sexo      | Obs.| Promedio|       SD|\n|:---------|----:|--------:|--------:|\n|1. Hombre |  757| 756712.0| 852544.0|\n|2. Mujer  |  680| 605150.2| 523794.4|\n\n\n:::\n:::\n\n\n## {style=\"font-size: 0.75em;\"}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_dir2 <- t.test(\n  salario ~ sexo,\n  data = casen_1500,\n  alternative = \"greater\",\n  var.equal = TRUE,\n  conf.level = 0.95)\nstats.table4 <- tidy(model_dir2)\nnice_table(stats.table4,\n           broom = \"t.test\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-f2c38d6c{table-layout:auto;}.cl-f2a6373a{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f2a63744{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f2a63745{font-family:'Times New Roman';font-size:7.2pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;vertical-align:sub;}.cl-f2a7f8a4{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-f2a7f8ae{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-f2a80948{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f2a80952{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f2a80953{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-f2c38d6c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-f2a80948\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">Method</span></p></th><th class=\"cl-f2a80948\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">Alternative</span></p></th><th class=\"cl-f2a80948\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">Mean 1</span></p></th><th class=\"cl-f2a80948\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">Mean 2</span></p></th><th class=\"cl-f2a80948\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a63744\">M</span><span class=\"cl-f2a63745\">1</span><span class=\"cl-f2a6373a\"> - </span><span class=\"cl-f2a63744\">M</span><span class=\"cl-f2a63745\">2</span></p></th><th class=\"cl-f2a80948\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a63744\">t</span></p></th><th class=\"cl-f2a80948\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a63744\">df</span></p></th><th class=\"cl-f2a80948\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a63744\">p</span></p></th><th class=\"cl-f2a80948\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">95% CI</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-f2a80952\"><p class=\"cl-f2a7f8ae\"><span class=\"cl-f2a6373a\">Two Sample t-test</span></p></td><td class=\"cl-f2a80953\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">greater</span></p></td><td class=\"cl-f2a80953\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">756,712.01</span></p></td><td class=\"cl-f2a80953\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">605,150.23</span></p></td><td class=\"cl-f2a80953\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">151,561.78</span></p></td><td class=\"cl-f2a80953\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">4.01</span></p></td><td class=\"cl-f2a80953\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">1,435</span></p></td><td class=\"cl-f2a80953\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">&lt; .001***</span></p></td><td class=\"cl-f2a80953\"><p class=\"cl-f2a7f8a4\"><span class=\"cl-f2a6373a\">[89291.57, Inf]</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-inferencia5_files/figure-revealjs/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n:::\n::::\n\n## Actividad práctica\n\n![](img/menti-clase-final.png)\n\n# [Hipótesis para proporciones]{style=\"color: white;\"} {data-background-color=\"#0C3547\"}\n\n## Test para proporciones {style=\"font-size: 0.8em;\"}\n\n- además de las inferencias con medidas de tendencia central (como promedios), es posible también realizar inferencia sobre porcentajes/proporciones, ej:\n\n  - El 20% de l_s chilen_s asiste a la educación superior (hipótesis puntual)\n\n  - Los hombres y las mujeres tienen un distinto porcentaje de acceso a la educación superior (hipótesis de diferencia)\n\n  - Las mujeres asisten más a la educación superior que los hombres (hipótesis direccional)\n\n## Datos {style=\"font-size: 1.2em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstargazer(as.data.frame(casen2022_inf), type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=========================================================\nStatistic   N       Mean      St. Dev.    Min     Max    \n---------------------------------------------------------\nsalario   54,756 680,138.000 645,405.500 8,000 25,000,000\nsexo      57,530    1.445       0.497      1       2     \neducacion 57,530   10.350       2.245      1       15    \n---------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n## {style=\"font-size: 0.8em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrq(casen2022_inf$educacion)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ne6a_no_asiste. ¿Cuál es el nivel educacional más alto al cual asistió? (x) <numeric> \n# total N=57530 valid N=57530 mean=10.35 sd=2.25\n\nValue |                                                             Label\n-------------------------------------------------------------------------\n    1 |                                                  1. Nunca asistió\n    2 |                                                      2. Sala cuna\n    3 |                    3. Jardín Infantil (Medio menor y Medio mayor)\n    4 |       4. Prekínder / Kínder (Transición menor y Transición Mayor)\n    5 |                               5. Educación Especial (Diferencial)\n    6 |                      6. Primaria o Preparatoria (Sistema antiguo)\n    7 |                                               7. Educación Básica\n    8 |                                  8. Humanidades (Sistema Antiguo)\n    9 |                           9. Educación Media Científico-Humanista\n   10 | 10. Técnica, Comercial, Industrial o Normalista (Sistema Antiguo)\n   11 |                           11. Educación Media Técnica Profesional\n   12 |                  12. Técnico Nivel Superior (Carreras 1 a 3 años)\n   13 |                           13. Profesional (Carreras 4 o más años)\n   14 |                                           14. Magíster o maestría\n   15 |                                                     15. Doctorado\n <NA> |                                                              <NA>\n\nValue |     N | Raw % | Valid % | Cum. %\n----------------------------------------\n    1 |   242 |  0.42 |    0.42 |   0.42\n    2 |     0 |  0.00 |    0.00 |   0.42\n    3 |     3 |  0.01 |    0.01 |   0.43\n    4 |     4 |  0.01 |    0.01 |   0.43\n    5 |    73 |  0.13 |    0.13 |   0.56\n    6 |   472 |  0.82 |    0.82 |   1.38\n    7 |  7728 | 13.43 |   13.43 |  14.81\n    8 |   348 |  0.60 |    0.60 |  15.42\n    9 | 18879 | 32.82 |   32.82 |  48.23\n   10 |   280 |  0.49 |    0.49 |  48.72\n   11 |  7457 | 12.96 |   12.96 |  61.68\n   12 |  7623 | 13.25 |   13.25 |  74.93\n   13 | 13166 | 22.89 |   22.89 |  97.82\n   14 |  1098 |  1.91 |    1.91 |  99.73\n   15 |   157 |  0.27 |    0.27 | 100.00\n <NA> |     0 |  0.00 |    <NA> |   <NA>\n```\n\n\n:::\n:::\n\n\n## Variable ed. universitaria {style=\"font-size: 0.85em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncasen2022_inf$educ_sup <- rec(casen2022_inf$educacion, rec = \"1:12=0;13:15=1\", val.labels = c(\"Menos que universitaria\", \"Universitaria o más\"))\nfrq(casen2022_inf$educ_sup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ne6a_no_asiste. ¿Cuál es el nivel educacional más alto al cual asistió? (x) <numeric> \n# total N=57530 valid N=57530 mean=0.25 sd=0.43\n\nValue |                   Label |     N | Raw % | Valid % | Cum. %\n------------------------------------------------------------------\n    0 | Menos que universitaria | 43109 | 74.93 |   74.93 |  74.93\n    1 |     Universitaria o más | 14421 | 25.07 |   25.07 | 100.00\n <NA> |                    <NA> |     0 |  0.00 |    <NA> |   <NA>\n```\n\n\n:::\n:::\n\n\n## {style=\"font-size: 0.8em;\"}\n\n:::: {.columns}\n::: {.column width=\"55%\" style=\"font-size: 0.8em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sjPlot)\ncasen2022_inf %>%\n  sjtab(educ_sup, sexo,\n  show.col.prc = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n <tr>\n <th style=\"border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;\" rowspan=\"2\">e6a_no_asiste. ¿Cuál<br>es el nivel<br>educacional más alto<br>al cual asistió?</th>\n <th style=\"border-top:double; text-align:center; font-style:italic; font-weight:normal;\" colspan=\"2\">Sexo</th>\n <th style=\"border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; \" rowspan=\"2\">Total</th>\n </tr>\n \n<tr>\n <td style=\"border-bottom:1px solid; text-align:center; padding:0.2cm;\">1. Hombre</td>\n <td style=\"border-bottom:1px solid; text-align:center; padding:0.2cm;\">2. Mujer</td>\n </tr>\n \n<tr> \n<td style=\"padding:0.2cm;  text-align:left; vertical-align:middle;\">Menos que<br>universitaria</td>\n<td style=\"padding:0.2cm; text-align:center; \"><span style=\"color:black;\">25102</span><br><span style=\"color:#339933;\">78.6&nbsp;&#37;</span></td>\n<td style=\"padding:0.2cm; text-align:center; \"><span style=\"color:black;\">18007</span><br><span style=\"color:#339933;\">70.3&nbsp;&#37;</span></td>\n<td style=\"padding:0.2cm; text-align:center;  \"><span style=\"color:black;\">43109</span><br><span style=\"color:#339933;\">74.9&nbsp;&#37;</span></td> \n</tr>\n \n<tr> \n<td style=\"padding:0.2cm;  text-align:left; vertical-align:middle;\">Universitaria o más</td>\n<td style=\"padding:0.2cm; text-align:center; \"><span style=\"color:black;\">6818</span><br><span style=\"color:#339933;\">21.4&nbsp;&#37;</span></td>\n<td style=\"padding:0.2cm; text-align:center; \"><span style=\"color:black;\">7603</span><br><span style=\"color:#339933;\">29.7&nbsp;&#37;</span></td>\n<td style=\"padding:0.2cm; text-align:center;  \"><span style=\"color:black;\">14421</span><br><span style=\"color:#339933;\">25.1&nbsp;&#37;</span></td> \n</tr>\n \n<tr> \n<td style=\"padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;\">Total</td>\n<td style=\"padding:0.2cm; text-align:center;   border-bottom:double;\"><span style=\"color:black;\">31920</span><br><span style=\"color:#339933;\">100&nbsp;&#37;</span></td>\n<td style=\"padding:0.2cm; text-align:center;   border-bottom:double;\"><span style=\"color:black;\">25610</span><br><span style=\"color:#339933;\">100&nbsp;&#37;</span></td>\n<td style=\"padding:0.2cm; text-align:center;   border-bottom:double;\"><span style=\"color:black;\">57530</span><br><span style=\"color:#339933;\">100&nbsp;&#37;</span></td> \n</tr>\n<td style=\"text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;\" colspan=\"4\">&chi;<sup>2</sup>=524.222 &middot; df=1 &middot; &phi=0.095 &middot; p=0.000</td> \n</tr>\n \n</table>\n`````\n:::\n:::\n\n\n:::\n\n::: {.column .fragment width=\"45%\"}\n\n<br>\n\n$p_m - p_h=0.297-0.214=0.083$\n\n<br>\n\n\nEl porcentaje de mujeres con educación universitaria es [8.3%]{style=\"color: #c0392b;\"} superior en las mujeres\n\n<br>\n\n::: {.content-box-red style=\"text-align: center;\"}\n[¿Es significativa esta diferencia?]{style=\"color: #ffffff;\"}\n:::\n\n:::\n::::\n\n<!--\nver: http://www.sthda.com/english/wiki/two-proportions-z-test-in-r\n-->\n\n## Diferencias entre proporciones {style=\"font-size: 0.8em;\"}\n\n1. Establecer las hipótesis (y definir si son o no direccionales)\n\n2. Calcular error estándar\n\n3. Estimar estadístico de prueba (Z)\n\n4. Establecer valor crítico de la prueba (de acuerdo a un cierto nivel de confianza)\n\n5. Contraste e interpretación\n\n## Diferencias entre proporciones {style=\"font-size: 0.8em;\"}\n### 1. Establecer las hipótesis\n\n¿Existen diferencias entre el porcentaje de mujeres y hombres con nivel educacional universitario?\n\n$$H_{a}: p_{mujeres} -  p_{hombres} \\neq 0$$\n$$H_{0}: p_{mujeres} -  p_{hombres}= 0$$\n\n## Diferencias entre proporciones {style=\"font-size: 0.8em;\"}\n### 2. Cálculo de error estándar (SE)\n\nEl SE para una proporción es:\n\n$$SE_p=\\sqrt{\\frac{p(1-p)}{n}}$$\n\nY para diferencia de proporciones:\n\n$$SE_{p_1 - p_2}=\\sqrt{\\frac{p_1(1-p_1)}{n_1}+\\frac{p_2(1-p_2)}{n_2}}$$\n\n<!--\nhttps://online.stat.psu.edu/stat415/lesson/9/9.4\n-->\n\n## Estimación de error estándar {style=\"font-size: 0.8em;\"}\n\n$$\n\\begin{align*}\nSE_{p_a - p_b}&=\\sqrt{\\frac{p_a(1-p_a)}{n_a}+\\frac{p_b(1-p_b)}{n_b}} \\\\\\\\\nSE_{p_m - p_h}&=\\sqrt{\\frac{0.297(1-0.297)}{7603}+\\frac{0.214(1-0.214)}{6818}} \\\\\\\\\nSE_{p_m - p_h}&=\\sqrt{\\frac{0.209}{7603}+\\frac{0.168}{6818}}=\\sqrt{0.0000275+0.0000246}=0.00722\n\\end{align*}\n$$\n\n## Diferencias entre proporciones {style=\"font-size: 0.8em;\"}\n### 3. Cálculo de estadístico de prueba\n\nPara diferencia de proporciones se utiliza la prueba $Z$\n\n$$Z_{est}=\\frac{p_m -  p_h}{SE_{p_m -p_h}}=\\frac{0.083}{0.0072}=11.528$$\n\n## Diferencias entre proporciones {style=\"font-size: 0.8em;\"}\n### 4. Establecer valor crítico de prueba\n\nY comparamos este valor con el Z crítico para un $\\alpha=0.05$ de dos colas (porque es hipótesis de diferencia)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(p = .05/2, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n\n## Diferencias entre proporciones {style=\"font-size: 0.8em;\"}\n### 5. Interpretación\n\nEn este caso, nuestro $Z_{est}=11.528 > Z_{crít}=1.96$, por lo tanto se rechaza $H_0$\n\nLa proporción de universitarias y universitarios es diferente, con un 95% de confianza\n\n## Diferencias entre proporciones {style=\"font-size: 0.8em;\"}\n\n### (6). Construcción intervalo de confianza\n\nPara obtener un intervalo de confianza, a la diferencia de proporciones se le suman/restan errores estándar multiplicados por el valor Z crítico según nivel de confianza, en este caso $\\alpha/2=0.05/2$ (prueba de dos colas)\n\n$$\n\\begin{align*}\np_1 - p_2 &\\pm Z_{crit_{\\alpha/2}}*SE_{p_a - p_b} \\\\\n0.297-0.214 &\\pm1.96*0.00722\\\\\n0.083&\\pm 0.0142 \\\\\n\\end{align*}\n$$\n\n$$CI[0.07;0.09]$$\n\nPodemos entonces decir con un 95% de confianza que la diferencia de proporción de universitari_s entre hombres y mujeres se encuentra entre un 7% y un 9%\n\n\n## Estimación directamente en R con `prop.test` {style=\"font-size: 0.7em;\"}\n\n:::: {.columns}\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_dif <- prop.test(x = c(7603, 6818), n = c(25610, 31920))\nprop_dif\n```\n:::\n\n\n```\n2-sample test for equality of proportions with continuity\n\tcorrection\n\ndata:  c(7603, 6818) out of c(25610, 31920)\nX-squared = 524.22, df = 1, p-value < 0.00000000000000022\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.07606640 0.09049306\nsample estimates:\n   prop 1    prop 2\n0.2968762 0.2135965\n```\n\n:::\n\n::: {.column .fragment width=\"45%\"}\n\nDos cosas importantes para reporte de este output:\n\n- probabilidad de error p: si es menor al nivel de error especificado ( $\\alpha$), se rechaza la hipótesis nula. En este caso, las diferencias entre grupos son significativamente distintas de cero.\n\n- el intervalo de confianza: rango de valores con un 95% de confianza para la diferencia estimada.\n\n:::\n::::\n\n## Hipótesis direccionales de proporciones {style=\"font-size: 0.8em;\"}\n### Paso 1: hipótesis\n\n¿Es superior la proporción de mujeres con educación superior?\n\nEn este caso,\n\n$$H_{0}: p_{mujeres} \\leq  p_{hombres}$$\n\nEn relación a la siguiente hipótesis alternativa:\n\n$$H_{a}: p_{mujeres} \\gt  p_{hombres}$$\n\n## Hipótesis direccionales de proporciones {style=\"font-size: 0.8em;\"}\n### Paso 2 (SE) y 3 (estadístico de prueba) igual que para hipótesis no direccionales\n\n## Hipótesis direccionales de proporciones {style=\"font-size: 0.8em;\"}\n### Paso 4: Valor crítico de prueba\n\nValor crítico de Z para una cola\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(p = .05, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.644854\n```\n\n\n:::\n:::\n\n\n## Hipótesis direccionales de proporciones {style=\"font-size: 0.8em;\"}\n### Paso 5: Interpretación\n\nValor crítico se compara con el valor estimado de Z para la diferencia de proporciones,\n\nEn este caso, $$Z_{est}=11.528 \\gt Z_{crít}=1.644$$\n\nPor lo tanto se rechaza $H_0$, con un 95% de confianza podemos decir que la proporción de mujeres universitarias es mayor en mujeres que en hombres.\n\n## Estimación directamente en R con `prop.test` {style=\"font-size: 0.7em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_greater <- prop.test(x = c(7603, 6818), n = c(25610, 31920), alternative = \"greater\")\nprop_greater\n```\n:::\n\n\n```\n\t2-sample test for equality of proportions with continuity\n\tcorrection\n\ndata:  c(7603, 6818) out of c(25610, 31920)\nX-squared = 524.22, df = 1, p-value < 0.00000000000000022\nalternative hypothesis: greater\n95 percent confidence interval:\n 0.07722045 1.00000000\nsample estimates:\n   prop 1    prop 2\n0.2968762 0.2135965\n```\n\n## Visualización interactiva: prueba de diferencia de proporciones {style=\"font-size: 0.8em;\"}\n\n```{=html}\n<div class=\"pp-widget\" style=\"font-size: 0.5em; color: #222; line-height: 1.4;\">\n  <div style=\"display:flex; gap:2em; flex-wrap:wrap; align-items:center; margin-bottom:0.4em;\">\n    <label>p1: <input type=\"range\" id=\"pp-p1\" min=\"0.01\" max=\"0.99\" step=\"0.001\" value=\"0.297\" style=\"vertical-align:middle;\"> <span id=\"pp-p1-val\">0.297</span></label>\n    <label>n1: <input type=\"range\" id=\"pp-n1\" min=\"10\" max=\"30000\" step=\"1\" value=\"7603\" style=\"vertical-align:middle;\"> <span id=\"pp-n1-val\">7603</span></label>\n    <label>p2: <input type=\"range\" id=\"pp-p2\" min=\"0.01\" max=\"0.99\" step=\"0.001\" value=\"0.214\" style=\"vertical-align:middle;\"> <span id=\"pp-p2-val\">0.214</span></label>\n    <label>n2: <input type=\"range\" id=\"pp-n2\" min=\"10\" max=\"30000\" step=\"1\" value=\"6818\" style=\"vertical-align:middle;\"> <span id=\"pp-n2-val\">6818</span></label>\n    <label>&alpha; (significancia): <input type=\"range\" id=\"pp-alpha\" min=\"0.001\" max=\"0.5\" step=\"0.001\" value=\"0.05\" style=\"vertical-align:middle;\"> <span id=\"pp-alpha-val\">0.05</span></label>\n  </div>\n  <div style=\"margin-bottom:0.4em;\">\n    <label style=\"margin-right:1.5em;\"><input type=\"radio\" name=\"pp-tail\" value=\"two\" checked> H1: p1 &ne; p2 (dos colas)</label>\n    <label style=\"margin-right:1.5em;\"><input type=\"radio\" name=\"pp-tail\" value=\"less\"> H1: p1 &lt; p2</label>\n    <label><input type=\"radio\" name=\"pp-tail\" value=\"greater\"> H1: p1 &gt; p2</label>\n  </div>\n  <div id=\"pp-plot\" style=\"width:100%; height:420px;\"></div>\n</div>\n\n<script src=\"https://cdn.plot.ly/plotly-2.32.0.min.js\"></script>\n<script>\n(function() {\n  function erf(x) {\n    var sign = x >= 0 ? 1 : -1;\n    x = Math.abs(x);\n    var a1 = 0.254829592, a2 = -0.284496736, a3 = 1.421413741,\n        a4 = -1.453152027, a5 = 1.061405429, p = 0.3275911;\n    var t = 1 / (1 + p * x);\n    var y = 1 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * Math.exp(-x * x);\n    return sign * y;\n  }\n\n  function normCDF(z) { return 0.5 * (1 + erf(z / Math.SQRT2)); }\n  function normPDF(z) { return Math.exp(-z * z / 2) / Math.sqrt(2 * Math.PI); }\n  function upperTail(z) { return 1 - normCDF(z); }\n\n  function findCritZ(targetUpper) {\n    var lo = 0, hi = 10;\n    for (var i = 0; i < 100; i++) {\n      var mid = (lo + hi) / 2;\n      if (upperTail(mid) > targetUpper) lo = mid; else hi = mid;\n    }\n    return (lo + hi) / 2;\n  }\n\n  var elP1 = document.getElementById('pp-p1');\n  var elN1 = document.getElementById('pp-n1');\n  var elP2 = document.getElementById('pp-p2');\n  var elN2 = document.getElementById('pp-n2');\n  var elAlpha = document.getElementById('pp-alpha');\n  var elP1Val = document.getElementById('pp-p1-val');\n  var elN1Val = document.getElementById('pp-n1-val');\n  var elP2Val = document.getElementById('pp-p2-val');\n  var elN2Val = document.getElementById('pp-n2-val');\n  var elAlphaVal = document.getElementById('pp-alpha-val');\n  var plotDiv = document.getElementById('pp-plot');\n\n  function getTail() {\n    var radios = document.getElementsByName('pp-tail');\n    for (var i = 0; i < radios.length; i++) if (radios[i].checked) return radios[i].value;\n    return 'two';\n  }\n\n  function render() {\n    var p1 = parseFloat(elP1.value);\n    var n1 = parseInt(elN1.value, 10);\n    var p2 = parseFloat(elP2.value);\n    var n2 = parseInt(elN2.value, 10);\n    var alpha = parseFloat(elAlpha.value);\n    var tail = getTail();\n    elP1Val.textContent = p1.toFixed(3);\n    elN1Val.textContent = n1;\n    elP2Val.textContent = p2.toFixed(3);\n    elN2Val.textContent = n2;\n    elAlphaVal.textContent = alpha.toFixed(3);\n\n    var se = Math.sqrt(p1 * (1 - p1) / n1 + p2 * (1 - p2) / n2);\n    var zest = (p1 - p2) / se;\n\n    var xs = [], ys = [];\n    for (var x = -5; x <= 5; x += 0.03) { xs.push(x); ys.push(normPDF(x)); }\n\n    var critPos, critNeg, rejectRegions = [], pVal, reject, comparisonText;\n\n    if (tail === 'two') {\n      critPos = findCritZ(alpha / 2);\n      critNeg = -critPos;\n      rejectRegions.push([-5, critNeg]);\n      rejectRegions.push([critPos, 5]);\n      pVal = 2 * upperTail(Math.abs(zest));\n      reject = Math.abs(zest) >= critPos;\n      comparisonText = '|Z| = ' + Math.abs(zest).toFixed(3) + (reject ? ' ≥ ' : ' < ') + critPos.toFixed(3);\n    } else if (tail === 'greater') {\n      critPos = findCritZ(alpha);\n      critNeg = null;\n      rejectRegions.push([critPos, 5]);\n      pVal = upperTail(zest);\n      reject = zest >= critPos;\n      comparisonText = 'Z = ' + zest.toFixed(3) + (reject ? ' ≥ ' : ' < ') + critPos.toFixed(3);\n    } else {\n      critNeg = -findCritZ(alpha);\n      critPos = null;\n      rejectRegions.push([-5, critNeg]);\n      pVal = normCDF(zest);\n      reject = zest <= critNeg;\n      comparisonText = 'Z = ' + zest.toFixed(3) + (reject ? ' ≤ ' : ' > ') + critNeg.toFixed(3);\n    }\n\n    var traces = [{\n      x: xs, y: ys, type: 'scatter', mode: 'lines',\n      line: { color: '#2c7fb8', width: 2 }, name: 'distribución Z', hoverinfo: 'skip'\n    }];\n\n    rejectRegions.forEach(function(region) {\n      var rx = [], ry = [];\n      for (var x = region[0]; x <= region[1]; x += 0.03) { rx.push(x); ry.push(normPDF(x)); }\n      traces.push({\n        x: rx, y: ry, type: 'scatter', mode: 'lines',\n        fill: 'tozeroy', fillcolor: 'rgba(34,139,34,0.35)',\n        line: { color: 'rgba(34,139,34,0.6)', width: 1 },\n        name: 'zona de rechazo', hoverinfo: 'skip', showlegend: false\n      });\n    });\n\n    var shapes = [];\n    var maxY = Math.max.apply(null, ys) * 1.15;\n    [critPos, critNeg].forEach(function(cv) {\n      if (cv === null) return;\n      shapes.push({\n        type: 'line', x0: cv, x1: cv, y0: 0, y1: maxY,\n        line: { color: '#d62728', width: 2, dash: 'dash' }\n      });\n    });\n    var zClamped = Math.max(-5, Math.min(5, zest));\n    var zWasClamped = zClamped !== zest;\n    shapes.push({\n      type: 'line', x0: zClamped, x1: zClamped, y0: 0, y1: maxY,\n      line: { color: '#111', width: 2, dash: 'dash' }\n    });\n\n    var annotations = [{\n      x: 0, y: maxY, xref: 'x', yref: 'y', showarrow: false, yanchor: 'bottom',\n      text: 'SE = ' + se.toFixed(4) + ',  α = ' + alpha.toFixed(3),\n      font: { size: 13 }\n    }, {\n      x: (critNeg !== null ? critNeg : critPos), y: maxY * 0.9, xref: 'x', yref: 'y',\n      showarrow: false, font: { size: 11, color: '#d62728' },\n      text: 'Z crítico = ' + (critPos !== null ? critPos.toFixed(3) : critNeg.toFixed(3))\n    }, {\n      x: zClamped, y: maxY * 0.55, xref: 'x', yref: 'y', showarrow: false,\n      font: { size: 11, color: '#111' },\n      xanchor: zWasClamped ? (zClamped >= 0 ? 'right' : 'left') : (zClamped >= 0 ? 'left' : 'right'),\n      text: 'Z = ' + zest.toFixed(3)\n    }, {\n      x: -3.9, y: maxY * 0.75, xref: 'x', yref: 'y', showarrow: false,\n      font: { size: 20, color: reject ? '#1a7a1a' : '#c0392b' },\n      text: '<b>' + (reject ? 'Se rechaza H0' : 'No se rechaza H0') + '</b>'\n    }, {\n      x: 3.9, y: maxY * 0.75, xref: 'x', yref: 'y', showarrow: false,\n      font: { size: 18, color: reject ? '#1a7a1a' : '#c0392b' },\n      text: '<b>' + comparisonText + '<br>p = ' + pVal.toFixed(4) + '</b>'\n    }];\n\n    var layout = {\n      margin: { l: 40, r: 20, t: 25, b: 30 },\n      xaxis: { range: [-5, 5], title: 'Z' },\n      yaxis: { range: [0, maxY], title: 'densidad' },\n      shapes: shapes,\n      annotations: annotations,\n      showlegend: false\n    };\n\n    Plotly.react(plotDiv, traces, layout, { responsive: true, displayModeBar: false });\n  }\n\n  elP1.addEventListener('input', render);\n  elN1.addEventListener('input', render);\n  elP2.addEventListener('input', render);\n  elN2.addEventListener('input', render);\n  elAlpha.addEventListener('input', render);\n  var radios = document.getElementsByName('pp-tail');\n  for (var i = 0; i < radios.length; i++) radios[i].addEventListener('change', render);\n\n  render();\n})();\n</script>\n```\n\n## Resumen de inferencia \n\n- La inferencia estadística permite sacar conclusiones sobre una población a partir de una muestra.\n- Se basa en un contraste de hipótesis, que puede ser direccional o no direccional.\n- La lógica de falsación busca rechazar la hipótesis nula, y se basa en el cálculo de un estadístico de prueba y su comparación con un valor crítico.\n\n\n\n# {.hide-logo data-background-color=\"#0C3547\"}\n\n<br>\n\n::::: columns\n::: {.column width=\"30%\"}\n\n<br>\n\n![](img/logo-correlacional-transp.png){width=\"100%\" fig-align=\"right\"}\n:::\n\n:::{.column width=\"2%\"}\n\n:::\n\n::: {.column style=\"width: 65%; font-size: 25px; text-align: right; margin: 0 auto;\"}\n\n<br>\n\n### [Estadística Correlacional]{style=\"font-size: 2em; color: white;\"}\n\n::: {style=\"border-top: 1px solid white; margin: 0.3em 0;\"}\n:::\n\n[Inferencia, asociación, y reporte]{style=\"font-size: 1.5em; color: #dfc117;\"}\n\n[Juan Carlos Castillo]{style=\"font-size: 1em; color: white;\"}\\\n[Sociología FACSO - UChile]{style=\"font-size: 1em; color: white;\"}\\\n[2do Sem 2026]{style=\"font-size: 1em; color: white;\"}\n\n[correlacional.metodos-facso.org](https://correlacional.metodos-facso.org)\n\n:::\n:::::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}