<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Estadística Correlacional">

<title>Intervalos de Confianza y Test de hipótesis – Estadística Correlacional</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-59898bd1c6b9d2bb783127feaa000c76.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-2cdf77136bd6d29f4993552638611836.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<link href="../site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="../site_libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Intervalos de Confianza y Test de hipótesis – Estadística Correlacional">
<meta property="og:description" content="">
<meta property="og:image" content="https://correlacional.metodos-facso.org/assignment/images/logo.png">
<meta property="og:site_name" content="Estadística Correlacional">
<meta property="og:locale" content="es">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Estadística Correlacional</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../news/index.html"> 
<span class="menu-text">Informaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Planificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../content/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignment/index.html"> 
<span class="menu-text">Prácticos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource/index.html"> 
<span class="menu-text">Recursos</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#objetivo-de-la-práctica" id="toc-objetivo-de-la-práctica" class="nav-link active" data-scroll-target="#objetivo-de-la-práctica">Objetivo de la práctica</a></li>
  <li><a href="#repaso-intervalos-de-confianza" id="toc-repaso-intervalos-de-confianza" class="nav-link" data-scroll-target="#repaso-intervalos-de-confianza"><span class="header-section-number">1</span> Repaso intervalos de confianza</a></li>
  <li><a href="#test-de-hipótesis" id="toc-test-de-hipótesis" class="nav-link" data-scroll-target="#test-de-hipótesis"><span class="header-section-number">2</span> Test de hipótesis</a>
  <ul class="collapse">
  <li><a href="#los-cinco-pasos-para-la-inferencia-estadística" id="toc-los-cinco-pasos-para-la-inferencia-estadística" class="nav-link" data-scroll-target="#los-cinco-pasos-para-la-inferencia-estadística"><span class="header-section-number">2.1</span> Los cinco pasos para la inferencia estadística</a></li>
  <li><a href="#preparación-datos" id="toc-preparación-datos" class="nav-link" data-scroll-target="#preparación-datos"><span class="header-section-number">2.2</span> Preparación datos</a></li>
  <li><a href="#recordemos" id="toc-recordemos" class="nav-link" data-scroll-target="#recordemos"><span class="header-section-number">2.3</span> Recordemos…</a></li>
  <li><a href="#ejercicio-1" id="toc-ejercicio-1" class="nav-link" data-scroll-target="#ejercicio-1"><span class="header-section-number">2.4</span> Ejercicio 1</a></li>
  <li><a href="#ejercicio-autónomo" id="toc-ejercicio-autónomo" class="nav-link" data-scroll-target="#ejercicio-autónomo"><span class="header-section-number">2.5</span> Ejercicio autónomo</a></li>
  </ul></li>
  <li><a href="#repaso" id="toc-repaso" class="nav-link" data-scroll-target="#repaso"><span class="header-section-number">3</span> Repaso</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><h1 class="title display-7">Intervalos de Confianza y Test de hipótesis</h1></header>

<header id="title-block-header">


<div class="date-block bg-assignment text-white p-2">
  <p class="date">Sesión del miércoles, 19 de agosto de 2026</p>
</div>
</header>


<style>
/* Texto escrito entre comillas invertidas */
:not(pre) > code {
  color: #00695c !important;
  background-color: #eef7f6 !important;
  padding: 0.1em 0.3em;
  border-radius: 4px;
}

/* Resultados producidos por R */
.cell-output pre {
  color: #17233a !important;
  background-color: #e8f5f3 !important;
  border-left: 4px solid #009688 !important;
  padding: 0.8em 1em !important;
}

/* Evita que el tema cambie el color del texto de las salidas */
.cell-output pre code {
  color: #17233a !important;
  background-color: transparent !important;
}

/* Comentarios (#) dentro de los chunks de código */
code span.co {
  color: #5c7a2c !important;
}

/* Tamaño de fuente de los chunks de código */
div.sourceCode pre code {
  font-size: 1.15em;
}
</style>
<section id="objetivo-de-la-práctica" class="level1 unnumbered">
<h1 class="unnumbered">Objetivo de la práctica</h1>
<p>El objetivo de esta guía práctica es repasar intervalos de confianza, y además aplicar las herramientas teóricas y prácticas aprendidas hasta el momento para realizar pruebas de hipótesis, tanto para diferencias de medias como direccionales utilizando la prueba <strong><em>t</em></strong>.</p>
<p>En detalle, en el práctico de hoy veremos:</p>
<ol type="1">
<li><p>Cálculo e interpretación de intervalos de confianza</p></li>
<li><p>Formular hipótesis, realizar una prueba t en R e interpretar sus principales resultados.</p></li>
</ol>
</section>
<section id="repaso-intervalos-de-confianza" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Repaso intervalos de confianza</h1>
<p>Recordemos que un intervalo de confianza es <strong>la mejor estimación del rango de un estadístico en la población (parámetro poblacional) con una muestra aleatoria</strong></p>
<p>El nivel de confianza describe qué tan frecuentemente este procedimiento produciría intervalos que contienen la verdadera media poblacional si repitiéramos muchas veces el muestreo.</p>
<p><img src="https://correlacional.netlify.app/slides/img/intervalos.png" class="img-fluid"></p>
<p>A modo de repasar el contenido de intervalos a confianza, resolveremos el ejercicio autónomo de la última sesión práctica. Trabajaremos con el conjunto de datos <code>Galton</code>, incluido en el paquete <code>HistData</code>, que contiene las estaturas de 928 hijos e hijas adultos recopiladas por Francis Galton en 1886.</p>
<p>Este es, de hecho, el conjunto de datos histórico que dio origen al estudio de la curva normal aplicada a variables biológicas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"pacman"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>) <span class="co"># Si no está instalado, instala el paquete</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(HistData)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Galton"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Galton) <span class="co"># revisar las variables disponibles: "parent" y "child"</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "parent" "child" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>altura <span class="ot">&lt;-</span> Galton<span class="sc">$</span>child <span class="co"># creamos el vector con la variable de interés</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>La función <code>p_load</code> del paquete <code>pacman</code> simplifica el proceso de carga de paquetes, ya que se pueden cargar varios paquetes a la vez y, en caso de que alguno de esos paquetes no esté previamente instalado, p_load lo reconoce e instala</p>
</div>
</div>
<p>La unidad de medida de la variable se encuentra en pulgadas.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Los # en el código</strong></p>
<p>En este código y siguientes aparecen varios #, que son una función de comentarios en R. Todo lo escrito después de # es un comentario para explicar el código o texto. R no lo ejecuta.</p>
<p>Pueden servir como herramientas para tomar apuntes mientras se trabaja en el código</p>
</div>
</div>
<ol type="1">
<li>Calcule y describa la distribución</li>
</ol>
<ul>
<li>Obtenga la media y desviación estándar de la estatura.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span> <span class="fu">mean</span>(Galton<span class="sc">$</span>child)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>desv_estandar <span class="ot">&lt;-</span> <span class="fu">sd</span>(Galton<span class="sc">$</span>child)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>media</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 68.08847</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>desv_estandar</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.517941</code></pre>
</div>
</div>
<ul>
<li>Visualice la distribución en un histograma</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Galton<span class="sc">$</span>child,<span class="at">main=</span><span class="st">"Histograma del Vector"</span>,<span class="at">xlab=</span><span class="st">"Valor"</span>,<span class="at">ylab=</span><span class="st">"Frecuencia"</span>,<span class="at">col=</span><span class="st">"cyan4"</span>,<span class="at">border=</span><span class="st">"black"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-practico_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li>Estandarice los datos (puntajes Z)</li>
</ol>
<ul>
<li>Transforme la variable a puntajes Z</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>z_scores <span class="ot">&lt;-</span> (Galton<span class="sc">$</span>child <span class="sc">-</span> media) <span class="sc">/</span> desv_estandar <span class="co"># aplicamos la fórmula del puntaje Z a la variable child dentro de la base de datos Galton</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Muestre los primeros 6 valores (<code>head()</code>).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(z_scores)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.537180 -2.537180 -2.537180 -2.537180 -2.537180 -2.338605</code></pre>
</div>
</div>
<ul>
<li>Muestre también los últimos 6 valores (<code>tail()</code>).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(z_scores)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.228618 2.228618 2.228618 2.228618 2.228618 2.228618</code></pre>
</div>
</div>
<ul>
<li>¿Cuál es el máximo puntaje Z y el mínimo puntaje Z? ¿A qué estatura corresponden?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>max <span class="ot">&lt;-</span> <span class="fu">max</span>(z_scores)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>max</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.228618</code></pre>
</div>
</div>
<p>El máximo puntaje Z corresponde a 2.23. Esto significa que el hijo o hija más alto se encuentra 2.23 desviaciones estándar sobre el promedio</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>min <span class="ot">&lt;-</span> <span class="fu">min</span>(z_scores)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>min</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.53718</code></pre>
</div>
</div>
<p>El mínimo puntaje corresponde a -2.53, lo que se entiende como que el hijo o hija más bajo se encuentra -2.53 desviaciones estándar bajo el promedio</p>
<p><strong>Obteniendo valores observados a partir de puntajes Z</strong></p>
<p>En el ejericio anterior, calculamos los puntajes Z para valores específicos de la variable estatura, en específico el mínimo y máximo. Esto nos permitió conocer cuántas desviaciones estándar se encontraba cada valor respecto de la media.</p>
<p>Tambiés es posible hacer el ejercicio inverso, es decir, <strong>calcular el valor observado a partir de un puntaje Z</strong>. Para esto, utilizaremos la fórmula del puntaje Z y despejaremos el valor observado.</p>
<p>Recordemos que la fórmula del puntaje Z es: <span class="math display">\[
Z = \frac{X - \mu}{\sigma}
\]</span></p>
<p>Por lo tanto,si queremos obtener el valor observado, debemos despejar X de la fórmula:</p>
<p><span class="math display">\[
X = Z \cdot \sigma + \mu
\]</span></p>
<p>Para verificar, veamos que pasa con el valor observado del puntaje Z máximo, que es 2.23:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(max <span class="sc">*</span> desv_estandar) <span class="sc">+</span> media</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 73.7</code></pre>
</div>
</div>
<p>Por lo tanto conociendo Z también podemos volver a valores observados de la distribución original … que en realidad ya conocemos, porque tenemos la variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(Galton<span class="sc">$</span>child) <span class="co"># valor máximo de la variable original</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 73.7</code></pre>
</div>
</div>
<p>Pero, lo interesante es que podemos hacer esto mismo para un valor teórico de Z, que por ejemplo podría ser el límite superior de un intervalo de confianza al 99% (2.58). Entonces, si queremos saber cuál es el valor observado que corresponde a un puntaje Z de 2.58, podemos hacer lo siguiente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>(<span class="fl">2.58</span> <span class="sc">*</span> desv_estandar) <span class="sc">+</span> media</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 74.58476</code></pre>
</div>
</div>
<p>Por lo tanto, el valor observado que corresponde a un puntaje Z de 2.58 es de 74.58 pulgadas, lo que significa que un 0,5% de los hijos e hijas miden más que este valor (ya que el 99% de la distribución se encuentra entre desviaciones estándar de la media, y el restante 1% se divide en 0.5% por cada cola de la distribución).</p>
<ol type="1">
<li>Calcule el error estándar de la variable</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recordemos que la fórmula del error estándar es: <span class="math display">\[
SE = \frac{s}{\sqrt{n}}
\]</span></p>
<p>Donde:</p>
<p><span class="math inline">\(s\)</span> es la desviación estándar de la muestra. <span class="math inline">\(n\)</span> es el número de casos de la muestra.</p>
</div>
</div>
<p>Para nuestro caso, reemplazamos los valores en la fórmula:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>n_vector <span class="ot">&lt;-</span> <span class="fu">length</span>(Galton<span class="sc">$</span>child)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> desv_estandar <span class="sc">/</span> <span class="fu">sqrt</span>(n_vector)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>se</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08265547</code></pre>
</div>
</div>
<p>Esto quiere decir que el error estándar estimado de la distribución de medias muestrales es 0,083: nos indica cuánto tienden a variar las medias entre posibles muestras de igual tamaño.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>El error estándar es una estimación de la <strong>desviación estandar de los promedios de varias muestras</strong> a partir de <strong>una sola muestra</strong></p>
</div>
</div>
<ol start="4" type="1">
<li>Calcule el intervalo de confianza para la media</li>
</ol>
<ul>
<li>Estime el IC para un 95% de confianza</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Su fórmula es la siguiente:</p>
<p><span class="math display">\[
IC = \bar{x} \pm z \cdot \frac{s}{\sqrt{n}}
\]</span></p>
<p>Donde:</p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span> es la media de la muestra.</li>
<li><span class="math inline">\(z\)</span> es el valor crítico.</li>
<li><span class="math inline">\(s\)</span> es la desviación estándar de la muestra.</li>
<li><span class="math inline">\(n\)</span> es el tamaño de la muestra.</li>
<li><span class="math inline">\(\frac{s}{\sqrt{n}}\)</span> corresponde al error estándar.</li>
</ul>
</div>
</div>
<p>Recordemos que el valor crítico para un 95% de confianza es de 1.96 (<a href="https://correlacional.metodos-facso.org/assignment/01-practico.html">link al práctico anterior</a>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>lim_inf <span class="ot">&lt;-</span> media <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se <span class="co"># Limite inferior del Intervalo</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>lim_inf</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.92647</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>lim_sup <span class="ot">&lt;-</span> media <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se <span class="co"># Límite superior del Intervalo</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>lim_sup</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 68.25047</code></pre>
</div>
</div>
<p>Generamos un gráfico para visualizar de mejor manera el intervalo de confianza que construimos</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-practico_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Media muestral e intervalo de confianza del 95 %.</figcaption>
</figure>
</div>
</div>
</div>
<div style="background-color: #b71c1c; color: #ffffff; border: 1px solid #8e0000; border-radius: 6px; padding: 0.8rem 1rem;">
<p>Podemos observar que contamos con una media muestral de 68.1 como estimación puntual. Ahora, se puede decir con un 95% de confianza que la media poblacional se encuentra entre 67.93 y 68.25.</p>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>En simple: si estimamos 100 intervalos de confianza, <strong>95 de ellos contendrán la media poblacional</strong>.</p>
</div>
</div>
<ul>
<li>Estime el IC para un 99% de confianza. ¿Qué sucede con el ancho del intervalo?</li>
</ul>
<p>El puntaje para el intervalo de confianza a un 95% es 1.96. Para un intervalo de confianza al 99% es 2.58, el cual refiere a la <strong>área acumulada bajo la curva normal</strong>. Entonces, calculemos el intervalo de confianza</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>lim_inf_99 <span class="ot">&lt;-</span> media <span class="sc">-</span> <span class="fl">2.58</span> <span class="sc">*</span> se <span class="co"># Limite inferior del Intervalo</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>lim_inf_99</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.87522</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>lim_sup_99 <span class="ot">&lt;-</span> media <span class="sc">+</span> <span class="fl">2.58</span> <span class="sc">*</span> se <span class="co"># Límite superior del Intervalo</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>lim_sup_99</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 68.30172</code></pre>
</div>
</div>
<div style="background-color: #b71c1c; color: #ffffff; border: 1px solid #8e0000; border-radius: 6px; padding: 0.8rem 1rem;">
<p>Podemos observar que al calcular el IC para un 99% de confianza, el ancho del intervalo se amplía, es decir, el rango donde se puede hallar el parámetro poblacional es mayor, encontrándose entre 67.88 y 68.30</p>
</div>
<p>Recordemos que también podemos utilizar la función <code>t.test</code> para calcular el intervalo de confianza de manera mucho más rápida. Solamente debemos especificar el vector y el nivel de confianza.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Galton<span class="sc">$</span>child, <span class="at">conf.level =</span> <span class="fl">0.99</span>)<span class="sc">$</span>conf.int</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.87512 68.30182
attr(,"conf.level")
[1] 0.99</code></pre>
</div>
</div>
<p>Así, llegamos a los mismos resultados.</p>
<ol start="5" type="1">
<li>Explore el efecto del tamaño muestral</li>
</ol>
<ul>
<li>Generemos 2 submuestras aleatorias con la función <code>sample()</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>muestra_50 <span class="ot">&lt;-</span> <span class="fu">sample</span>(altura, <span class="dv">50</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>muestra_500 <span class="ot">&lt;-</span> <span class="fu">sample</span>(altura, <span class="dv">500</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>la función <code>set.seed</code> fija una semilla para que las secuencias de números “aleatorios” que produce R sean reproducibles. Es decir, asegura que otra persona que corra el mismo script obtenga los mismos resultados</p>
</div>
</div>
<ul>
<li>Calcule el error estándar y el intervalo de confianza al 95% de cada muestra ¿Qué pasa con el error estándar y el intervalo de confianza a medida que aumenta el tamaño de la muestra?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>media_50 <span class="ot">&lt;-</span> <span class="fu">mean</span>(muestra_50)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>desv_estandar_50 <span class="ot">&lt;-</span> <span class="fu">sd</span>(muestra_50)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>n_media_50 <span class="ot">&lt;-</span> <span class="fu">length</span>(muestra_50)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>se_50 <span class="ot">&lt;-</span> desv_estandar_50 <span class="sc">/</span> <span class="fu">sqrt</span>(n_media_50)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>se_50</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3390383</code></pre>
</div>
</div>
<p>Calculamos el intervalo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(muestra_50)<span class="sc">$</span>conf.int</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.25868 68.62132
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
</div>
<p>La media como estimación puntual es de 67.9, mientras que con un 95% de confianza podemos asegurar que el parámetro poblacional se encuentra entre <strong>67.26 y 68.62</strong>.</p>
<p>Ahora realicemos el mismo procedimiento con la muestra generada con 500 casos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>media_500 <span class="ot">&lt;-</span> <span class="fu">mean</span>(muestra_500)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>desv_estandar_500 <span class="ot">&lt;-</span> <span class="fu">sd</span>(muestra_500)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>n_media_500 <span class="ot">&lt;-</span> <span class="fu">length</span>(muestra_500)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>se_500 <span class="ot">&lt;-</span> desv_estandar_500 <span class="sc">/</span> <span class="fu">sqrt</span>(n_media_500)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>se_500</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1109578</code></pre>
</div>
</div>
<p>Calculamos el intervalo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(muestra_500)<span class="sc">$</span>conf.int</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.832 68.268
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
</div>
<p>Al comparar el error estándar de la muestra de 50 con la muestra de 500, podemos ver que, <strong>a medida que la muestra es más grande</strong>, <strong>el error estándar se vuelve más pequeño</strong>.</p>
<p>De la misma manera, el intervalo de la muestra de 50 casos es de 67.28 y 68.60, mientras que el de la muestra de 500 es más reducido, conteniendo valores entre el 67.83 y 68.27. Así, podemos afirmar que <strong>una muestra con mayor cantidad de casos</strong> tenderá a entregar intervalos más pequeños, es decir, <strong>estimaciones más precisas</strong></p>
<ul>
<li>Calcule el intervalo de confianza al 99% de cada muestra ¿Qué pasa con el intervalo de confianza a medida que aumenta el tamaño de la muestra?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(muestra_50, <span class="at">conf.level =</span> <span class="fl">0.99</span>)<span class="sc">$</span>conf.int</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.03139 68.84861
attr(,"conf.level")
[1] 0.99</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(muestra_500, <span class="at">conf.level =</span> <span class="fl">0.99</span>)<span class="sc">$</span>conf.int</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.76309 68.33691
attr(,"conf.level")
[1] 0.99</code></pre>
</div>
</div>
<div style="background-color: #b71c1c; color: #ffffff; border: 1px solid #8e0000; border-radius: 6px; padding: 0.8rem 1rem;">
<p>A medida que la muestra se vuelve más grande, el error estándar se vuelve más pequeño, es decir, es más preciso en la estimación.</p>
<p>A medida que el intervalo de confianza aumenta en su nivel de confiabilidad, el rango se vuelve más amplio y, en consecuencia, la estimación es menos precisa, <strong>a menos que aumente su tamaño muestral</strong></p>
</div>
</section>
<section id="test-de-hipótesis" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Test de hipótesis</h1>
<p>Hasta ahora utilizamos el error estándar para expresar la incertidumbre de una estimación mediante intervalos de confianza. Ahora usaremos esa misma idea de variabilidad muestral para responder una nueva pregunta: ¿las diferencias entre grupos que logramos observar en una muestra, pueden ser representativas de a nivel de la población?</p>
<p>Para este punto, recurriremos a todas las herramientas que hemos aprendido hasta ahora:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th>Concepto</th>
<th>Definición</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Curva normal</td>
<td>Distribución teórica que nos entrega un estándar para comparar distribuciones empíricas</td>
</tr>
<tr class="even">
<td>Teorema central del límite</td>
<td>Al calcular un estadístico de distintas muestras de una misma población, estos valores se distribuirán de manera normal</td>
</tr>
<tr class="odd">
<td>Error estándar</td>
<td>Desviación estándar de los promedios de distintas muestras de una misma población</td>
</tr>
<tr class="even">
<td>Puntajes Z</td>
<td>Medida estandarizada la cual se expresa en términos de desviación estándar</td>
</tr>
<tr class="odd">
<td>Intervalos de confianza</td>
<td>Rango de probabilidad de un parámetro poblacional</td>
</tr>
</tbody>
</table>
<p>Para esta sección del práctico, trabajaremos con un subconjunto de datos previamente procesados de la Encuesta de Caracterización Socioeconómica (CASEN) del año 2022, elaborada por el <a href="https://observatorio.ministeriodesarrollosocial.gob.cl/">Ministerio de Desarrollo Social y Familia</a>.</p>
<p>Para este ejercicio, obtendremos directamente esta base desde internet. No obstante, también tienes la opción de acceder a la misma información a través del siguiente enlace: <a href="https://github.com/cursos-metodos-facso/datos-ejemplos/raw/main/proc_casen.RData"><i class="fa-solid fa-table" aria-label="table"></i> <code>CASEN 2022</code></a>. Desde allí, podrás descargar el archivo que contiene el subconjunto procesado de la base de datos CASEN 2022.</p>
<section id="los-cinco-pasos-para-la-inferencia-estadística" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="los-cinco-pasos-para-la-inferencia-estadística"><span class="header-section-number">2.1</span> Los cinco pasos para la inferencia estadística</h2>
<p>En inferencia, las pruebas de hipótesis nos permiten evaluar qué tan compatibles son los resultados observados en nuestra muestra con una hipótesis planteada sobre la población. Aquí recomendamos una lista de cinco pasos lógicos para enfrentarnos a la inferencia estadística:</p>
<style>
  table {
    margin-left: auto; /* Ajustamos el margen izquierdo a automático */
    margin-right: auto; /* Ajustamos el margen derecho a automático */
    border-collapse: collapse;
    width: 60%;
    border: 2px solid black;
  }
  
  th, td {
    border: 1px solid #D3D3D3;
    padding: 8px;
    text-align: center;
  }
</style>
<table>
<tbody><tr>
<th class="cell-left">
Paso
</th>
<th class="cell-left">
Detalle
</th>
</tr>
<tr>
<td class="cell-left">
1
</td>
<td class="cell-left">
Formula <span class="math inline">\(H_0\)</span> y <span class="math inline">\(H_A\)</span> y estipula la dirección de la prueba
</td>
</tr>
<tr>
<td class="cell-left">
2
</td>
<td class="cell-left">
Calcula el error estándar (SE) y el valor estimado de la prueba (ej: Z o t)
</td>
</tr>
<tr>
<td class="cell-left">
3
</td>
<td class="cell-left">
Especifica la probabilidad de error <span class="math inline">\(\alpha\)</span> y el valor crítico de la prueba
</td>
</tr>
<tr>
<td class="cell-left">
4
</td>
<td class="cell-left">
Contrasta el valor estimado con el valor crítico
</td>
</tr>
<tr>
<td class="cell-left">
5
</td>
<td class="cell-left">
Interpreta los resultados
</td>
</tr>
</tbody></table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>La hipótesis nula (<span class="math inline">\(H_{0}\)</span>) es la contraria a la hipótesis original, y es la buscamos <strong>falsar</strong></p>
</div>
</div>
<p>Además de estos 5 pasos también existe la posibilidad de calcular un intervalo de confianza, que acompañe la precisión de nuestra estimación.</p>
</section>
<section id="preparación-datos" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="preparación-datos"><span class="header-section-number">2.2</span> Preparación datos</h2>
<p>Comencemos por preparar nuestros datos. Iniciamos cargando las librerías necesarias.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, <span class="co"># Manipulación datos</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>               gginference, <span class="co"># Visualización </span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>               rempsyc, <span class="co"># Reporte</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>               kableExtra, <span class="co"># Tablas</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>               broom, <span class="co"># Varios</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>               flextable <span class="co"># nice table</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>               )</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># para desactivar notación científica</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># para limpiar el entorno de trabajo</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>dplyr</code> será uno de los paquetes más frecuentrados en nuestro flujo de trabajo, ya que nos entrega las herramientas esenciales para el procesamiento de datos sociales. Algunas de ellas nos permiten realizar el filtrado, selección, orden y creación de variables.</p>
</div>
</div>
<p>Cargamos los datos directamente desde internet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://github.com/cursos-metodos-facso/datos-ejemplos/raw/main/proc_casen.RData"</span>)) <span class="co">#Cargar base de datos</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A continuación, exploramos la base de datos <strong>proc_casen</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_casen) <span class="co"># Nombre de columnas</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "id_vivienda"      "folio"            "id_persona"       "hogar"           
 [5] "nucleo"           "varunit"          "varstrat"         "expr"            
 [9] "edad"             "sexo"             "educ"             "activ"           
[13] "y1"               "ytrabajocor"      "pobreza_multi_5d" "o15"             
[17] "qaut"             "fdt"              "ocupado"          "desocupado"      
[21] "inact"            "hijo"             "n_educ"           "universitaria"   
[25] "tipo_ocup"        "ss_salud"         "ayuda_moverse"    "ayuda_thogar"    
[29] "disc_fisica"     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(proc_casen) <span class="co"># Dimensiones</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 202111     29</code></pre>
</div>
</div>
<p>Contamos con 29 variables (columnas) y 202.111 observaciones (filas).</p>
</section>
<section id="recordemos" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="recordemos"><span class="header-section-number">2.3</span> Recordemos…</h2>
<p>En estadística, la formulación de hipótesis que implica dos variables (o la comparación de grupos) busca determinar si las diferencias que se encuentran en la muestra son extrapolables a la población.</p>
<p>Ahora vamos a aprender a contrastar hipótesis sobre diferencias entre grupos. Si nuestra hipótesis plantea <strong>solamente</strong> que los <strong>grupos son diferentes</strong>, sin especificar cuál tendrá un promedio mayor, utilizamos una <strong>prueba de dos colas</strong> o <strong>no direccional</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Diferencias de medias (o prueba de dos colas)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Contrastamos la <em>hipótesis nula</em> de <em>no</em> diferencias entre grupos: <span class="math display">\[  H_{0}: \mu_{1} - \mu_{2} = 0 \]</span> En relación a una <em>hipótesis alternativa</em> sobre <em>diferencias</em> entre grupos: <span class="math display">\[  H_{A}: \mu_{1} - \mu_{2} \neq 0 \]</span></p>
</div>
</div>
<p>Además, podemos <strong>plantear hipótesis</strong> respecto a que el valor de cierto parámetro para un grupo <strong>puede ser mayor o menor</strong> al de otro grupo. A esto se le conoce como <strong>hipótesis de una cola</strong> y lo veremos más adelante.</p>
<p>Veamos ahora cómo aplicar todos estos conocimientos con ejercicios. Primero, para asegurar la reproducibilidad de los resultados, utilizamos <code>set.seed</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># Fijar la semilla para reproducibilidad</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="ejercicio-1" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="ejercicio-1"><span class="header-section-number">2.4</span> Ejercicio 1</h2>
<p>Estamos en un escenario donde la pregunta de investigación es: <em>¿Existen diferencias salariales entre hombres y mujeres en Chile?</em></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para diferencia de medias utilizaremos <em><strong>prueba t</strong></em>, la cual es una especie de extensión de la prueba Z para diferencia de medias, y que se asimila a Z con muestras mayores a 30. Por lo tanto, por el momento vamos a asumir que Z=t, y sus diferencias se verán en el próximo práctico</p>
</div>
</div>
<p>Para contrastar esta hipótesis, vamos utilizar la base de datos <code>proc_casen</code>, seleccionaremos las variables <code>sexo</code> e <code>ytrabajocor</code> (ingresos) y haremos un subset de datos de 1.500 casos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>casen_subset <span class="ot">&lt;-</span> proc_casen <span class="sc">%&gt;%</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sexo, ytrabajocor) <span class="sc">%&gt;%</span> <span class="co"># seleccionamos</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">1500</span>) <span class="co"># extraemos una muestra de 1500 casos</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>casen_subset <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(casen_subset) <span class="co"># eliminamos casos perdidos (listwise)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>El símbolo <code>%&gt;%</code> se llama pipe, y es una de las funciones más útiles de R. Su utilidad radica en que permite <strong>encadenar operaciones</strong>, es decir, lee el código como una secuencia de pasos en lugar de funciones aisladas, donde el resultado de un comando pasa a ser el primer argumento del siguiente comando, lo que permite ahorrar líneas de código</p>
</div>
</div>
<p>Generamos tabla para visualizar la distribución de los datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>casen_subset <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(sexo) <span class="sc">%&gt;%</span> <span class="co"># se agrupan por la variable categórica </span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">Obs. =</span> <span class="fu">n</span>(), <span class="co"># columna para el N de cada categoría</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Promedio =</span> <span class="fu">mean</span>(ytrabajocor, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">SD =</span> <span class="fu">sd</span>(ytrabajocor, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> <span class="co"># se agregan las operaciones a presentar en la tabla</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>) <span class="co"># se genera la tabla</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">sexo</th>
<th style="text-align: right;">Obs.</th>
<th style="text-align: right;">Promedio</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">379</td>
<td style="text-align: right;">690724.8</td>
<td style="text-align: right;">613238.9</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">309</td>
<td style="text-align: right;">585360.4</td>
<td style="text-align: right;">567737.7</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Ahora vamos con los <a href="https://correlacional.netlify.app/slides/05-inferencia4.html#33">5 pasos de la inferencia</a></p>
<p><strong>1. Formulación de hipótesis</strong></p>
<p>El primer aspecto a establecer es el tipo de hipótesis a formular: ¿Direccional o no direccional? En este caso, la pregunta <strong>no</strong> indica una <strong>direccionalidad</strong>, por lo tanto corresponde a una <strong>hipótesis no direccional</strong>. Si hubiera sido una pregunta que hiciera referencia a una mayoría de un grupo por sobre otro (“¿Es el salario de los hombres mayor que el de las mujeres?”) correspondería a una hipótesis direccional.</p>
<p>La hipótesis general es que el salario de los hombres es <strong>distinto</strong> que el de las mujeres. Pasando a lenguaje de hipótesis, esto se plantea como:</p>
<p><strong>Hipótesis alternativa</strong>:</p>
<p><span class="math display">\[H_{a}: \bar{X}_{hombres} -  \bar{X}_{mujeres} \neq 0\]</span></p>
<p><strong>Hipótesis nula</strong>:</p>
<p><span class="math display">\[H_{0}: \bar{X}_{hombres} -  \bar{X}_{mujeres}= 0\]</span></p>
<p><strong>2. Obtención del error estándar y estadístico de prueba</strong></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>La fórmula para error estándar en diferencia de medias es:</p>
<p><span class="math display">\[SE=\sqrt{\frac{\sigma_{diff}}{n_a}+\frac{\sigma_{diff}}{n_b}}\]</span></p>
</div>
</div>
<p>Ahora aplicamos la fórmula con nuestros datos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>media_hombres <span class="ot">&lt;-</span> <span class="fu">mean</span>(casen_subset<span class="sc">$</span>ytrabajocor[casen_subset<span class="sc">$</span>sexo <span class="sc">==</span> <span class="dv">1</span>]) <span class="co"># media para hombres</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>media_mujeres <span class="ot">&lt;-</span> <span class="fu">mean</span>(casen_subset<span class="sc">$</span>ytrabajocor[casen_subset<span class="sc">$</span>sexo <span class="sc">==</span> <span class="dv">2</span>]) <span class="co"># media para mujeres</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>var_hombres <span class="ot">&lt;-</span> <span class="fu">var</span>(casen_subset<span class="sc">$</span>ytrabajocor[casen_subset<span class="sc">$</span>sexo <span class="sc">==</span> <span class="dv">1</span>]) <span class="co"># varianza para hombres</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>var_mujeres <span class="ot">&lt;-</span> <span class="fu">var</span>(casen_subset<span class="sc">$</span>ytrabajocor[casen_subset<span class="sc">$</span>sexo <span class="sc">==</span> <span class="dv">2</span>]) <span class="co"># varianza para mujeres</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>n_hombres <span class="ot">&lt;-</span> <span class="fu">length</span>(casen_subset<span class="sc">$</span>ytrabajocor[casen_subset<span class="sc">$</span>sexo <span class="sc">==</span> <span class="dv">1</span>]) <span class="co"># n para hombres</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>n_mujeres <span class="ot">&lt;-</span> <span class="fu">length</span>(casen_subset<span class="sc">$</span>ytrabajocor[casen_subset<span class="sc">$</span>sexo <span class="sc">==</span> <span class="dv">2</span>]) <span class="co"># n para mujeres</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a><span class="co"># aplicamos la fórmula de error estándar para diferencia de medias</span></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>se_diff <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((var_hombres <span class="sc">/</span> n_hombres) <span class="sc">+</span> (var_mujeres <span class="sc">/</span> n_mujeres))</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>se_diff</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 45115.12</code></pre>
</div>
</div>
<p><strong>3. Establecer probabilidad de error</strong></p>
<p>Recordemos que, por convención, nuestra probabilidad de error es <span class="math inline">\(a\)</span> = 0.05</p>
<p><strong>4. Intervalo de confianza</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>diff_medias <span class="ot">&lt;-</span> media_hombres <span class="sc">-</span> media_mujeres <span class="co"># diferencia de medias observada</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>lim_inf <span class="ot">&lt;-</span> diff_medias <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_diff <span class="co"># límite inferior del intervalo</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>lim_sup <span class="ot">&lt;-</span> diff_medias <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_diff <span class="co"># límite superior del intervalo</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>lim_inf</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16938.82</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>lim_sup</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 193790.1</code></pre>
</div>
</div>
<p>Entonces nuestro intervalo de confianza quedaría de tal manera: <span class="math inline">\(CI\)</span>[16939.82; 193790.1]</p>
<p>Ahora…</p>
<p><strong>Pasos 2, 3 y 4 de una vez con R</strong></p>
<ul>
<li><p>Obtener error estándar y estadístico de prueba empírico correspondiente (ej: Z o t)</p></li>
<li><p>Establecer la probabilidad de error <span class="math inline">\(\alpha\)</span> (usualmente 0.05) y obtener valor crítico (teórico) de la prueba correspondiente</p></li>
<li><p>Cálculo de intervalo de confianza / contraste valores empírico/crítico</p></li>
</ul>
<p>Luego de establecer las hipótesis nos vamos directamente al software, ya que R nos permite obtener de una vez toda la información de los pasos 2, 3 y 4.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>test_ej1 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(casen_subset<span class="sc">$</span>ytrabajocor <span class="sc">~</span> casen_subset<span class="sc">$</span>sexo, <span class="co"># define las variables que serán sometidas al test de hipótesis</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="co"># define la hipótesis alternativa</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="co"># establece el nivel de confianza</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>test_ej1</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  casen_subset$ytrabajocor by casen_subset$sexo
t = 2.3355, df = 674.99, p-value = 0.01981
alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
95 percent confidence interval:
  16781.61 193947.32
sample estimates:
mean in group 1 mean in group 2 
       690724.8        585360.4 </code></pre>
</div>
</div>
<p>También podemos visualizarlo en una tabla más amable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>stats.table <span class="ot">&lt;-</span> <span class="fu">tidy</span>(test_ej1, <span class="at">conf_int =</span> T) <span class="co"># se convierten los datos del test en un dataframe</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nice_table</span>(stats.table, <span class="at">broom =</span> <span class="st">"t.test"</span>) <span class="co"># convierte el dataframe en tabla</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-3b802544{table-layout:auto;}.cl-3b708b34{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3b708b3e{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3b708b48{font-family:'Times New Roman';font-size:7.2pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;vertical-align:sub;}.cl-3b7e0070{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-3b7e0084{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-3b7e0f52{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3b7e0f53{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3b7e0f5c{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-3b802544"><thead><tr style="overflow-wrap:break-word;"><th class="cl-3b7e0f52"><p class="cl-3b7e0070"><span class="cl-3b708b34">Method</span></p></th><th class="cl-3b7e0f52"><p class="cl-3b7e0070"><span class="cl-3b708b34">Alternative</span></p></th><th class="cl-3b7e0f52"><p class="cl-3b7e0070"><span class="cl-3b708b34">Mean 1</span></p></th><th class="cl-3b7e0f52"><p class="cl-3b7e0070"><span class="cl-3b708b34">Mean 2</span></p></th><th class="cl-3b7e0f52"><p class="cl-3b7e0070"><span class="cl-3b708b3e">M</span><span class="cl-3b708b48">1</span><span class="cl-3b708b34"> - </span><span class="cl-3b708b3e">M</span><span class="cl-3b708b48">2</span></p></th><th class="cl-3b7e0f52"><p class="cl-3b7e0070"><span class="cl-3b708b3e">t</span></p></th><th class="cl-3b7e0f52"><p class="cl-3b7e0070"><span class="cl-3b708b3e">df</span></p></th><th class="cl-3b7e0f52"><p class="cl-3b7e0070"><span class="cl-3b708b3e">p</span></p></th><th class="cl-3b7e0f52"><p class="cl-3b7e0070"><span class="cl-3b708b34">95% CI</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-3b7e0f53"><p class="cl-3b7e0084"><span class="cl-3b708b34">Welch Two Sample t-test</span></p></td><td class="cl-3b7e0f5c"><p class="cl-3b7e0070"><span class="cl-3b708b34">two.sided</span></p></td><td class="cl-3b7e0f5c"><p class="cl-3b7e0070"><span class="cl-3b708b34">690,724.82</span></p></td><td class="cl-3b7e0f5c"><p class="cl-3b7e0070"><span class="cl-3b708b34">585,360.36</span></p></td><td class="cl-3b7e0f5c"><p class="cl-3b7e0070"><span class="cl-3b708b34">105,364.47</span></p></td><td class="cl-3b7e0f5c"><p class="cl-3b7e0070"><span class="cl-3b708b34">2.34</span></p></td><td class="cl-3b7e0f5c"><p class="cl-3b7e0070"><span class="cl-3b708b34">674.99</span></p></td><td class="cl-3b7e0f5c"><p class="cl-3b7e0070"><span class="cl-3b708b34">.020*</span></p></td><td class="cl-3b7e0f5c"><p class="cl-3b7e0070"><span class="cl-3b708b34">[16781.61, 193947.32]</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Visualicemos la distribución de esta prueba y su zona de rechazo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>gginference<span class="sc">::</span><span class="fu">ggttest</span>(test_ej1)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-practico_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>5. Interpretación</strong></p>
<p>Antes de la interpretación, aclaremos algunos conceptos:</p>
<ul>
<li><p>El valor <span class="math inline">\(p\)</span> es la <strong>probabilidad</strong> de observar un resultado (una diferencia de medias, un estadístico <span class="math inline">\(t\)</span>) igual o más extremo que el obtenido en la muestra, <strong>asumiendo que <span class="math inline">\(H_0\)</span> es verdadera</strong></p></li>
<li><p>Si <span class="math inline">\(p &lt; \alpha\)</span> → rechazamos <span class="math inline">\(H_0\)</span> (el resultado es “estadísticamente significativo”: es poco probable observar algo así si <span class="math inline">\(H_0\)</span> fuera cierta)</p></li>
<li><p>Si <span class="math inline">\(p \geq \alpha\)</span> → no rechazamos <span class="math inline">\(H_0\)</span> (los datos son compatibles con la ausencia de efecto)</p></li>
</ul>
<p>Ahora, pasemos a la interpretación:</p>
<p>La prueba t que evalúa la diferencia de medias entre el salario y el sexo sugiere que el efecto es positivo y estadísticamente signficativo (diferencia = 105.364,47, t = 2.34, p &lt; .05). El valor <strong><span class="math inline">\(p\)</span></strong> indica que <strong>la probabilidad de observar una diferencia de esta magnitud, o mayor, bajo la suposición de <span class="math inline">\(H_{0}\)</span> es menor al 5%</strong>. Por tanto, con un 95% de confianza, rechazamos la <span class="math inline">\(H_{0}\)</span> ya que existe <strong>evidencia a favor</strong> de nuestra <span class="math inline">\(H_{A}\)</span> respecto a que hay diferencias de salario entre hombres y mujeres.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Mientras más grande (en valor absoluto) sea <span class="math inline">\(t\)</span>, más lejos está el resultado observado de lo que <span class="math inline">\(H_0\)</span> predice, y por lo tanto más pequeño es el valor <span class="math inline">\(p\)</span> asociado</p>
</div>
</div>
</section>
<section id="ejercicio-autónomo" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="ejercicio-autónomo"><span class="header-section-number">2.5</span> Ejercicio autónomo</h2>
<p>Tomando como ejemplo el trabajo de la ganadora del Premio Nobel de Economía 2023 Claudia Goldin, en este siguiente ejercicio evaluaremos la siguiente pregunta: <em>¿Es el salario de las mujeres con hijos distinto al salario de las mujeres sin hijos?</em> Por ende, usaremos <strong>prueba <span class="math inline">\(t\)</span></strong> para diferencia de medias.</p>
<p>Siga las siguientes instrucciones:</p>
<ul>
<li><p>Utilice la base de datos <code>proc_casen</code>, seleccionando las variables <code>ocupado</code>, <code>sexo</code>, <code>ytrabajocor</code> e <code>hijo</code></p></li>
<li><p>Filtre por <code>ocupado == 1</code> y <code>sexo == 2</code> para quedarnos sólo con mujeres ocupadas</p></li>
<li><p>Genere una muestra aleatoria de 1.500 casos con la función <code>sample_n()</code> y elimine los casos pérdidos con <code>na.omit()</code></p></li>
<li><p>Genere una tabla de descriptivos presentando la cantidad de casos, la media y la desviación estándar.</p></li>
<li><p>Aplique los 5 pasos para la inferencia mediante el uso de software</p></li>
<li><p>Interprete los resultados</p></li>
</ul>
</section>
</section>
<section id="repaso" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Repaso</h1>
<p>Hoy vimos:</p>
<ul>
<li><p>Repaso de los intervalos de confianza, observando la importancia del error estándar y la estimación de rangos para encontrar el parámetro poblacional</p></li>
<li><p>Contraste de hipótesis mediante pruebas de diferencias de medias</p></li>
<li><p>Aplicar los 5 pasos para la inferencia mediante software</p></li>
</ul>
<p>Para cerrar…</p>
<p><img src="https://correlacional.netlify.app/slides/img/rechazar_meme.png" class="img-fluid"></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nuestro objetivo no es rechazar <span class="math inline">\(H_{0}\)</span> a toda costa, sino evaluar si los datos entregan evidencia suficiente para rechazarla. Un resultado en que no rechazamos <span class="math inline">\(H_{0}\)</span> también es un resultado estadístico válido</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/correlacional\.metodos-facso\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2026 by <a href="https://www.jc-castillo.com">Juan Castillo</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/cursos-metodos-facso/correlacional-2026">View the source at <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></p>
</div>
  </div>
</footer>




</body></html>