{
  "hash": "25891182e9521f3a8d945f7d8f6f65a7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Integración e Interpretación de Inferencia\"\ndate: \"2026-09-02\"\nlang: es\n\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n    code-copy: true\n    code-fold: false\n    code-tools: true\n    highlight-style: github\n    embed-resources: true\n    page-layout: full\n    grid:\n      body-width: 1100px\n      margin-width: 280px\n      gutter-width: 1.5rem\n\nexecute:\n  freeze: auto\n  cache: false\n  warning: false\n  message: false\n---\n\n<style>\n/* Código escrito dentro del texto */\n:not(pre) > code {\n  color: #00695c !important;\n  background-color: #eef7f6 !important;\n  padding: 0.1em 0.3em;\n  border-radius: 4px;\n}\n\n/* Resultados producidos por R */\n.cell-output pre {\n  color: #17233a !important;\n  background-color: #e8f5f3 !important;\n  border-left: 4px solid #009688 !important;\n  padding: 0.8em 1em !important;\n}\n\n.cell-output pre code {\n  color: #17233a !important;\n  background-color: transparent !important;\n}\n\n/* Lectura de párrafos */\nmain.content p,\n.callout-body p {\n  text-align: justify;\n  text-justify: inter-word;\n  hyphens: auto;\n}\n\n/* Figuras */\n#quarto-content main.content img {\n  display: block;\n  max-width: 100%;\n  height: auto;\n}\n\n#TOC .nav-link {\n  font-size: 0.95rem !important;\n  line-height: 1.15;\n  padding-top: 0.12rem;\n  padding-bottom: 0.12rem;\n}\n\ndiv.sourceCode,\npre.sourceCode {\n  background-color: #F7F8FA !important;\n  border: 1px solid #D9DEE7;\n  border-radius: 6px;\n}\n\n/* Evita un segundo fondo dentro del chunk */\npre.sourceCode code {\n  background-color: transparent !important;\n}\n\n\n/* Quitar el borde azul exterior de las salidas de R */\n#quarto-content .cell-output.cell-output-stdout {\n  border: none !important;\n  border-left: none !important;\n  outline: none !important;\n  box-shadow: none !important;\n  background: transparent !important;\n}\n\n/* Dar un borde gris suave solamente al resultado */\n#quarto-content .cell-output.cell-output-stdout > pre {\n  color: #17233a !important;\n  background: #F7F8FA !important;\n  border: 1px solid #D9DEE7 !important;\n  border-left: 4px solid #B8C2D1 !important;\n  outline: 0 !important;\n  box-shadow: none !important;\n  border-radius: 6px !important;\n  padding: 0.8em 1em !important;\n}\n\n</style>\n\n\n# Objetivo de la práctica\n\nHasta ahora hemos aprendido, progresivamente:\n\n1. A calcular puntajes Z y errores estándar\n2. A calcular e interpretar intervalos de confianza\n3. A plantear y contrastar hipótesis direccionales y no direccionales\n\nHoy el objetivo es **integrar** estos aprendizajes: Tomar decisiones pertinentes, ejecutarles en R, e interpretarlas **estadística y sociológicamente**\n\n# Repaso\n\nPero primero, volvamos a los contenidos que desarrollados en esta unidad. \n\n## Glosario\n\n**Curva Normal**: Distribución teórica que nos entrega un estándar para comparar distribuciones empíricas.\n\n**Puntajes Z**: Medida estandarizada que se expresa en desviaciones estándar respecto a la media.\n\n**Teorema central del límite**: Define que al calcular un estadístico de distintas muestra de una misma población, estos valores seguirán una distribución normal.\n\n**Error estándar**: Desviación estándar de los promedios de distintas muestras de una misma población. \n\n**Intervalos de confianza**: Rango de probabilidad de un parámetro poblacional\n\n**Nivel de Confianza**: Proporción en que el rango acierta. Se define como $1-\\alpha$, siendo $\\alpha$ la probabilidad de error. \n\n**Hipótesis**: Aseveración o predicción que se desprende una teoría sobre una situación que ocurren en la población.\n\n**Hipótesis nula**: Hipótesis contraria a nuestra teoría. Se expresa como $H_0$\n\n## Los 5 pasos de la inferencia\n\n| Paso | Detalle |\n|---|---|\n| 1 | Formula $H_0$ y $H_A$ y estipula la dirección de la prueba |\n| 2 | Calcula el error estándar (SE) y el valor estimado de la prueba |\n| 3 | Especifica la probabilidad de error $\\alpha$ y el valor crítico |\n| 4 | Contrasta el valor estimado con el valor crítico |\n| 5 | Interpreta los resultados |\n\n## ¿IC o prueba de hipótesis?\n\nNo toda pregunta requiere comparar grupos. Antes de elegir una prueba, conviene preguntarse:\n\n- ¿Quiero **estimar un valor poblacional** (un promedio, una proporción)?; o\n- ¿Quiero **comparar dos grupos**?\n\nEn el primer caso, observaremos el intervalo de confianza. En el segundo, utilizaremos la prueba t para diferencias de medias. \n\n## Dos colas o una cola?\n\nSi nuestra pregunta requiere realizar una prueba t, debemos decidir cuál es la dirección de nuestra hipótesis: \n\n| Pregunta | Hipótesis alternativa | `alternative` |\n|---|---|---|\n| ¿A y B son diferentes? | $\\mu_A - \\mu_B \\neq 0$ | `\"two.sided\"` |\n| ¿A > B? | $\\mu_A - \\mu_B > 0$ | `\"greater\"` |\n| ¿A < B? | $\\mu_A - \\mu_B < 0$ | `\"less\"` |\n\n::: {.callout-important}\nA la hora de decidir que técnica utilizar, no hay realmente decisiones mejores que otra. Es la pregunta de investigación la que debe guiar la elección de la técnica, no al revés. \n:::\n\n::: {.callout-tip}\n\n## Antes de seguir\n\nSi quisiéramos comparar el ingreso promedio entre personas de dos comunas del Gran Santiago, ¿usaríamos un intervalo de confianza o una prueba t? Si es una prueba t, ¿de una cola o de dos?\n:::\n\n# Interpretación\n\nHasta ahora,  nos hemos enfocado en entender y aplicar conceptos claves en la estadística inferencial. Sin embargo, tan importante como eso es **interpretar y reportar** correctamente los hallazgos que entreguen las pruebas estadísticas. Por ejemplo, observemos la siguiente interpretación a la pregunta planteada en el [práctico 3](03-practico.qmd): ¿Existen diferencias entre los ingresos laborales promedio de las mujeres con hijos y las mujeres sin hijos?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-4730e2b8{table-layout:auto;}.cl-47216bd0{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-47216be4{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-47216bee{font-family:'Times New Roman';font-size:7.2pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3.6pt;}.cl-47287a9c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-47287ab0{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-4728baf2{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4728bb06{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-4728bb07{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-4730e2b8'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-4728baf2\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">Method</span></p></th><th class=\"cl-4728baf2\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">Alternative</span></p></th><th class=\"cl-4728baf2\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">Mean 1</span></p></th><th class=\"cl-4728baf2\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">Mean 2</span></p></th><th class=\"cl-4728baf2\"><p class=\"cl-47287a9c\"><span class=\"cl-47216be4\">M</span><span class=\"cl-47216bee\">1</span><span class=\"cl-47216bd0\"> - </span><span class=\"cl-47216be4\">M</span><span class=\"cl-47216bee\">2</span></p></th><th class=\"cl-4728baf2\"><p class=\"cl-47287a9c\"><span class=\"cl-47216be4\">t</span></p></th><th class=\"cl-4728baf2\"><p class=\"cl-47287a9c\"><span class=\"cl-47216be4\">df</span></p></th><th class=\"cl-4728baf2\"><p class=\"cl-47287a9c\"><span class=\"cl-47216be4\">p</span></p></th><th class=\"cl-4728baf2\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">95% CI</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-4728bb06\"><p class=\"cl-47287ab0\"><span class=\"cl-47216bd0\">Welch Two Sample t-test</span></p></td><td class=\"cl-4728bb07\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">two.sided</span></p></td><td class=\"cl-4728bb07\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">706,113.65</span></p></td><td class=\"cl-4728bb07\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">590,847.70</span></p></td><td class=\"cl-4728bb07\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">115,265.96</span></p></td><td class=\"cl-4728bb07\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">2.39</span></p></td><td class=\"cl-4728bb07\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">492.66</span></p></td><td class=\"cl-4728bb07\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">.017*</span></p></td><td class=\"cl-4728bb07\"><p class=\"cl-47287a9c\"><span class=\"cl-47216bd0\">[20564.30, 209967.62]</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n> Observamos que el ingreso de las mujeres sin hijos es diferente al de las mujeres con hijos, y que p es menor a 0.05. De tal modo, podemos comprobar que nuestra hipótesis es verdadera.\n\n¿Que está mal con esta interpretación?\n\n**¿Qué debe tener una buena interpretación estadística?**\n\n1. **Resultado descriptivo**: qué se observó en la muestra y en qué dirección. El tamaño de la muestra, la media, la desviación estándar, la diferencia, etc., según corresponda. \n2. **Resultado inferencial**: Mencionar de manera explícita las técnicas estadísticas utilizadas, reportando el estadístico que corresponda (el valor *t* en este caso), el valor *p* y el IC — reportados con sus valores, no solo mencionados.\n3. **Decisión estadística explícita**: se rechaza o no se rechaza $H_0$ o la $H_A$, y con qué $\\alpha$.\n4. **Conclusión sustantiva**: Se debe responder la pregunta de investigación en lenguaje sociológico, no solo estadístico. \n5. **Limitaciones**: Se debe tener claro el alcance de los hallazgos, evitando sobreinterpretaciones (por ejemplo, un p significativo pero un efecto pequeño) afirmaciones grandilocuentes del tipo \"comprobamos que la hipótesis es verdadera\" o \"establecemos que x es la causa de y\". \n\nTeniendo en cuenta estas recomendaciones, volvemos a escribir la interpretación a los resultados. \n\n> \"Los datos muestran que existe una diferencia de &#36;115.265,96 entre los ingresos de las mujeres sin hijos ($\\bar{x}_1$=706.113,65) y de las mujeres con hijos ($\\bar{x}_2$=590.847,69). A través de una prueba t para diferencia de medias, se observó que esta diferencia es estadísticamente significativa al 95% de confianza (*t*=2,39; *df*=492,66; *p*=0.017, *CI*[20.564,30-209.967,62]). Por lo tanto, se rechaza la $H_0$ de igualdad de medias entre los ingresos de mujeres con hijos y mujeres sin hijos\"\n\n::: {.callout-important}\n¿Qué interpretación sociológica le podemos dar estos hallazgos?\n\n**Lectura sugerida**: Budig, M. J., & England, P. (2001). The wage penalty for motherhood. *American Sociological Review, 66*(2), 204–225. https://doi.org/10.2307/2657415\n:::\n\nAdicionalmente, existen paquetes en R que pueden escribir interpretaciones de manera automática (en inglés), como `report`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!require(report)) install.packages(\"report\")\nlibrary(report)\n\ntest_goldin <- t.test(\n  ytrabajocor ~ grupo_hijo,\n  data = goldin_data,\n  alternative = \"two.sided\"\n)\n\nreport::report(test_goldin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEffect sizes were labelled following Cohen's (1988) recommendations.\n\nThe Welch Two Sample t-test testing the difference of ytrabajocor by grupo_hijo\n(mean in group Sin hijos = 7.06e+05, mean in group Con hijos = 5.91e+05)\nsuggests that the effect is positive, statistically significant, and small\n(difference = 1.15e+05, 95% CI [20564.30, 2.10e+05], t(492.66) = 2.39, p =\n0.017; Cohen's d = 0.22, 95% CI [0.04, 0.39])\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-caution}\n\nNunca se debe copiar y pegar la salida de `report`. Además de traducirla (si el reporte es en español), es necesario hacer ediciones, particularmente en el nombre de las variables y sus categorías. Una versión traducida y editada debería verse así: \n\nLa prueba t de Welch para dos muestras que evalúa la diferencia en los ingresos labores de mujeres con y sin hijos ($\\bar{x}_{sin hijos}$=706.113,65, $\\bar{x}_{con hijos}$=590.847,69) sugiere que el efecto es positivo, estadísticamente significativo y pequeño (diferencia = 115.265,96, IC 95% [20564,30, 209.967], t(492,66) = 2,39, p = 0,017; d de Cohen = 0,22, IC 95% [0,04, 0,39])\n:::\n\n\n::: {.callout-note}\n**¿Por que `report` indica que la diferencia es pequeña?**\n\nPorque estima un estadístico conocido como *d de Cohen* que permite estimar la **magnitud** del efecto. Se define como la diferencia entre las medias grupales divido por la desviación estándar agrupada de ambos grupos. \n\nCohen (1988) indicó que:\n\n- d>0.2 son considerados pequeños\n- d>0.5 son considerados medianos\n- d>0.8 son considerado grandes\n\nPor lo tanto, el efecto observado en este ejercicio (*d*=0.22) sería pequeño. \n:::\n\n# Ejercicios de Integración e Interpretación\n\nTrabajaremos nuevamente con `proc_casen`, que se carga con el código de más abajo. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(url(\"https://github.com/cursos-metodos-facso/datos-ejemplos/raw/main/proc_casen.RData\"))\n```\n:::\n\n\nBuscaremos responde dos preguntas de investigación. \n\n1. ¿Cuál es la edad promedio de las personas que necesitan ayuda para moverse dentro de su casa?\n2. ¿Existen diferencias en el ingreso promedio de las personas con discapacidad y sin discapacidad?\n\n\n### Pregunta 1\n\n> ¿Cuál es la edad promedio de las personas que necesitan ayuda para moverse dentro de su casa?\n\n**¿Es una pregunta de estimación o de comparación entre grupos?**\n\nSolo buscamos estimar la edad promedio de un grupo de personas (quienes necesitan ayuda para moverse). Por lo tanto, esta pregunta de investigación se puede responder solo observando sus intervalos de confianza. \n\n\n::: {.callout-important}\n¿Se podría realizar un test de hipótesis en este caso? En estricto rigor, sí. Sin embargo, la conclusión que obtendríamos es que la edad promedio de las personas que necesitan ayuda para moverse en casa es distinta a 0. ¿Es ésta una conclusión informativa para nuestra pregunta de investigación?\n:::\n\n**Preparar los datos**\n\nYa cargamos la base de datos, ahora vamos a procesar la variable `ayuda_moverse` para responder la pregunta de investigación. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creamos un subset\nsubset_1 <- proc_casen |> \n  # Filtramos para dejar solo las personas que necesitan ayuda muchas veces (4) o siempre (5)\n  dplyr::filter(ayuda_moverse >= 4)\n```\n:::\n\n\nComo sabemos que vamos a necesitar el tamaño de la muestra, así como el promedio y la desviación estándar de `edad`, las calcularemos de inmediato:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_edad <- nrow(subset_1)\nmedia_edad <- mean(subset_1$edad)\nsd_edad <- sd(subset_1$edad)\n\nn_edad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2364\n```\n\n\n:::\n\n```{.r .cell-code}\nmedia_edad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 73.15398\n```\n\n\n:::\n\n```{.r .cell-code}\nsd_edad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.78623\n```\n\n\n:::\n:::\n\n\nCon esto ya tenemos una estimación puntual de la edad de las personas que necesitan ayuda para moverse en su casa: 73,15 años para nuestra muestra, con una desviación estándar de 18.79.\n\n**Los 5 pasos de la inferencia estadística**\n\n*1. Formular Hipótesis*\n\nEn este caso, nuestra hipótesis nula es que la edad promedio de las personas que necesitan ayuda para moverse en casa es igual a 0 en la población.\n\n$$\nH_0: \\bar{x}_{edad} = 0\n$$\n\nEn referencia a la siguiente hipótesis alternativa:\n\n$$\nH_a: \\bar{x}_{edad} \\ne 0\n$$\n**Calcular el error estándar**\n\nRecordemos que el error estándar del promedio está definido por:\n\n$$\nSE = \\frac{s}{\\sqrt{n}}\n$$\n\nEn R, esto se calcularía así:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse_edad <- sd_edad/sqrt(n_edad)\n\nse_edad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3863812\n```\n\n\n:::\n:::\n\n\nEl error estándar de la media de edad de 0.39 años.\n\n*Definir la probabilidad de error $\\alpha$ y el valor crítico*\n\nSeguiremos la convención de de $\\alpha$=0.05, lo que se corresponde con el valor crítico de 1,96. \n\n*Calcular el intervalo de confianza*\n\nLa formula del intervalo de confianza para el promedio es:\n\n$$\nIC = \\bar{x} \\pm z_{\\alpha/2} \\cdot SE\n$$\n\nCalculemos en R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlim_inferior <- media_edad - 1.96 * se_edad\nlim_superior <- media_edad + 1.96 * se_edad\n\nlim_inferior\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 72.39667\n```\n\n\n:::\n\n```{.r .cell-code}\nlim_superior\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 73.91128\n```\n\n\n:::\n:::\n\n\n**Interpretación**\n\nA partir de una muestra 2364 personas, se estimó que la edad promedio de las personas que necesitan ayuda para moverse en su casa es de 73.15 años, con una desviación estándar de 18.79 años. Considerando un nivel de 95% de confianza (*SE*=0.39), se puede afirmar que la edad promedio en la población se encuentra entre los 72.4 y los 73.9 años. \n\n\n::: {.callout-important}\n\nLo de arriba es una interpretación estadística de los resultados. Para dar una interpretación sociológica valdría la pena remitirnos, por ejemplo, a la literatura sobre envejecimiento o tareas de cuidado en Chile. \n\n:::\n\n\n### Pregunta 2\n\n> ¿Existen diferencias en el ingreso promedio de las personas con discapacidad y sin discapacidad?\n\n**Procesar los datos**\n\nYa hemos trabajado antes con la variable `ytrabajocor`, que indica los ingresos labores de los individuos. Identificaremos las personas con y sin discapacidad con la variable `disc_fisica`, que indica que 1=no tiene discapacidad y 2=tiene discapacidad. Vamos a limpiar los casos perdidos y ponerle etiquetas a `disc_fisica`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creamos un subset con las variables de interés\nsubset_2 <- proc_casen |>\n  dplyr::select(ytrabajocor, disc_fisica)\n\n# Eliminamos los casos con información faltante\nsubset_2 <- na.omit(subset_2)\n\n# Reemplazamos los códigos de la variable `disc_fisica` por etiquetas\nsubset_2$disc_fisica <- factor(\n  subset_2$disc_fisica,\n  levels = c(1, 2),\n  labels = c(\n    \"No tiene discapacidad\",\n    \"Tiene discapacidad\"\n  )\n)\n```\n:::\n\n\nAprovechemos también de hacer una exploración descriptiva de los datos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset_2 |>\n  dplyr::group_by(disc_fisica) |>\n  dplyr::summarise(\n    N = dplyr::n(),\n    Media = mean(ytrabajocor),\n    SD = sd(ytrabajocor)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  disc_fisica               N   Media      SD\n  <fct>                 <int>   <dbl>   <dbl>\n1 No tiene discapacidad 86245 667067. 814001.\n2 Tiene discapacidad     2615 687027. 893880.\n```\n\n\n:::\n:::\n\n\n¿Que podemos observar en esta tabla?\n\n**Ejercicio autónomo**\n\nPara seguir, responda las siguientes preguntas:\n\n1. ¿Es una pregunta de estimación o de comparación entre grupos? ¿Qué técnica debemos utilizar?\n2. ¿Cuál es la hipótesis nula? ¿Y la alternativa?\n3. ¿La pregunta de investigación requiere de una hipótesis direccional o no direccional? ¿Por qué?\n4. Realice la inferencia y haga la interpretación de los resultados. \n\n# Síntesis\n\nHoy integramos lo aprendido en sesiones anteriores: decidir entre estimación (IC) y comparación de grupos (prueba t), elegir la dirección de la hipótesis, ejecutar el análisis en R, e interpretar los resultados de manera correcta. El dominio de estas herramientas nos permite pasar desde la mera descripción de una muestra a ser capaces de inferir y sacar conclusiones sobre la población de estudio. En la sociología, utilizamos estás técnicas para generar conocimiento conocimiento sobre la sociedad basada en evidencia estadística. \n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}